/******************************************************************************
 * @file   arm.cpp
 * @brief  Main app window arm group box implementation file.
 *
 * @author brice.c.aa
 ******************************************************************************/

// Related Header
#include "main_window.h"

// C++ Standard Library Headers
//   (none)

// Other Library Headers
//   (none)

// Project Headers
#include "colors.h"
#include "ui_main_window.h"  // auto-generated by Qt

/* --- TABLE OF CONTENTS ---
 * !Buttons
 */

//------------------------------------------------------------------------------
// !Buttons
//------------------------------------------------------------------------------

/**
 * @brief Sets all actuator target values in the UI using a comma-delimited
 *        string of values.
 *
 * @note This is a stop-gap approach, since end-effector tracking (i.e., inverse
 *       kinematics) is not yet implemented.
 */
void MainWindow::on_pb_quick_input_clicked() {
    const auto input = ui_->le_quick_input->text();

    if (input.isEmpty()) {
        logger_->Error("No values entered!");
        return;
    }

    // Parse input (format and delimiter are automatically validated)
    const auto values = input.split(',', Qt::SkipEmptyParts);

    constexpr auto expected_count = Actuator::kJointCountHebi
                                    + Actuator::kJointCountEpos;
    if (values.size() != expected_count) {
        logger_->Error("Provided values (" + std::to_string(values.size())
                       + ") != No. of actuators ("
                       + std::to_string(expected_count) + ")!");
        return;
    }

    // Set UI values (each Spin Box's min/max is automatically respected)
#if LIBRA_VERSION == 1
    ui_->sb_arm_roll->setValue(values[0].toDouble());
    ui_->sb_arm_pitch->setValue(values[1].toDouble());
    ui_->sb_arm_j1->setValue(values[2].toDouble());
    ui_->sb_arm_j2->setValue(values[3].toDouble());
    ui_->sb_arm_j3->setValue(values[4].toDouble());
#elif LIBRA_VERSION == 2
    ui_->sb_arm_yaw->setValue(values[0].toDouble());
    ui_->sb_arm_pitch->setValue(values[1].toDouble());
#endif

    // Clear the input box
    ui_->le_quick_input->clear();
}

/**
 * @brief Sends movement command signal(s) to all actuators.
 *
 * @note To improve ease of use, LIBRA-I arm actuator angles (J1, J2, J3) in the
 *       UI are shown relative to a forward-facing perspective directly behind
 *       the robot, where "0" is directly forward, and counterclockwise movement
 *       is considered "+" (positive).
 */
void MainWindow::on_pb_arm_start_clicked() {
#if LIBRA_VERSION == 1
    // TODO: this shouldn't be necessary because joint_defs exists and it's all
    // done in HebiThread now

    // Roll and Pitch are controlled by actuators MA and MB via differential drive
    auto val_ma = (-ui_->sb_arm_roll->value() + ui_->sb_arm_pitch->value());
    auto val_mb = (-ui_->sb_arm_roll->value() - ui_->sb_arm_pitch->value());

    auto val_j1 = ui_->sb_arm_j1->value();
    auto val_j2 = -ui_->sb_arm_j2->value();  // match operator perspective
    auto val_j3 = -ui_->sb_arm_j3->value();  // match operator perspective

    logger_->Debug(
        "Sending movement command (deg): MA=" + std::to_string(val_ma)
        + ", MB=" + std::to_string(val_mb) + ", J1=" + std::to_string(val_j1)
        + ", J2=" + std::to_string(val_j2) + ", J3=" + std::to_string(val_j3));

    emit CommandHebi({val_ma, val_mb, val_j1, val_j2, val_j3});
#elif LIBRA_VERSION == 2
    logger_->Debug("Sending movement command (deg): Yaw="
                   + std::to_string(ui_->sb_arm_yaw->value())
                   + ", Pitch=" + std::to_string(ui_->sb_arm_pitch->value()));

    emit CommandEpos({ui_->sb_arm_yaw->value()});
    emit CommandHebi({ui_->sb_arm_pitch->value()});
#endif
}

/**
 * @brief Toggles functionality related to automatic torque compensation. This
 *        includes automatic torque control of the central arm joint and, by
 *        association, automatic fluid system operation.
 *
 * @param checked Whether to enable automatic fluid system compensation
 *
 * @see on_pb_water_fill_A_clicked on_pb_water_drain_A_clicked
 *      on_pb_water_fill_B_clicked on_pb_water_drain_B_clicked
 */
void MainWindow::on_pb_autocomp_enable_toggled(bool checked) {
    logger_->Debug("ATC - " + std::string(checked ? "Enabling" : "Disabling")
                   + " automatic torque compensation");

    emit EnableAutoTorqueComp(checked);

    if (checked) {
        // Cancel any conflicting widget states
        ui_->pb_water_fill_A->setChecked(false);
        ui_->pb_water_drain_A->setChecked(false);
#if LIBRA_VERSION == 1
        ui_->pb_water_fill_B->setChecked(false);
        ui_->pb_water_drain_B->setChecked(false);
#endif

        // Clearly display an "enabled" state
        ui_->pb_autocomp_enable->setText(" DISABLE ATC");
        ui_->pb_autocomp_enable->setStyleSheet(
            QString("color: %1;").arg(Color::kRed));
    } else {
        // Revert to "disabled" state
        ui_->pb_autocomp_enable->setText(" ENABLE ATC");
        ui_->pb_autocomp_enable->setStyleSheet(
            QString("color: %1;").arg(Color::kGreen));
    }
}
