/******************************************************************************
 * @file   arm.cpp
 * @brief  Main app window arm group box implementation file.
 *
 * @author brice.c.aa
 ******************************************************************************/

// Related Header
#include "main_window.h"

// C++ Standard Library Headers
#include <sstream>

// Other Library Headers
//   (none)

// Project Headers
#include "colors.h"
#include "ui_main_window.h"  // auto-generated by Qt

/* --- TABLE OF CONTENTS ---
 * !Local Helpers
 * !Buttons
 */

//------------------------------------------------------------------------------
// !Local Helpers
//------------------------------------------------------------------------------

namespace {

std::vector<double> BuildHebiCommandVector(const Ui::MainWindow* ui) {
#if LIBRA_VERSION == 1
    const double roll = ui->sb_arm_roll->value();
    const double pitch = ui->sb_arm_pitch->value();

    // clang-format off
    return {
        Joint::JointToActuatorDifferential(Actuator::Name::kMA, roll, pitch),
        Joint::JointToActuatorDifferential(Actuator::Name::kMB, roll, pitch),
        Joint::JointToActuatorSimple(Actuator::Name::kJ1, ui->sb_arm_j1->value()),
        Joint::JointToActuatorSimple(Actuator::Name::kJ2, ui->sb_arm_j2->value()),
        Joint::JointToActuatorSimple(Actuator::Name::kJ3, ui->sb_arm_j3->value()),
    };
#elif LIBRA_VERSION == 2
    return {
        Joint::JointToActuatorSimple(Actuator::Name::kPitch, ui->sb_arm_pitch->value())
    };
    //clang-format on
#else
    return {};
#endif
}

}  // namespace

//------------------------------------------------------------------------------
// !Buttons
//------------------------------------------------------------------------------

/**
 * @brief Sets all actuator target values in the UI using a comma-delimited
 *        string of values.
 *
 * @note This is a stop-gap approach, since end-effector tracking (i.e., inverse
 *       kinematics) is not yet implemented.
 */
void MainWindow::on_pb_quick_input_clicked() {
    const auto input = ui_->le_quick_input->text();

    if (input.isEmpty()) {
        logger_->Error("No values entered!");
        return;
    }

    // Parse input (format and delimiter are automatically validated)
    const auto values = input.split(',', Qt::SkipEmptyParts);

    constexpr auto expected_count = Actuator::kJointCountHebi
                                    + Actuator::kJointCountEpos;
    if (values.size() != expected_count) {
        logger_->Error("Provided values (" + std::to_string(values.size())
                       + ") != No. of actuators ("
                       + std::to_string(expected_count) + ")!");
        return;
    }

    // Set UI values (each Spin Box's min/max is automatically respected)
#if LIBRA_VERSION == 1
    ui_->sb_arm_roll->setValue(values[0].toDouble());
    ui_->sb_arm_pitch->setValue(values[1].toDouble());
    ui_->sb_arm_j1->setValue(values[2].toDouble());
    ui_->sb_arm_j2->setValue(values[3].toDouble());
    ui_->sb_arm_j3->setValue(values[4].toDouble());
#elif LIBRA_VERSION == 2
    ui_->sb_arm_yaw->setValue(values[0].toDouble());
    ui_->sb_arm_pitch->setValue(values[1].toDouble());
#endif

    // Clear the input box
    ui_->le_quick_input->clear();
}

/**
 * @brief Sends movement command signal(s) to all actuators.
 *
 * @note To improve ease of use, LIBRA-I arm actuator angles (J1, J2, J3) in the
 *       UI are shown relative to a forward-facing perspective directly behind
 *       the robot, where "0" is directly forward, and counterclockwise movement
 *       is considered "+" (positive).
 */
void MainWindow::on_pb_arm_start_clicked() {
    // Get command vector(s) from UI values
    const auto hebi_command = BuildHebiCommandVector(ui_);

    if (debug_mode_) {
        // Format command string (for debug output)
        std::stringstream command_ss;
        command_ss << std::fixed << std::setprecision(2)
                   << "Sending movement command (deg): "
        // clang-format off
#if LIBRA_VERSION == 1
                   << "MA=" << hebi_command[0]
                   << ", MB=" << hebi_command[1]
                   << ", J1=" << hebi_command[2]
                   << ", J2=" << hebi_command[3]
                   << ", J3=" << hebi_command[4];
#elif LIBRA_VERSION == 2
                   << "Yaw=" << ui_->sb_arm_yaw->value()  // EPOS
                   << ", Pitch=" << hebi_command[0];
#endif
        // clang-format on

        logger_->Debug(command_ss.str());
    }

    // Send command(s)
#if LIBRA_VERSION == 2
    emit CommandEpos({ui_->sb_arm_yaw->value()});
#endif
    emit CommandHebi(hebi_command);
}

/**
 * @brief Toggles functionality related to automatic torque compensation. This
 *        includes automatic torque control of the central arm joint and, by
 *        association, automatic fluid system operation.
 *
 * @param checked Whether to enable automatic fluid system compensation
 *
 * @see on_pb_water_fill_A_clicked on_pb_water_drain_A_clicked
 *      on_pb_water_fill_B_clicked on_pb_water_drain_B_clicked
 */
void MainWindow::on_pb_autocomp_enable_toggled(bool checked) {
    logger_->Debug("ATC - " + std::string(checked ? "Enabling" : "Disabling")
                   + " automatic torque compensation");

    emit EnableAutoTorqueComp(checked);

    if (checked) {
        // Cancel any conflicting widget states
        ui_->pb_water_fill_A->setChecked(false);
        ui_->pb_water_drain_A->setChecked(false);
#if LIBRA_VERSION == 1
        ui_->pb_water_fill_B->setChecked(false);
        ui_->pb_water_drain_B->setChecked(false);
#endif

        // Clearly display an "enabled" state
        ui_->pb_autocomp_enable->setText(" DISABLE ATC");
        ui_->pb_autocomp_enable->setStyleSheet(
            QString("color: %1;").arg(Color::kRed));
    } else {
        // Revert to "disabled" state
        ui_->pb_autocomp_enable->setText(" ENABLE ATC");
        ui_->pb_autocomp_enable->setStyleSheet(
            QString("color: %1;").arg(Color::kGreen));
    }
}
