/******************************************************************************
 * @file   arm.cpp
 * @brief  Main app window arm group box implementation file.
 *
 * @author brice.c.aa
 ******************************************************************************/

// Related Header
#include "main_window.h"

// C++ Standard Library Headers
#include <sstream>

// Other Library Headers
//   (none)

// Project Headers
#include "colors.h"
#include "ui_main_window.h"  // auto-generated by Qt

/* --- TABLE OF CONTENTS ---
 * !Local Helpers
 * !Buttons
 */

//------------------------------------------------------------------------------
// !Local Helpers
//------------------------------------------------------------------------------

namespace {

/**
 * @brief Converts joint-space commands from the UI to actuator-space commands
 *        for actuators and returns an enum-ordered vector.
 *
 * @param ui Pointer to main UI object
 * @return Actuator-space ordered target values for all actuators
 *
 * @see Actuator::Name
 */
std::vector<double> GetActuatorTargets(const Ui::MainWindow* ui) {
    std::vector<double> targets(Actuator::kUndefined, 0.0);

    // Lambdas for converting joint-space UI values to actuator-space command values
    auto convert_and_set_simple = [&](Actuator::Name name, double val) {
        targets[name] = Joint::JointToActuatorSimple(name, val);
    };

    auto convert_and_set_diff = [&](Actuator::Name name, double roll,
                                    double pitch) {
        targets[name] = Joint::JointToActuatorDifferential(name, roll, pitch);
    };

    // Convert and save values based on Actuator::Name enum order
#if LIBRA_VERSION == 1
    const double roll = ui->sb_arm_roll->value();
    const double pitch = ui->sb_arm_pitch->value();

    convert_and_set_diff(Actuator::kMA, roll, pitch);
    convert_and_set_diff(Actuator::kMB, roll, pitch);
    convert_and_set_simple(Actuator::kJ1, ui->sb_arm_j1->value());
    convert_and_set_simple(Actuator::kJ2, ui->sb_arm_j2->value());
    convert_and_set_simple(Actuator::kJ3, ui->sb_arm_j3->value());
#elif LIBRA_VERSION == 2
    convert_and_set_simple(Actuator::kYaw, ui->sb_arm_yaw->value());
    convert_and_set_simple(Actuator::kPitch, ui->sb_arm_pitch->value());
#endif

    return targets;
}

/**
 * @brief Helper to resolve UI targets sequence layout-agnostically for input
 * parsers.
 *
 * @param ui Pointer to main UI object
 * @return Joint-space ordered pointers to target position Spin Boxes
 *
 * @see Joint::Name
 */
std::vector<QDoubleSpinBox*> GetOrderedSpinBoxes(const Ui::MainWindow* ui) {
#if LIBRA_VERSION == 1
    return {ui->sb_arm_roll, ui->sb_arm_pitch, ui->sb_arm_j1, ui->sb_arm_j2,
            ui->sb_arm_j3};
#elif LIBRA_VERSION == 2
    return {ui->sb_arm_yaw, ui->sb_arm_pitch};
#else
    return {};
#endif
}

}  // namespace

//------------------------------------------------------------------------------
// !Buttons
//------------------------------------------------------------------------------

/**
 * @brief Sets all actuator target values in the UI using a comma-delimited
 *        string of values.
 *
 * @note This is a stop-gap approach, since end-effector tracking (i.e., inverse
 *       kinematics) is not yet implemented.
 */
void MainWindow::on_pb_quick_input_clicked() {
    const auto input = ui_->le_quick_input->text();

    if (input.isEmpty()) {
        logger_->Error("No values entered!");
        return;
    }

    // Parse input (format and delimiter are automatically validated)
    const auto values = input.split(',', Qt::SkipEmptyParts);
    const auto target_boxes = GetOrderedSpinBoxes(ui_);

    if (static_cast<size_t>(values.size()) != target_boxes.size()) {
        logger_->Error("Provided values (" + std::to_string(values.size())
                       + ") != No. of actuators ("
                       + std::to_string(target_boxes.size()) + ")!");
        return;
    }

    // Set UI values (each Spin Box's min/max is automatically respected)
    for (size_t i = 0; i < target_boxes.size(); ++i) {
        target_boxes[i]->setValue(values[i].toDouble());
    }

    // Clear the input box
    ui_->le_quick_input->clear();
}

/**
 * @brief Sends movement command signal(s) to all actuators.
 *
 * @note To improve ease of use, LIBRA-I arm actuator angles (J1, J2, J3) in the
 *       UI are shown relative to a forward-facing perspective directly behind
 *       the robot, where "0" is directly forward, and counterclockwise movement
 *       is considered "+" (positive).
 */
void MainWindow::on_pb_arm_start_clicked() {
    // Get command vector from UI values
    const auto targets = GetActuatorTargets(ui_);

    if (debug_mode_) {
        std::stringstream command_ss;
        command_ss << std::fixed << std::setprecision(2)
                   << "Sending movement command (deg): ";

        for (int i = 0; i < Actuator::kUndefined; ++i) {
            const auto actuator = static_cast<Actuator::Name>(i);
            command_ss << Actuator::NameEnumToString(actuator) << "="
                       << targets[actuator];

            if (i < Actuator::kUndefined - 1) {
                command_ss << ", ";
            }
        }

        logger_->Debug(command_ss.str());
    }

    // Send command(s)
#if LIBRA_VERSION == 1
    emit CommandHebi(targets);
#elif LIBRA_VERSION == 2
    emit CommandEpos({targets[Actuator::kYaw]});
    emit CommandHebi({targets[Actuator::kPitch]});
#endif

    last_command_ = targets;
}

/**
 * @brief Toggles functionality related to automatic torque compensation.
 *        This includes automatic torque control of the central arm joint and,
 *        by association, automatic fluid system operation.
 *
 * @param checked Whether to enable automatic fluid system compensation
 *
 * @see on_pb_water_fill_A_clicked on_pb_water_drain_A_clicked
 *      on_pb_water_fill_B_clicked on_pb_water_drain_B_clicked
 */
void MainWindow::on_pb_atc_enable_toggled(bool checked) {
    logger_->Debug("ATC - " + std::string(checked ? "Enabling" : "Disabling")
                   + " automatic torque compensation");

    emit EnableAutoTorqueComp(checked);

    if (checked) {
        // Cancel any conflicting widget states
        ui_->pb_water_fill_A->setChecked(false);
        ui_->pb_water_drain_A->setChecked(false);
#if LIBRA_VERSION == 1
        ui_->pb_water_fill_B->setChecked(false);
        ui_->pb_water_drain_B->setChecked(false);
#endif

        // Clearly display an "enabled" state
        ui_->pb_atc_enable->setText(" DISABLE ATC");
        ui_->pb_atc_enable->setStyleSheet(
            QString("color: %1;").arg(Color::kRed));
    } else {
        // Revert to "disabled" state
        ui_->pb_atc_enable->setText(" ENABLE ATC");
        ui_->pb_atc_enable->setStyleSheet(
            QString("color: %1;").arg(Color::kGreen));
    }
}
