/******************************************************************************
 * @file   camera.cpp
 * @brief  Main app window camera group box implementation file.
 *
 * @author Christian Brice
 ******************************************************************************/

// Related Header
#include "main_window.h"

// C++ Standard Library Headers
//   (none)

// Other Library Headers
//   (none)

// Project Headers
#include "colors.h"
#include "ui_main_window.h"  // auto-generated by Qt

/* --- TABLE OF CONTENTS ---
 * !Selection
 * !Buttons
 */

constexpr int kInfoLifespan = 4000;  // 4s timer for non-hover status tips

//------------------------------------------------------------------------------
// !Selection
//------------------------------------------------------------------------------

/**
 * @brief Connects to the selected camera feed.
 *
 * @param sel Selected camera description
 *
 * @note The camera -description- is NOT what must be passed into CameraManager;
 *       that would be the camera -ID-, which is the OS-level device address.
 *       So `available_cameras_` must be used to "translate" the human-readable
 *       description into the device address.
 */
void MainWindow::on_cb_camera_name_currentTextChanged(const QString& sel) {
    // Remove any signals before destruction
    disconnect(this, &MainWindow::EnableDebugMode, camera_manager_.get(),
               &CameraManager::SetDebugMode);

    // Only allow one camera manager to exist at a time
    if (camera_manager_ != nullptr) {
        logger_->Debug("Resetting existing camera manager");
        camera_manager_.reset();

        // Reset flip button states
        ui_->pb_camera_flip_h->setEnabled(false);
        ui_->pb_camera_flip_h->setIcon(QIcon::fromTheme("go-next"));
        ui_->pb_camera_flip_h->setStyleSheet(
            QString("color: %1;").arg(Color::kGreen));

        ui_->pb_camera_flip_v->setEnabled(false);
        ui_->pb_camera_flip_v->setIcon(QIcon::fromTheme("go-down"));
        ui_->pb_camera_flip_v->setStyleSheet(
            QString("color: %1;").arg(Color::kGreen));
    }

    // Initialize camera and begin streaming
    camera_manager_ = std::make_unique<CameraManager>(available_cameras_[sel],
                                                      ui_->vw_camera_viewfinder,
                                                      this);
    connect(this, &MainWindow::EnableDebugMode,  // update debug mode
            camera_manager_.get(), &CameraManager::SetDebugMode);

    camera_manager_->Start();

    // Display misc. info and enable relevant widgets
    ui_->l_camera_id->setText(available_cameras_[sel]);
    ui_->pb_camera_capture->setEnabled(true);
    ui_->pb_camera_record->setEnabled(true);
    ui_->pb_camera_flip_h->setEnabled(true);  // TODO: only enable if RealSense
    ui_->pb_camera_flip_v->setEnabled(true);  // TODO: only enable if RealSense
}

//------------------------------------------------------------------------------
// !Buttons
//------------------------------------------------------------------------------

/**
 * @brief Captures a still image from the active camera feed.
 */
void MainWindow::on_pb_camera_capture_clicked() {
    camera_manager_->Capture();

    // Display a status tip at the bottom of the UI
    statusBar()->showMessage("Saving capture to img/ directory...",
                             kInfoLifespan);
}

/**
 * @brief Toggles video recording from the active camera feed.
 */
void MainWindow::on_pb_camera_record_clicked() {
    if (camera_manager_->Record()) {
        // Clearly display a "recording" state
        ui_->pb_camera_record->setIcon(QIcon::fromTheme("media-playback-stop"));
        ui_->pb_camera_record->setText(" STOP");
        ui_->pb_camera_record->setStyleSheet(
            QString("color: %1;").arg(Color::kRed));
    } else {
        // Display a status tip at the bottom of the UI
        statusBar()->showMessage("Saving recording to vid/ directory...",
                                 kInfoLifespan);

        // Revert to original state
        ui_->pb_camera_record->setIcon(QIcon::fromTheme("media-record"));
        ui_->pb_camera_record->setText(" RECORD");
        ui_->pb_camera_record->setStyleSheet(
            QString("color: %1;").arg(Color::kGreen));
    }
}

/**
 * @brief Toggles horizontal flipping of the camera feed.
 */
void MainWindow::on_pb_camera_flip_h_clicked() {
    if (camera_manager_ == nullptr) {
        return;
    }

    bool current_state = camera_manager_->IsHorizontalFlipped();
    camera_manager_->FlipHorizontal(!current_state);

    if (!current_state) {
        // Clearly display a "flipped" state
        ui_->pb_camera_flip_h->setIcon(QIcon::fromTheme("go-previous"));
        ui_->pb_camera_flip_h->setStyleSheet(
            QString("color: %1;").arg(Color::kRed));
    } else {
        // Revert to original state
        ui_->pb_camera_flip_h->setIcon(QIcon::fromTheme("go-next"));
        ui_->pb_camera_flip_h->setStyleSheet(
            QString("color: %1;").arg(Color::kGreen));
    }
}

/**
 * @brief Toggles vertical flipping of the camera feed.
 */
void MainWindow::on_pb_camera_flip_v_clicked() {
    if (camera_manager_ == nullptr) {
        return;
    }

    bool current_state = camera_manager_->IsVerticalFlipped();
    camera_manager_->FlipVertical(!current_state);

    if (!current_state) {
        // Clearly display a "flipped" state
        ui_->pb_camera_flip_v->setIcon(QIcon::fromTheme("go-up"));
        ui_->pb_camera_flip_v->setStyleSheet(
            QString("color: %1;").arg(Color::kRed));
    } else {
        // Revert to original state
        ui_->pb_camera_flip_v->setIcon(QIcon::fromTheme("go-down"));
        ui_->pb_camera_flip_v->setStyleSheet(
            QString("color: %1;").arg(Color::kGreen));
    }
}
