/******************************************************************************
 * @file   main_window.cpp
 * @brief  Main app window implementation file.
 *
 * @author brice.c.aa
 ******************************************************************************/

// Related Header
#include "main_window.h"

// C++ Standard Library Headers
//   (none)

// Other Library Headers
#include <QMessageBox>                  // Qt::Widgets
#include <QRegularExpressionValidator>  // Qt::Gui

// Project Headers
#include "qt_logger.h"
#include "ui_main_window.h"  // auto-generated by Qt
#include "util.h"

/* --- TABLE OF CONTENTS ---
 * !Local Helpers
 * !Class Management
 * !Class Helpers
 * !Thread Handlers (Slots)
 * !Uncategorized
 */

constexpr int kPrecision = 1;  // i.e., "0.1"

//------------------------------------------------------------------------------
// !Local Helpers
//------------------------------------------------------------------------------

namespace {

/**
 * @brief Fully deletes a widget or layout from the user interface.
 *
 * @tparam T Any visual QObject type
 * @param widget The widget or layout to be removed
 */
template<typename T>
void RemoveUiElement(T*& element) {
    if (!element) {
        return;
    }

    // To avoid duplicating code, define this lambda capable of handling both
    // QWidgets and QLayouts (since they boil down to different QObjects)
    auto RemoveFromParentLayout = [](QObject* obj) {
        if (!obj) {
            return;
        }

        // All objects are eventually children of a QWidget, so this is allowed
        if (auto* p = qobject_cast<QWidget*>(obj->parent())) {
            if (auto* pl = p->layout()) {
                // We must explicitly cast since indexOf() does not take QObjects
                if (auto* w = qobject_cast<QWidget*>(obj)) {
                    if (int i = pl->indexOf(w); i >= 0) {
                        delete pl->takeAt(i);
                    }
                } else if (auto* l = qobject_cast<QLayout*>(obj)) {
                    if (int i = pl->indexOf(l); i >= 0) {
                        delete pl->takeAt(i);
                    }
                }
            }
        }
    };

    RemoveFromParentLayout(element);

    // Handle layouts
    if constexpr (std::is_base_of_v<QLayout, T>) {
        // Recursively delete all children
        while (QLayoutItem* item = element->takeAt(0)) {
            if (auto* w = item->widget()) {
                RemoveUiElement(w);
            } else if (auto* l = item->layout()) {
                RemoveUiElement(l);
            }
            delete item;
        }
    }

    // Mark for deletion to reclaim visual space
    element->deleteLater();
    element = nullptr;
}

}  // namespace

//------------------------------------------------------------------------------
// !Class Management
//------------------------------------------------------------------------------

/**
 * @brief Standard constructor.
 *
 * @param parent Owning Qt widget
 */
MainWindow::MainWindow(QWidget* parent)
    : QMainWindow(parent), ui_(new Ui::MainWindow) {
    ui_->setupUi(this);
    this->setMinimumSize(this->minimumSizeHint());  // enforce minimum size

    logger_ = std::make_unique<QtLogger>("main_window", debug_mode_);

    // Runtime checks
    util::IsWslEnvironment();  // only warns, no action needed

    // GUI configuration
    ConfigureUi();
    InitializeFeedbackElementMap();
    InitializeDeviceManagers();
    InitializeThreads();

    // Component auto-connect
    auto reply = QMessageBox::question(nullptr, "LIBRA App Startup",
                                       "Automatically connect all components?",
                                       QMessageBox::Yes | QMessageBox::No);
    if (reply == QMessageBox::Yes) {
        ui_->a_connect_all->trigger();
    } else {
        // Even if auto-connect was refused, some UI elements should be populated
        ui_->a_refresh_camera_list->trigger();
    }
}

/**
 * @brief Standard destructor.
 */
MainWindow::~MainWindow() {
    // Define a lambda for gracefully wrapping up worker thread(s)
    auto StopThread = [](QThread* thread) {
        if (thread != nullptr && thread->isRunning()) {
            thread->disconnect();           // kill any further communication
            thread->requestInterruption();  // signal thread to stop looping
            thread->wait();                 // wait for thread cleanup to finish
        }
    };

    // Cleanup
    StopThread(hebi_thread_);
#if LIBRA_VERSION == 2
    StopThread(epos_thread_);
#endif

    delete ui_;
}

//------------------------------------------------------------------------------
// !Class Helpers
//------------------------------------------------------------------------------

/**
 * @brief Based on LIBRA version, disables unneeded widgets and connects those
 *        with complementary functions.
 *
 * @note Only used in constructor - placed in own function to improve readability.
 */
void MainWindow::ConfigureUi() {
    ui_->a_debug_mode->setChecked(debug_mode_);

    // Display build configuration: LIBRA_VERSION
    {
        QString ver_text = "<span>";
#ifdef LIBRA_VERSION
        ver_text += QString("<b>%1</b>").arg(LIBRA_VERSION);
#else
        ver_text += "<b>Unsupported</b>";
#endif
        ver_text += "</span>";
        ui_->l_libraversion_val->setText(ver_text);
    }

    // Display build configuration: BUILD_WITH_ROS2
    {
        QString ros2en_text = "<span>";
#ifdef BUILD_WITH_ROS2
        ros2en_text += "<b style='color: green;'>ON</b>";
#else
        ros2en_text += "<b style='color: red;'>OFF</b>";
#endif
        ros2en_text += "</span>";
        ui_->l_ros2enabled_val->setText(ros2en_text);
    }

    // ========== Menu Bar ==========

    // Unneeded menus/actions
#if LIBRA_VERSION != 1
    ui_->m_serial_servo->setEnabled(false);
#elif LIBRA_VERSION != 2
    ui_->m_epos->setEnabled(false);
#endif

    // Slots
    //   (none)

    // ========== Arm ==========

    // Unneeded widgets
#if LIBRA_VERSION != 1
    RemoveUiElement(ui_->gl_roll_input);
    RemoveUiElement(ui_->gl_roll_output);

    RemoveUiElement(ui_->gl_j1_input);
    RemoveUiElement(ui_->gl_j1_output);

    RemoveUiElement(ui_->gl_j2_input);
    RemoveUiElement(ui_->gl_j2_output);

    RemoveUiElement(ui_->gl_j3_input);
    RemoveUiElement(ui_->gl_j3_output);
#elif LIBRA_VERSION != 2
    RemoveUiElement(ui_->gl_yaw_input);
    RemoveUiElement(ui_->gl_yaw_output);

    RemoveUiElement(ui_->l_epos_status);
#endif

    // Slots
    connect(ui_->hs_arm_pitch, &QAbstractSlider::sliderMoved,  // when moved,
            ui_->sb_arm_pitch, &QDoubleSpinBox::setValue);     // update display
    connect(ui_->sb_arm_pitch, &QDoubleSpinBox::valueChanged,  // when changed,
            ui_->hs_arm_pitch, &QAbstractSlider::setValue);    // update slider

#if LIBRA_VERSION == 1
    connect(ui_->hs_arm_roll, &QAbstractSlider::sliderMoved,  // "
            ui_->sb_arm_roll, &QDoubleSpinBox::setValue);
    connect(ui_->sb_arm_roll, &QDoubleSpinBox::valueChanged,  // "
            ui_->hs_arm_roll, &QAbstractSlider::setValue);

    connect(ui_->hs_arm_j1, &QAbstractSlider::sliderMoved,  // "
            ui_->sb_arm_j1, &QDoubleSpinBox::setValue);
    connect(ui_->sb_arm_j1, &QDoubleSpinBox::valueChanged,  // "
            ui_->hs_arm_j1, &QAbstractSlider::setValue);

    connect(ui_->hs_arm_j2, &QAbstractSlider::sliderMoved,  // "
            ui_->sb_arm_j2, &QDoubleSpinBox::setValue);
    connect(ui_->sb_arm_j2, &QDoubleSpinBox::valueChanged,  // "
            ui_->hs_arm_j2, &QAbstractSlider::setValue);

    connect(ui_->hs_arm_j3, &QAbstractSlider::sliderMoved,  // "
            ui_->sb_arm_j3, &QDoubleSpinBox::setValue);
    connect(ui_->sb_arm_j3, &QDoubleSpinBox::valueChanged,  // "
            ui_->hs_arm_j3, &QAbstractSlider::setValue);
#elif LIBRA_VERSION == 2
    connect(ui_->hs_arm_yaw, &QAbstractSlider::sliderMoved,  // "
            ui_->sb_arm_yaw, &QDoubleSpinBox::setValue);
    connect(ui_->sb_arm_yaw, &QDoubleSpinBox::valueChanged,  // "
            ui_->hs_arm_yaw, &QAbstractSlider::setValue);
#endif

    // Store original limits for override functionality
    original_limits_.pitch_min = ui_->sb_arm_pitch->minimum();
    original_limits_.pitch_max = ui_->sb_arm_pitch->maximum();

#if LIBRA_VERSION == 1
    original_limits_.roll_min = ui_->sb_arm_roll->minimum();
    original_limits_.roll_max = ui_->sb_arm_roll->maximum();

    original_limits_.j1_min = ui_->sb_arm_j1->minimum();
    original_limits_.j1_max = ui_->sb_arm_j1->maximum();

    original_limits_.j2_min = ui_->sb_arm_j2->minimum();
    original_limits_.j2_max = ui_->sb_arm_j2->maximum();

    original_limits_.j3_min = ui_->sb_arm_j3->minimum();
    original_limits_.j3_max = ui_->sb_arm_j3->maximum();
#elif LIBRA_VERSION == 2
    original_limits_.yaw_min = ui_->sb_arm_yaw->minimum();
    original_limits_.yaw_max = ui_->sb_arm_yaw->maximum();
#endif

    // Set up validation for the "Quick Input" Line Edit
    {
        // Explanation of the regex:
        // - "^-?": optional minus sign
        // - "\d{1,3}": 1–3 digit number
        // - "(,-?\d{1,3}){0,4}": up to 4 more integers, each preceded by a comma
        QRegularExpression regex("(^-?\\d{1,3}(,-?\\d{1,3}){0,4}$)");
        QRegularExpressionValidator* validator =
            new QRegularExpressionValidator(regex, this);
        ui_->le_quick_input->setValidator(validator);
    }

    // ========== Water ==========

    // Unneeded widgets
#if LIBRA_VERSION != 1
    RemoveUiElement(ui_->vl_counterweight_B);
    RemoveUiElement(ui_->pb_water_fill_B);
    RemoveUiElement(ui_->pb_water_drain_B);
#endif

    // Slots
    //   (none)

    // ========== Manipulator ==========

    // Unneeded widgets
#if LIBRA_VERSION != 1
    RemoveUiElement(ui_->gb_manipulator);
#endif

    // Slots
#if LIBRA_VERSION == 1
    //   (none)
#endif

    // ========== Camera ==========

    connect(ui_->pb_camera_refresh, &QPushButton::clicked,     // when clicked,
            ui_->a_refresh_camera_list, &QAction::triggered);  // refresh list
}

/**
 * @brief Populates a map-of-maps with UI label elements, according to their
 *        corresponding joint names (`Joint`) and feedback types
 *        (`Actuator::Feedback`).
 *
 * @note Only used in constructor - placed in own function to improve readability.
 *
 * @see Joint::Name Actuator::Feedback HandleActuatorFeedback
 */
void MainWindow::InitializeFeedbackElementMap() {
    // Central joint
#if LIBRA_VERSION == 1
    feedback_element_map_[Joint::Name::kRoll][Actuator::Feedback::kTargetPos] =
        ui_->l_target_roll;
    feedback_element_map_[Joint::Name::kRoll][Actuator::Feedback::kActualPos] =
        ui_->l_actual_roll;
    feedback_element_map_[Joint::Name::kRoll][Actuator::Feedback::kActualTorque] =
        ui_->l_torque_roll;
#elif LIBRA_VERSION == 2
    feedback_element_map_[Joint::Name::kYaw][Actuator::Feedback::kTargetPos] =
        ui_->l_target_yaw;
    feedback_element_map_[Joint::Name::kYaw][Actuator::Feedback::kActualPos] =
        ui_->l_actual_yaw;
    feedback_element_map_[Joint::Name::kYaw][Actuator::Feedback::kActualTorque] =
        ui_->l_torque_yaw;
#endif

    feedback_element_map_[Joint::Name::kPitch][Actuator::Feedback::kTargetPos] =
        ui_->l_target_pitch;
    feedback_element_map_[Joint::Name::kPitch][Actuator::Feedback::kActualPos] =
        ui_->l_actual_pitch;
    feedback_element_map_[Joint::Name::kPitch][Actuator::Feedback::kActualTorque] =
        ui_->l_torque_pitch;

    // Arm
#if LIBRA_VERSION == 1
    feedback_element_map_[Joint::Name::kJ1][Actuator::Feedback::kTargetPos] =
        ui_->l_target_j1;
    feedback_element_map_[Joint::Name::kJ1][Actuator::Feedback::kActualPos] =
        ui_->l_actual_j1;
    feedback_element_map_[Joint::Name::kJ1][Actuator::Feedback::kActualTorque] =
        ui_->l_torque_j1;

    feedback_element_map_[Joint::Name::kJ2][Actuator::Feedback::kTargetPos] =
        ui_->l_target_j2;
    feedback_element_map_[Joint::Name::kJ2][Actuator::Feedback::kActualPos] =
        ui_->l_actual_j2;
    feedback_element_map_[Joint::Name::kJ2][Actuator::Feedback::kActualTorque] =
        ui_->l_torque_j2;

    feedback_element_map_[Joint::Name::kJ3][Actuator::Feedback::kTargetPos] =
        ui_->l_target_j3;
    feedback_element_map_[Joint::Name::kJ3][Actuator::Feedback::kActualPos] =
        ui_->l_actual_j3;
    feedback_element_map_[Joint::Name::kJ3][Actuator::Feedback::kActualTorque] =
        ui_->l_torque_j3;
#endif
}

/**
 * @brief Sets up child objects.
 *
 * @note Only used in constructor - placed in own function to improve readability.
 */
void MainWindow::InitializeDeviceManagers() {
    // ========== Arduino Manager ==========

    // NOTE: Since ArduinoManager is QTimer-driven and asynchronous, we set up
    //       signal/slot connections much like we do with QThreads. This is not
    //       necessary with CameraManager, which is different by nature.

    arduino_manager_ = new ArduinoManager(this, debug_mode_);

    // MainWindow signals
    connect(this, &MainWindow::EnableDebugMode,  // update debug mode
            arduino_manager_, &ArduinoManager::SetDebugMode);

    connect(this, &MainWindow::ConnectWater,  // connect water
            arduino_manager_, &ArduinoManager::ConnectWater);
    connect(ui_->a_water_disconnect, &QAction::triggered,  // disconnect water
            arduino_manager_, &ArduinoManager::DisconnectWater);
    connect(this, &MainWindow::EnableAutoTorqueComp,  // automate water state
            arduino_manager_, &ArduinoManager::SetAutoCompensation);
    connect(this, &MainWindow::CommandWater,  // force update water command
            arduino_manager_, &ArduinoManager::ForceWaterCommand);

#if LIBRA_VERSION == 1
    connect(this, &MainWindow::ConnectManip,  // connect servos
            arduino_manager_, &ArduinoManager::ConnectManip);
    connect(ui_->a_manip_disconnect, &QAction::triggered,  // disconnect servos
            arduino_manager_, &ArduinoManager::DisconnectManip);
    connect(ui_->a_manip_enable_auto_correction, &QAction::toggled,  // leveling
            arduino_manager_, &ArduinoManager::SetManipCorrectionEnabled);
    connect(this, &MainWindow::CommandManip,  // update manip targets
            arduino_manager_, &ArduinoManager::SetManipTarget);
#endif

    // TankWidget signals
    connect(ui_->tw_water_level_A, &TankWidget::TankFull,  // stop if full
            this, [this]() {
                logger_->Info("Tank A estimated full; disabling ATC");
                ui_->pb_autocomp_enable->setChecked(false);
            });

    connect(ui_->tw_water_level_A, &TankWidget::TankEmpty,  // stop if empty
            this, [this]() {
                logger_->Info("Tank A estimated empty; disabling ATC");
                ui_->pb_autocomp_enable->setChecked(false);
            });

#if LIBRA_VERSION == 1
    connect(ui_->tw_water_level_B, &TankWidget::TankFull,  // stop if full
            this, [this]() {
                logger_->Info("Tank B estimated full; disabling ATC");
                ui_->pb_autocomp_enable->setChecked(false);
            });

    connect(ui_->tw_water_level_B, &TankWidget::TankEmpty,  // stop if empty
            this, [this]() {
                logger_->Info("Tank B estimated empty; disabling ATC");
                ui_->pb_autocomp_enable->setChecked(false);
            });
#endif

    // MainWindow slots
    connect(arduino_manager_, &ArduinoManager::ErrorThrown,  // handle errors
            this, &MainWindow::HandleCriticalError);

    connect(arduino_manager_, &ArduinoManager::WaterConnected,  // update UI
            this, &MainWindow::HandleWaterConnChanged);
    connect(arduino_manager_, &ArduinoManager::ReportWaterStatus,  // get state
            this, &MainWindow::HandleWaterStatus);

#if LIBRA_VERSION == 1
    connect(arduino_manager_, &ArduinoManager::ManipConnected,  // update UI
            this, &MainWindow::HandleManipConnChanged);
    connect(arduino_manager_, &ArduinoManager::ReportPosition,  // get position
            this, &MainWindow::HandleManipPosition);
#endif

    // ========== Camera Manager ==========

    // TODO: auto-display first connected device?
}

/**
 * @brief Sets up signal and slot connections to child threads and spins them up.
 *
 * @note In Qt, thread management for subclassed QThreads generally has 4 steps:
 *   1) Initialize a new QThread object as a child of MainWindow.
 *   2) Register its signals and slots to send/receive data to/from MainWindow.
 *   3) Register its exit signal to its own destruction slot.
 *   4) Spin it off.
 * If the thread loops continuously, there is a fifth step:
 *   5) In the MainWindow destructor, interrupt or forcibly stop the QThread.
 *
 * @note Only used in constructor - placed in own function to improve readability.
 */
void MainWindow::InitializeThreads() {
    // ========== HEBI Thread ==========

    // NOTE: This constructor automatically determines the actuator family and
    //       names based on the LIBRA_VERSION the app is built with
    hebi_thread_ = new HebiThread(this, debug_mode_);

    // MainWindow signals
    connect(this, &MainWindow::EnableDebugMode,  // update debug mode
            hebi_thread_, &HebiThread::SetDebugMode);

    connect(ui_->a_hebi_connect, &QAction::triggered,  // connect to HEBI
            hebi_thread_, &HebiThread::Connect);
    connect(ui_->a_hebi_disconnect, &QAction::triggered,  // disconnect HEBI
            hebi_thread_, &HebiThread::Disconnect);

    connect(this, &MainWindow::CommandHebi,  // update HEBI target(s)
            hebi_thread_, &HebiThread::SetTarget);
    connect(ui_->pb_arm_stop, &QPushButton::clicked,  // stop ALL actuators
            hebi_thread_, &HebiThread::Stop);

    connect(this, &MainWindow::LoadHebiGains,  // load new gains
            hebi_thread_, &HebiThread::LoadGains);
    connect(ui_->a_hebi_log_start, &QAction::triggered,  // start new hebilog
            hebi_thread_, &HebiThread::StartHebiLog);
    connect(ui_->a_hebi_log_stop, &QAction::triggered,  // stop current hebilog
            hebi_thread_, &HebiThread::StopHebiLog);

    connect(this, &MainWindow::EnableAutoTorqueComp,  // auto-balancing
            hebi_thread_, &HebiThread::EnableTorqueControl);
    connect(this, &MainWindow::UpdateHebiTorqueCompBounds,  // update limits
            hebi_thread_, &HebiThread::SetTorqueCompBounds);
    connect(ui_->a_hebi_model_based_comp, &QAction::toggled,  // HRDF-based comp
            hebi_thread_, &HebiThread::EnableModelBasedComp);

    // MainWindow slots
    connect(hebi_thread_, &HebiThread::ErrorThrown,  // handle errors
            this, &MainWindow::HandleCriticalError);

    connect(hebi_thread_, &HebiThread::Connected,  // update UI
            this, &MainWindow::HandleHebiConnChanged);
    connect(hebi_thread_, &HebiThread::ReportFeedback,  // get feedback
            this, &MainWindow::HandleActuatorFeedback);
    connect(hebi_thread_, &HebiThread::ReportStatus,  // get minor statuses
            this, &MainWindow::HandleActuatorStatus);

    // ArduinoManager slots
    connect(hebi_thread_, &HebiThread::ReportArmTorque,  // update water command
            arduino_manager_, &ArduinoManager::UpdateWaterControl);
#if LIBRA_VERSION == 1
    connect(hebi_thread_, &HebiThread::InformPitch,  // update manip correction
            arduino_manager_, &ArduinoManager::SetManipCorrection);
#endif

    // Thread cleanup
    connect(hebi_thread_, &HebiThread::finished,      // when thread exits,
            hebi_thread_, &HebiThread::deleteLater);  // deallocate

    hebi_thread_->start();

    // ========== EPOS Thread ==========

#if LIBRA_VERSION == 2
    epos_thread_ = new EposThread(this, debug_mode_);

    // MainWindow signals
    connect(this, &MainWindow::EnableDebugMode,  // update debug mode
            epos_thread_, &EposThread::SetDebugMode);

    connect(this, &MainWindow::ConnectEpos,  // connect to EPOS
            epos_thread_, &EposThread::Connect);
    connect(ui_->a_epos_disconnect, &QAction::triggered,  // disconnect EPOS
            epos_thread_, &EposThread::Disconnect);

    connect(this, &MainWindow::CommandEpos,  // update EPOS target(s)
            epos_thread_, &EposThread::SetTarget);
    connect(ui_->pb_arm_stop, &QPushButton::clicked,  // stop ALL actuators
            epos_thread_, &EposThread::Stop);

    // MainWindow slots
    connect(epos_thread_, &EposThread::ErrorThrown,  // handle errors
            this, &MainWindow::HandleCriticalError);

    connect(epos_thread_, &EposThread::Connected,  // update UI
            this, &MainWindow::HandleEposConnChanged);
    connect(epos_thread_, &EposThread::ReportFeedback,  // get feedback
            this, &MainWindow::HandleActuatorFeedback);
    connect(epos_thread_, &EposThread::ReportStatus,  // get minor statuses
            this, &MainWindow::HandleActuatorStatus);

    // Thread cleanup
    connect(epos_thread_, &EposThread::finished,      // when thread exits,
            epos_thread_, &EposThread::deleteLater);  // deallocate

    epos_thread_->start();
#endif
}

/**
 * @brief Update UI according to connection status of all actuator types.
 */
void MainWindow::UpdateActuatorControls() {
    // Evaluate connection statuses of all actuators
    bool hebi_connected = ui_->a_hebi_disconnect->isEnabled();
    bool any_connected = hebi_connected;

#if LIBRA_VERSION == 2
    bool epos_connected = ui_->a_epos_disconnect->isEnabled();
    any_connected = hebi_connected || epos_connected;
#endif

    // Update UI
    ui_->pb_arm_start->setEnabled(any_connected);
    ui_->le_quick_input->setEnabled(any_connected);
    ui_->pb_quick_input->setEnabled(any_connected);
    ui_->pb_arm_stop->setEnabled(any_connected);
}

//------------------------------------------------------------------------------
// !Thread Handlers (Slots)
//------------------------------------------------------------------------------

#if LIBRA_VERSION == 1
/**
 * @brief Reflects SerialServo connection status in the UI.
 *
 * @note Currently does nothing, as the original manipulator was too weak and
 *       has been replaced with a static mount.
 */
void MainWindow::HandleManipConnChanged(const bool& connected) {
    // Menu bar
    ui_->a_manip_connect->setEnabled(!connected);
    ui_->a_manip_disconnect->setEnabled(connected);

    ui_->a_manip_enable_auto_correction->setEnabled(connected);

    // UI widgets
    ui_->pb_manip_slow->setEnabled(connected);
    ui_->pb_manip_fast->setEnabled(connected);
}

/**
 * @brief Sorts important actuator information into individual UI elements.
 *
 * @param base Position of the pitch-correction servo.
 * @param pan Position of the manipulator yaw servo.
 * @param tilt Position of the manipulator pitch servo.
 */
void MainWindow::HandleManipPosition(const double& base, const double& pan,
                                     const double& tilt) {
    ui_->l_actual_manip_base->setText(QString::number(base, 'f', 1));  // 0.1
    ui_->l_actual_manip_pan->setText(QString::number(pan, 'f', 1));
    ui_->l_actual_manip_tilt->setText(QString::number(tilt, 'f', 1));
}
#endif

/**
 * @brief Reflects SerialWater connection status in the UI.
 */
void MainWindow::HandleWaterConnChanged(const bool& connected) {
    // Menu bar
    ui_->a_water_connect->setEnabled(!connected);
    ui_->a_water_disconnect->setEnabled(connected);

    ui_->a_water_set_empty->setEnabled(connected);
    ui_->a_water_set_full->setEnabled(connected);

    // UI widgets
    ui_->pb_water_fill_A->setEnabled(connected);
    ui_->pb_water_drain_A->setEnabled(connected);
#if LIBRA_VERSION == 1
    ui_->pb_water_fill_B->setEnabled(connected);
    ui_->pb_water_drain_B->setEnabled(connected);
#endif

    if (connected || (!connected && ui_->a_hebi_connect->isEnabled())) {
        // Since auto torque compensation is shared between ActuatorThread and
        // ArduinoManager, disable this button if neither is connected
        ui_->pb_autocomp_enable->setEnabled(connected);
    }
}

/**
 * @brief Reflects fluid system status in the UI.
 *        - Primary visual feedback: formatted status string in "WATER" GroupBox
 *        - Secondary visual feedback: updates animation state of TankWidget(s)
 *
 * @param side The side of the fluid system
 * @param state The flow state of the fluid system
 */
void MainWindow::HandleWaterStatus(const Water::Side& side,
                                   const Water::State& state) {
    switch (side) {
        case Water::Side::kA:
            ui_->l_water_status_A->setText(Water::StateEnumToString(state));
            ui_->tw_water_level_A->UpdateState(state);
            break;
#if LIBRA_VERSION == 1
        case Water::Side::kB:
            ui_->l_water_status_B->setText(Water::StateEnumToString(state));
            ui_->tw_water_level_B->UpdateState(state);
            break;
#endif
        default:
            // Shouldn't be able to get here
            logger_->Error("Received status for unknown fluid system side: "
                           + SideEnumToString(side) + " ("
                           + std::to_string(static_cast<int>(side)) + ")");
    }
}

/**
 * @brief Reflects HEBI actuator connection status in the UI.
 */
void MainWindow::HandleHebiConnChanged(const bool& connected) {
    // Menu bar
    ui_->a_hebi_connect->setEnabled(!connected);
    ui_->a_hebi_disconnect->setEnabled(connected);

    ui_->a_hebi_load_gains->setEnabled(connected);
    ui_->a_hebi_log_start->setEnabled(connected);
    ui_->a_hebi_log_stop->setEnabled(connected);

    ui_->a_hebi_override_limits->setEnabled(connected);
    ui_->a_hebi_central_torque_comp->setEnabled(connected);
    ui_->a_hebi_model_based_comp->setEnabled(connected);

    // UI widgets
    UpdateActuatorControls();

    if (connected || (!connected && ui_->a_water_connect->isEnabled())) {
        // Since auto torque compensation is shared between ActuatorThread and
        // ArduinoManager, disable this button if neither is connected
        ui_->pb_autocomp_enable->setEnabled(connected);
    }
}

#if LIBRA_VERSION == 2
/**
 * @brief Reflects EPOS (Maxon) actuator connection status in the UI.
 */
void MainWindow::HandleEposConnChanged(const bool& connected) {
    // Menu bar
    ui_->a_epos_connect->setEnabled(!connected);
    ui_->a_epos_usedefaults->setEnabled(!connected);
    ui_->a_epos_disconnect->setEnabled(connected);

    // UI widgets
    UpdateActuatorControls();
}
#endif

/**
 * @brief Sorts important actuator information into individual UI elements.
 *
 * @param feedbacks Unordered map of joint(s) and their corresponding feedback
 * @param feedback_type The type of primary feedback provided
 *
 * @note To improve ease of use, LIBRA-I arm actuator angles (J1, J2, J3) in the
 *       UI are shown relative to a forward-facing perspective directly behind
 *       the robot, where "0" is directly forward, and counterclockwise movement
 *       is considered "+" (positive).
 */
void MainWindow::HandleActuatorFeedback(
    const std::unordered_map<Joint::Name, double>& feedbacks,
    const Actuator::Feedback feedback_type) {
    bool initialized = false;

    for (const auto& feedback : feedbacks) {
        const auto& joint = feedback.first;
        const auto& val = feedback.second;

        // Index into matching label using map-of-maps initialized in constructor
        try {
            feedback_element_map_.at(joint)
                .at(feedback_type)
                ->setText(QString::number(val, 'f', kPrecision));
        } catch (const std::out_of_range&) {
            logger_->Error(
                "No UI element mapped to joint " + Joint::NameEnumToString(joint)
                + " (" + std::to_string(static_cast<int>(joint))
                + ") and feedback type "
                + Actuator::FeedbackEnumToString(feedback_type) + " ("
                + std::to_string(static_cast<int>(feedback_type)) + ")");
        }

        // TODO: documentation
        if (!initialized) {
            // TODO: initialize SpinBoxes to first received value

            initialized = true;
        }
    }
}

/**
 * @brief Prints miscellaneous actuator information at the bottom of the UI.
 *
 * @param status Newline-delimited status info
 * @param type The actuator type, for updating the corresponding UI element
 */
void MainWindow::HandleActuatorStatus(const QString& status,
                                      const Actuator::Type type) {
    switch (type) {
        case Actuator::Type::kHebi:
            ui_->l_hebi_status->setText(status);
            break;
#if LIBRA_VERSION == 2
        case Actuator::Type::kEpos:
            ui_->l_epos_status->setText(status);
            break;
#endif
        default:
            // Shouldn't be able to get here
            logger_->Error("Received status from unknown actuator type: "
                           + TypeEnumToString(type) + " ("
                           + std::to_string(static_cast<int>(type)) + ")");
    }
}

/**
 * @brief Throws a pop-up error box upon receiving an error signal from a thread.
 *
 * @param err Fatal error message from a component
 */
void MainWindow::HandleCriticalError(const QString& err) {
    QMessageBox::critical(this, tr("Error"), err);
}

//------------------------------------------------------------------------------
// !Uncategorized
//------------------------------------------------------------------------------
