/******************************************************************************
 * @file   manipulator.cpp
 * @brief  Main app window manipulator group box implementation file.
 *
 * @author brice.c.aa
 ******************************************************************************/

// Related Header
#include "main_window.h"

// C++ Standard Library Headers
//   (none)

// Other Library Headers
//   (none)

// Project Headers
#include "ui_main_window.h"  // auto-generated by Qt

/* --- TABLE OF CONTENTS ---
 * !Buttons
 */

constexpr bool kManipMoveSlow = true;
constexpr bool kManipMoveFast = false;

//------------------------------------------------------------------------------
// !Buttons
//------------------------------------------------------------------------------

/**
 * @brief Moves manipulator servos #2 and #3 at a slow speed.
 *
 * @note Manipulator servo #1 is a compensating pitch joint that offsets J3's
 *       pitch; it is not directly commanded here.
 */
void MainWindow::on_pb_manip_slow_clicked() {
    emit CommandManip(ui_->sb_manip_pan->value(), ui_->sb_manip_tilt->value(),
                      kManipMoveSlow);
}

/**
 * @brief Moves manipulator servos #2 and #3 at maximum speed (near-instant).
 *
 * @note Manipulator servo #1 is a compensating pitch joint that offsets J3's
 *       pitch; it is not directly commanded here.
 */
void MainWindow::on_pb_manip_fast_clicked() {
    emit CommandManip(ui_->sb_manip_pan->value(), ui_->sb_manip_tilt->value(),
                      kManipMoveFast);
}
