/******************************************************************************
 * @file   menu_bar.cpp
 * @brief  Main app window menu bar implementation file.
 *
 * @author Christian Brice
 ******************************************************************************/

// Related Header
#include "main_window.h"

// C++ Standard Library Headers
//   (none)

// Other Library Headers
#include <QFileDialog>  // Qt::Widgets

// Project Headers
#if LIBRA_VERSION == 2
# include "open_epos_dialog.h"
#endif
#include "open_serial_dialog.h"
#include "torque_comp_dialog.h"
#include "ui_main_window.h"  // auto-generated by Qt
#include "util.h"

/* --- TABLE OF CONTENTS ---
 * !Preferences
 * !Automation
 * !Actuators
 * !Sensors
 * !Water
 * !Quick Actions
 */

//------------------------------------------------------------------------------
// !Preferences
//------------------------------------------------------------------------------

/**
 * @brief Event handler for "Preferences" menu action "Debug Mode".
 *        Toggles debug prinouts for this object and all its children.
 */
void MainWindow::on_a_debug_mode_toggled(bool checked) {
    debug_mode_ = checked;
    logger_->SetDebugMode(debug_mode_);

    if (debug_mode_) {
        // Always print this message when debug mode is enabled
        logger_->Info("Debug mode enabled");
    }

    // Propagate to all children
    emit EnableDebugMode(checked);
}

//------------------------------------------------------------------------------
// !Automation
//------------------------------------------------------------------------------

/**
 * @brief Event handler for "Automation/ATC" menu action "Torque compensation
 *        bounds...". Opens a dialog to configure torque compensation bounds.
 */
void MainWindow::on_a_atc_update_bounds_triggered() {
    if (hebi_thread_ == nullptr) {
        logger_->Warn("HEBI thread not available - cannot edit torque bounds");
        return;
    }

    // Prompt user to input new bounds
    TorqueCompDialog dialog(this, kTorqueCompLowerBound, kTorqueCompUpperBound);

    if (dialog.exec() == QDialog::Accepted) {
        const double lower_bound = dialog.GetLowerBound();
        const double upper_bound = dialog.GetUpperBound();

        // Send the new bounds to the HebiThread
        emit UpdateHebiTorqueCompBounds(lower_bound, upper_bound);
    } else {
        logger_->Debug("Torque bound setting cancelled by user");
        return;
    }
}

/**
 * @brief TODO: documentation.
 *
 */
void MainWindow::on_a_atc_ignore_water_level_triggered() {
    // TODO: implementation
}

//------------------------------------------------------------------------------
// !Actuators
//------------------------------------------------------------------------------

#if LIBRA_VERSION == 2
/**
 * @brief Event handler for "Actuators/EPOS" menu action "Connect".
 *        Opens a dialog allowing the user to select connection settings.
 */
void MainWindow::on_a_epos_connect_triggered() {
    // Native Linux should have no issues connecting with defaults
    if (!ui_->a_epos_usedefaults->isChecked() || util::IsWslEnvironment()) {
        // Prompt user to select an EPOS device
        OpenEposDialog dialog(this);

        if (dialog.exec() == QDialog::Accepted) {
            auto params = dialog.GetDeviceParams();

            if (!params.is_set) {
                logger_->Error("Parameter selection incomplete!");
                return;
            }

            if (util::IsWslEnvironment()) {
                // What the EPOS API retrieves as "USB#" on WSL is actually
                // "hidraw#", so we modify the port name here
                if (auto pos = params.port_name.find("USB");
                    pos != std::string::npos) {
                    params.port_name.replace(pos, 3, "/dev/hidraw");
                    logger_->Info("WSL detected - modified EPOS port name to "
                                  + params.port_name);
                }
            }

            // Send selected device params to EposThread
            epos_thread_->SetDeviceParams(params.device_name,
                                          params.protocol_name,
                                          params.interface_name,
                                          params.port_name, params.baud_rate);
        } else {
            logger_->Debug("Parameter selection cancelled by user");
            return;
        }
    }

    emit ConnectEpos();
}
#endif

/**
 * @brief Event handler for "Actuators/HEBI" menu action "Load new gains...".
 *        Opens a file dialog to select and load a new gains file.
 */
void MainWindow::on_a_hebi_load_gains_triggered() {
    if (hebi_thread_ == nullptr) {
        logger_->Warn("HEBI thread not available - cannot load gains");
        return;
    }

    QString file_path = QFileDialog::getOpenFileName(this,
                                                     "Select HEBI Gains File",
                                                     "./bin/shared/hebi/",
                                                     "XML Files (*.xml)");

    if (file_path.isEmpty()) {
        logger_->Debug("Gains file selection cancelled by user");
        return;
    }

    emit LoadHebiGains(file_path);
}

/**
 * @brief Event handler for "Actuators/HEBI" menu action "Override pos. limits".
 *        Toggles input SpinBox and Slider limits.
 */
void MainWindow::on_a_hebi_override_limits_toggled(bool checked) {
    if (checked) {
        logger_->Debug("Overriding HEBI position limits");

        // Set override limits (full circle in either direction)
        // NOLINTBEGIN(readability-magic-numbers)
        ui_->hs_arm_pitch->setRange(-360, 360);
        ui_->sb_arm_pitch->setRange(-360.0, 360.0);

#if LIBRA_VERSION == 1
        ui_->hs_arm_roll->setRange(-360, 360);
        ui_->sb_arm_roll->setRange(-360.0, 360.0);

        ui_->hs_arm_j1->setRange(-360, 360);
        ui_->sb_arm_j1->setRange(-360.0, 360.0);

        ui_->hs_arm_j2->setRange(-360, 360);
        ui_->sb_arm_j2->setRange(-360.0, 360.0);

        ui_->hs_arm_j3->setRange(-360, 360);
        ui_->sb_arm_j3->setRange(-360.0, 360.0);
#elif LIBRA_VERSION == 2
        ui_->hs_arm_yaw->setRange(-360, 360);
        ui_->sb_arm_yaw->setRange(-360.0, 360.0);
#endif
        // NOLINTEND(readability-magic-numbers)
    } else {
        logger_->Debug("Restoring HEBI position limits");

        // Restore original limits
        ui_->hs_arm_pitch->setRange(original_limits_.pitch_min,
                                    original_limits_.pitch_max);
        ui_->sb_arm_pitch->setRange(original_limits_.pitch_min,
                                    original_limits_.pitch_max);

#if LIBRA_VERSION == 1
        ui_->hs_arm_roll->setRange(original_limits_.roll_min,
                                   original_limits_.roll_max);
        ui_->sb_arm_roll->setRange(original_limits_.roll_min,
                                   original_limits_.roll_max);

        ui_->hs_arm_j1->setRange(original_limits_.j1_min,
                                 original_limits_.j1_max);
        ui_->sb_arm_j1->setRange(original_limits_.j1_min,
                                 original_limits_.j1_max);

        ui_->hs_arm_j2->setRange(original_limits_.j2_min,
                                 original_limits_.j2_max);
        ui_->sb_arm_j2->setRange(original_limits_.j2_min,
                                 original_limits_.j2_max);

        ui_->hs_arm_j3->setRange(original_limits_.j3_min,
                                 original_limits_.j3_max);
        ui_->sb_arm_j3->setRange(original_limits_.j3_min,
                                 original_limits_.j3_max);
#elif LIBRA_VERSION == 2
        ui_->hs_arm_yaw->setRange(original_limits_.yaw_min,
                                  original_limits_.yaw_max);
        ui_->sb_arm_yaw->setRange(original_limits_.yaw_min,
                                  original_limits_.yaw_max);
#endif
    }
}

#if LIBRA_VERSION == 1
/**
 * @brief Event handler for "Actuator/Manip. Servos" menu action "Connect".
 *        Allows user to select a physical serial device to connect to.
 *
 * @note Currently does nothing, as the original manipulator was too weak and
 *       has been replaced with a static mount.
 */
void MainWindow::on_a_manip_connect_triggered() {
    // Prompt user to select a serial device
    OpenSerialDialog dialog(this, QString("SerialServo"),
                            QString("Seeed XIAO M0"));
    QString port_name;

    if (dialog.exec() == QDialog::Accepted) {
        port_name = dialog.GetSelectedPortName();

        if (port_name.isEmpty()) {
            logger_->Error("No port selected!");
            return;
        }
    } else {
        logger_->Debug("Port selection cancelled by user");
        return;
    }

    emit ConnectManip(port_name);
}
#endif

//------------------------------------------------------------------------------
// !Sensors
//------------------------------------------------------------------------------

/**
 * @brief Event handler for "Sensors/Camera" menu action "Refresh Camera List".
 *        Populates the "Camera" tab's ComboBox with all detected cameras.
 */
void MainWindow::on_a_refresh_camera_list_triggered() {
    logger_->Debug("Checking available video inputs...");

    ui_->cb_camera_name->clear();  // existing list may be stale

    const auto cameras = QMediaDevices::videoInputs();
    for (const auto& camera : cameras) {
        auto desc = camera.description();
        ui_->cb_camera_name->addItem(desc);  // populate ComboBox
        available_cameras_[desc] = QString(camera.id());
    }

    // NOTE: The "CAPTURE", "RECORD", and "FLIP" buttons are only enabled when
    //       a camera is selected (see on_cb_camera_name_currentTextChanged)
    if (available_cameras_.empty()) {
        ui_->pb_camera_capture->setEnabled(false);
        ui_->pb_camera_record->setEnabled(false);
        ui_->pb_camera_flip_h->setEnabled(false);
        ui_->pb_camera_flip_v->setEnabled(false);

        logger_->Info("No cameras found");
    } else {
        logger_->Debug("Found " + std::to_string(available_cameras_.size())
                       + " cameras");
    }
}

//------------------------------------------------------------------------------
// !Water
//------------------------------------------------------------------------------

/**
 * @brief Event handler for "Water" menu action "Connect".
 *        Allows user to select a physical serial device to connect to.
 */
void MainWindow::on_a_water_connect_triggered() {
    // Prompt user to select a serial device
    OpenSerialDialog dialog(this, QString("SerialWater"),
                            QString("Arduino Nano Every"));
    QString port_name;

    if (dialog.exec() == QDialog::Accepted) {
        port_name = dialog.GetSelectedPortName();

        if (port_name.isEmpty()) {
            logger_->Error("No port selected!");
            return;
        }
    } else {
        logger_->Debug("Port selection cancelled by user");
        return;
    }

    emit ConnectWater(port_name);
}

/**
 * @brief Event handler for "Water/Advanced" menu action "Set empty (0%)".
 *        Forces the tank (water bladder) visualization to show as empty.
 *
 * @note Only use if there is a discrepancy with the physical water bladders.
 */
void MainWindow::on_a_water_set_empty_triggered() {
    ui_->tw_water_level_A->OverrideLevel(0.0);
#if LIBRA_VERSION == 1
    ui_->tw_water_level_B->OverrideLevel(0.0);
#endif
}

/**
 * @brief Event handler for "Water/Advanced" menu action "Set full (100%)".
 *        Forces the tank (water bladder) visualization to show as full.
 *
 * @note Only use if there is a discrepancy with the physical water bladders.
 */
void MainWindow::on_a_water_set_full_triggered() {
    ui_->tw_water_level_A->OverrideLevel(1.0);
#if LIBRA_VERSION == 1
    ui_->tw_water_level_B->OverrideLevel(1.0);
#endif
}

//------------------------------------------------------------------------------
// !Quick Actions
//------------------------------------------------------------------------------

/**
 * @brief Event handler for "Quick Actions" menu action "Connect All".
 *        Connects all peripheral devices (actuators, sensors, etc.).
 */
void MainWindow::on_a_connect_all_triggered() {
    // Arduinos
    ui_->a_water_connect->trigger();
#if LIBRA_VERSION == 1
    ui_->a_manip_connect->trigger();
#endif

    // Actuators
    ui_->a_hebi_connect->trigger();
#if LIBRA_VERSION == 2
    ui_->a_epos_connect->trigger();
#endif

    // Sensors
    ui_->a_refresh_camera_list->trigger();
    ui_->a_lidar_connect->trigger();
}

/**
 * @brief Event handler for "Quick Actions" menu action "Disconnect All".
 *        Disconnects all peripheral devices (actuators, sensors, etc.).
 */
void MainWindow::on_a_disconnect_all_triggered() {
    // Arduinos
#if LIBRA_VERSION == 1
    ui_->a_manip_disconnect->trigger();
#endif
    ui_->a_water_disconnect->trigger();

    // Actuators
    ui_->a_hebi_disconnect->trigger();
#if LIBRA_VERSION == 2
    ui_->a_epos_disconnect->trigger();
#endif

    // Sensors
    ui_->a_lidar_disconnect->trigger();
}
