/******************************************************************************
 * @file   water.cpp
 * @brief  Main app window water group box implementation file.
 *
 * @author brice.c.aa
 ******************************************************************************/

// Related Header
#include "main_window.h"

// C++ Standard Library Headers
//   (none)

// Other Library Headers
//   (none)

// Project Headers
#include "ui_main_window.h"  // auto-generated by Qt

/* --- TABLE OF CONTENTS ---
 * !Buttons
 */

//------------------------------------------------------------------------------
// !Buttons
//------------------------------------------------------------------------------

/**
 * @brief Toggles force-filling of counterweight #1. Implicitly disables
 *        automatic torque compensation.
 *
 * @param checked Whether to force-fill the counterweight
 *
 * @see on_pb_atc_enable_toggled
 */
void MainWindow::on_pb_water_fill_A_clicked(bool checked) {
    if (checked) {
        // Cancel any conflicting widget states
        ui_->pb_atc_enable->setChecked(false);
        ui_->pb_water_drain_A->setChecked(false);

        // Send signal
        emit CommandWater(Water::Side::kA, Water::State::kFilling);
    } else {
        // Return to stable state
        emit CommandWater(Water::Side::kA, Water::State::kStopped);
    }
}

/**
 * @brief Toggles force-draining of counterweight #1. Implicitly disables
 *        automatic torque compensation.
 *
 * @param checked Whether to force-drain the counterweight
 *
 * @see on_pb_atc_enable_toggled
 */
void MainWindow::on_pb_water_drain_A_clicked(bool checked) {
    if (checked) {
        // Cancel any conflicting widget states
        ui_->pb_atc_enable->setChecked(false);
        ui_->pb_water_fill_A->setChecked(false);

        // Send signal
        emit CommandWater(Water::Side::kA, Water::State::kDraining);
    } else {
        // Return to stable state
        emit CommandWater(Water::Side::kA, Water::State::kStopped);
    }
}

#if LIBRA_VERSION == 1
/**
 * @brief Toggles force-filling of counterweight #2. Implicitly disables
 *        automatic torque compensation.
 *
 * @param checked Whether to force-fill the counterweight
 *
 * @see on_pb_atc_enable_toggled
 */
void MainWindow::on_pb_water_fill_B_clicked(bool checked) {
    if (checked) {
        // Cancel any conflicting widget states
        ui_->pb_atc_enable->setChecked(false);
        ui_->pb_water_drain_B->setChecked(false);

        // Send signal
        emit CommandWater(Water::Side::kB, Water::State::kFilling);
    } else {
        // Return to stable state
        emit CommandWater(Water::Side::kB, Water::State::kStopped);
    }
}

/**
 * @brief Toggles force-draining of counterweight #2. Implicitly disables
 *        automatic torque compensation.
 *
 * @param checked Whether to force-drain the counterweight
 *
 * @see on_pb_atc_enable_toggled
 */
void MainWindow::on_pb_water_drain_B_clicked(bool checked) {
    if (checked) {
        // Cancel any conflicting widget states
        ui_->pb_atc_enable->setChecked(false);
        ui_->pb_water_fill_B->setChecked(false);

        // Send signal
        emit CommandWater(Water::Side::kB, Water::State::kDraining);
    } else {
        // Return to stable state
        emit CommandWater(Water::Side::kB, Water::State::kStopped);
    }
}
#endif
