<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>thread</name>
  <version>0.0.0</version>
  <description>ROS2-enabled threads for the LIBRA app</description>
  <maintainer email="brice.c.67b9@m.isct.ac.jp">Christian Brice</maintainer>
  <license>Please see LICENSE.txt in the project root directory.</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>libra_interfaces</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
