/******************************************************************************
 * @file   main_window.cpp
 * @brief  Main app window implementation file.
 *
 * @author brice.c.aa
 ******************************************************************************/

// Related Header
#include "main_window.h"

// C++ Standard Library Headers
#include <sys/stat.h>

// Other Library Headers
#include <QMessageBox>  // Qt::Widgets

// Project Headers
#include "ui_main_window.h"  // auto-generated by Qt

/* --- TABLE OF CONTENTS ---
 * !Helper Functions
 * !Thread Handlers (Slots)
 * !Menu Bar
 * !Main Window
 * !Uncategorized
 */

/**
 * @brief Standard constructor.
 *
 * @param parent Owning Qt widget (default: nullptr)
 */
MainWindow::MainWindow(QWidget* parent)
    : QMainWindow(parent), ui_(new Ui::MainWindow) {
    ui_->setupUi(this);

    // Check if app is running in Windows Subsystem for Linux (WSL2)
    {
        const char* wsl_path = "/run/WSL";

        struct stat buf {};

        if (stat(wsl_path, &buf) == 0 && S_ISDIR(buf.st_mode)) {
            qWarning()
                << "[WARN] You seem to be running this on WSL2. Please ensure "
                   "you have properly forwarded your USB connections.";
        }
    }

    // Set initial state UI of elements
    ui_->a_debug_mode->setChecked(debug_mode_);

    // --- Thread Management ---

    /* In Qt, thread management for subclassed QThreads generally has 4 steps:
     *   1) Initialize a new QThread object
     *   2) Register a QThread signal to return data to a MainWindow handler
     *   3) Register the QThread's exit signal to its own destruction slot
     *   4) Spin off the QThread
     * If the thread loops continuously, there is a fifth step:
     *   5) In the MainWindow destructor, interrupt or forcibly stop the QThread
     */

    // Arm thread
    ArmThread* arm_thread_ = new ArmThread(this, debug_mode_);

    // - MainWindow signals
    connect(this, &MainWindow::TryConnect,  // connect a specific actuator
            arm_thread_, &ArmThread::ConnectActuator);
    connect(this, &MainWindow::TryDisconnect,  // disconnect a specific actuator
            arm_thread_, &ArmThread::DisconnectActuator);

    connect(ui_->pb_connect_all,
            &QPushButton::clicked,  // connect all actuators
            arm_thread_, &ArmThread::ConnectAllActuators);
    connect(ui_->pb_disconnect_all,
            &QPushButton::clicked,  // disconnect all actuators
            arm_thread_, &ArmThread::DisconnectAllActuators);

    connect(this, &MainWindow::CommandOne,  // move a specific actuator
            arm_thread_, &ArmThread::Move);
    connect(this, &MainWindow::CommandAll,  // move all actuators
            arm_thread_, &ArmThread::MoveAll);
    connect(ui_->pb_arm_stop, &QPushButton::clicked,  // stop all actuators
            arm_thread_, &ArmThread::Stop);

    // - MainWindow slots
    connect(arm_thread_, &ArmThread::finished,  // receive status updates
            this, &MainWindow::deleteLater);
    connect(arm_thread_, &ArmThread::finished,  // handle error messages
            this, &MainWindow::deleteLater);

    // - Thread cleanup
    connect(arm_thread_, &ArmThread::finished,      // when thread exits
            arm_thread_, &ArmThread::deleteLater);  // ... deallocate

    arm_thread_->start();
}

/**
 * @brief Standard destructor.
 */
MainWindow::~MainWindow() {
    delete ui_;
}

//------------------------------------------------------------------------------
// !Helper Functions
//------------------------------------------------------------------------------

namespace {  // local to this file

}  // namespace

//------------------------------------------------------------------------------
// !Thread Handlers
//------------------------------------------------------------------------------

/**
 * @brief Parses messages from ArmThread.
 */
void MainWindow::HandleStatusMsg(const QString& status) {
    qDebug() << "[INFO] Arm status changed:" << status;
}

/**
 * @brief Handles errors from ArmThread.
 */
void MainWindow::HandleErrorMsg(const QString& err) {
    QMessageBox::critical(this, tr("Error"), err);
}

//------------------------------------------------------------------------------
// !Menu Bar
//------------------------------------------------------------------------------

/**
 * @brief Event handler for "Preferences" menu bar action "Debug Mode".
 *        Toggles debug prinouts for this object and all its children.
 */
void MainWindow::on_a_debug_mode_toggled(bool checked) {
    debug_mode_ = checked;

    if (debug_mode_) {
        qDebug() << "[DEBUG] Debug mode enabled";
    }
}

/**
 * @brief Event handler for "EPOS" menu bar action "Connect".
 *        Sends a request to open a connection to the EPOS-based yaw joint.
 */
void MainWindow::on_a_epos_connect_triggered() {
    emit TryConnect(ArmThread::Joint::kYaw);
}

/**
 * @brief Event handler for "EPOS" menu bar action "Disonnect".
 *        Sends a request to close the connection to the EPOS-based yaw joint.
 */
void MainWindow::on_a_epos_disconnect_triggered() {
    emit TryDisconnect(ArmThread::Joint::kYaw);
}

/**
 * @brief Event handler for "HEBI" menu bar action "Connect".
 *        Sends a request to open a connection to the HEBI-based pitch joint.
 */
void MainWindow::on_a_hebi_connect_triggered() {
    emit TryConnect(ArmThread::Joint::kPitch);
}

/**
 * @brief Event handler for "HEBI" menu bar action "Disonnect".
 *        Sends a request to close the connection to the HEBI-based pitch joint.
 */
void MainWindow::on_a_hebi_disconnect_triggered() {
    emit TryDisconnect(ArmThread::Joint::kPitch);
}

//------------------------------------------------------------------------------
// !Main Window
//------------------------------------------------------------------------------

/**
 * @brief Send a command signal for the yaw actuator to move.
 */
void MainWindow::on_pb_yaw_start_clicked() {
    auto val = ui_->sb_arm_yaw->value();

    emit CommandOne(ArmThread::Joint::kYaw, val);
}

/**
 * @brief Send a command signal for the pitch actuator to move.
 */
void MainWindow::on_pb_pitch_start_clicked() {
    auto val = ui_->sb_arm_pitch->value();

    emit CommandOne(ArmThread::Joint::kPitch, val);
}

/**
 * @brief Send a command signal for all actuators to move.
 */
void MainWindow::on_pb_arm_start_clicked() {
    auto yaw = ui_->sb_arm_yaw->value();
    auto pitch = ui_->sb_arm_pitch->value();
    std::vector<double> vals = {yaw, pitch};

    emit CommandAll(vals);
}

//------------------------------------------------------------------------------
// !Uncategorized
//------------------------------------------------------------------------------
