/******************************************************************************
 * @file   main_window.cpp
 * @brief  Main app window implementation file.
 *
 * @author brice.c.aa
 ******************************************************************************/

// Related Header
#include "main_window.h"

// C++ Standard Library Headers
#include <sys/stat.h>

// Other Library Headers
#include <QMessageBox>  // Qt::Widgets

// Project Headers
#include "ui_main_window.h"  // auto-generated by Qt

/* --- TABLE OF CONTENTS ---
 * !Helper Functions
 * !Thread Handlers (Slots)
 * !Menu Bar
 * !Main Window
 * !Uncategorized
 */

/**
 * @brief Standard constructor.
 *
 * @param parent Owning Qt widget (default: nullptr)
 */
MainWindow::MainWindow(QWidget* parent)
    : QMainWindow(parent), ui_(new Ui::MainWindow) {
    ui_->setupUi(this);

    // Check if app is running in Windows Subsystem for Linux (WSL2)
    {
        // NOLINTBEGIN
        const char* wsl_path = "/run/WSL";

        struct stat buf {};

        if (stat(wsl_path, &buf) == 0 && S_ISDIR(buf.st_mode)) {
            qWarning()
                << "[WARN] You seem to be running this on WSL2. Please ensure "
                   "you have properly forwarded your USB connections.";
        }
        // NOLINTEND
    }

    // Set initial state UI of elements
    ui_->a_debug_mode->setChecked(debug_mode_);

    // Initialize a map-of-maps that we will use to access certain label elements
    // for displaying actuator feedback, similar to how they are laid out in the UI
    InitializeFeedbackElementMap();

    // --- Internal Slots ---

    // Connect the sliders to their respective spinboxes, but not the other way
    // around since they'd become stuck in an endless feedback loop
    connect(ui_->hs_arm_yaw, &QSlider::valueChanged,  // yaw visual parity
            ui_->sb_arm_yaw, &QDoubleSpinBox::setValue);
    connect(ui_->hs_arm_pitch, &QSlider::valueChanged,  // pitch visual parity
            ui_->sb_arm_pitch, &QDoubleSpinBox::setValue);

    // --- Thread Management ---

    /* In Qt, thread management for subclassed QThreads generally has 4 steps:
     *   1) Initialize a new QThread object
     *   2) Register a QThread signal to return data to a MainWindow handler
     *   3) Register the QThread's exit signal to its own destruction slot
     *   4) Spin off the QThread
     * If the thread loops continuously, there is a fifth step:
     *   5) In the MainWindow destructor, interrupt or forcibly stop the QThread
     */

    // EPOS thread
    epos_thread_ = new EposThread(this, "EPOS4", "MAXON SERIAL V2", "USB",
                                  "USB0", 115200, debug_mode_);

    // - MainWindow signals
    connect(this, &MainWindow::UpdateDebugMode,  // update debug mode
            epos_thread_, &EposThread::SetDebugMode);

    connect(ui_->a_epos_connect, &QAction::triggered,  // connect to EPOS
            epos_thread_, &EposThread::Connect);
    connect(ui_->a_epos_disconnect, &QAction::triggered,  // disconnect EPOS
            epos_thread_, &EposThread::Disconnect);

    connect(this, &MainWindow::CommandEpos,  // update EPOS target(s)
            epos_thread_, &EposThread::SetTarget);
    connect(ui_->pb_arm_stop, &QPushButton::clicked,  // stop ALL actuators
            epos_thread_, &EposThread::Stop);

    // - MainWindow slots
    connect(epos_thread_, &EposThread::ReportFeedback,  // receive feedback
            this, &MainWindow::HandleActuatorFeedback);
    connect(epos_thread_, &EposThread::ReportStatus,  // receive minor statuses
            this, &MainWindow::HandleActuatorStatus);

    connect(epos_thread_, &EposThread::ErrorThrown,  // handle error messages
            this, &MainWindow::HandleErrorMsg);

    // - Thread cleanup
    connect(epos_thread_, &EposThread::finished,      // when thread exits
            epos_thread_, &EposThread::deleteLater);  // ... deallocate

    epos_thread_->start();

    // HEBI thread
    hebi_thread_ = new HebiThread(this, {"LIBRA"}, {"Pitch"}, debug_mode_);

    // - MainWindow signals
    connect(this, &MainWindow::UpdateDebugMode,  // update debug mode
            hebi_thread_, &HebiThread::SetDebugMode);

    connect(ui_->a_hebi_connect, &QAction::triggered,  // connect to HEBI
            hebi_thread_, &HebiThread::Connect);
    connect(ui_->a_hebi_disconnect, &QAction::triggered,  // disconnect HEBI
            hebi_thread_, &HebiThread::Disconnect);

    connect(this, &MainWindow::CommandHebi,  // update HEBI target(s)
            hebi_thread_, &HebiThread::SetTarget);
    connect(ui_->pb_arm_stop, &QPushButton::clicked,  // stop ALL actuators
            hebi_thread_, &HebiThread::Stop);

    // - MainWindow slots
    connect(hebi_thread_, &HebiThread::ReportFeedback,  // receive feedback
            this, &MainWindow::HandleActuatorFeedback);
    connect(hebi_thread_, &HebiThread::ReportStatus,  // receive minor statuses
            this, &MainWindow::HandleActuatorStatus);

    connect(hebi_thread_, &HebiThread::ErrorThrown,  // handle error messages
            this, &MainWindow::HandleErrorMsg);

    // - Thread cleanup
    connect(hebi_thread_, &HebiThread::finished,      // when thread exits
            hebi_thread_, &HebiThread::deleteLater);  // ... deallocate

    hebi_thread_->start();
}

/**
 * @brief Standard destructor.
 */
MainWindow::~MainWindow() {
    // Wrap up the worker thread(s) gracefully
    if (epos_thread_ != nullptr && epos_thread_->isRunning()) {
        epos_thread_->requestInterruption();  // signal thread to stop looping
        epos_thread_->wait();  // wait for thread cleanup to finish
    }
    if (hebi_thread_ != nullptr && hebi_thread_->isRunning()) {
        hebi_thread_->requestInterruption();
        hebi_thread_->wait();
    }

    delete ui_;
}

//------------------------------------------------------------------------------
// !Helper Functions
//------------------------------------------------------------------------------

namespace {  // local to this file

}  // namespace

/**
 * @brief Populates a map-of-maps with UI label elements, according to their
 *        corresponding actuator joint names (`Actuator::Joint`) and feedback types
 *        (`Actuator::Feedback`).
 *
 * @see Actuator::Joint Actuator::Feedback
 */
void MainWindow::InitializeFeedbackElementMap() {
    // Yaw joint
    feedback_element_map_[Actuator::Joint::kYaw]
                         [Actuator::Feedback::kTargetPos] = ui_->l_target_yaw;
    feedback_element_map_[Actuator::Joint::kYaw]
                         [Actuator::Feedback::kActualPos] = ui_->l_actual_yaw;
    feedback_element_map_[Actuator::Joint::kYaw]
                         [Actuator::Feedback::kActualTorque] = ui_->l_torque_yaw;

    // Pitch joint
    feedback_element_map_[Actuator::Joint::kPitch]
                         [Actuator::Feedback::kTargetPos] = ui_->l_target_pitch;
    feedback_element_map_[Actuator::Joint::kPitch]
                         [Actuator::Feedback::kActualPos] = ui_->l_actual_pitch;
    feedback_element_map_[Actuator::Joint::kPitch]
                         [Actuator::Feedback::kActualTorque] =
                             ui_->l_torque_pitch;
}

//------------------------------------------------------------------------------
// !Thread Handlers
//------------------------------------------------------------------------------

/**
 * @brief Sorts important actuator information into individual UI elements.
 *
 * @param feedbacks Unordered map of joint(s) and their corresponding feedback
 * @param feedback_type The type of primary feedback provided
 */
void MainWindow::HandleActuatorFeedback(
    const std::unordered_map<Actuator::Joint, double>& feedbacks,
    const Actuator::Feedback feedback_type) {
    for (const auto& feedback : feedbacks) {
        try {
            // Index into the relevant UI label using the map-of-maps
            // initialized in the constructor
            feedback_element_map_.at(feedback.first)
                .at(feedback_type)
                ->setText(QString::number(feedback.second, 'f', 1));  // 0.1
        } catch (const std::out_of_range&) {
            qCritical() << "[ERROR] No UI element mapped to joint"
                        << feedback.first << "and feedback type"
                        << feedback_type;
        }
    }
}

/**
 * @brief Prints miscellaneous actuator information at the bottom of the UI.
 *
 * @param status Newline-delimited status info
 * @param type The actuator type, for updating the corresponding UI element
 */
void MainWindow::HandleActuatorStatus(const QString& status,
                                      const Actuator::Type type) {
    switch (type) {
        case Actuator::Type::kEpos:
            ui_->l_yaw_status->setText(status);
            break;
        case Actuator::Type::kHebi:
            ui_->l_pitch_status->setText(status);
            break;
        default:
            // Shouldn't be able to get here
            qCritical() << "[ERROR] Received status from unknown actuator type:"
                        << type;
    }
}

/**
 * @brief Throws a pop-up error box upon receiving an error signal from a thread.
 *
 * @param err Fatal error message from an actuator
 */
void MainWindow::HandleErrorMsg(const QString& err) {
    QMessageBox::critical(this, tr("Error"), err);
}

//------------------------------------------------------------------------------
// !Menu Bar
//------------------------------------------------------------------------------

/**
 * @brief Event handler for "Preferences" menu bar action "Debug Mode".
 *        Toggles debug prinouts for this object and all its children.
 */
void MainWindow::on_a_debug_mode_toggled(bool checked) {
    debug_mode_ = checked;

    emit UpdateDebugMode(checked);

    if (debug_mode_) {
        qDebug() << "[DEBUG] Debug mode enabled";
    }
}

//------------------------------------------------------------------------------
// !Main Window
//------------------------------------------------------------------------------

/**
 * @brief Send a command signal to attempt to connect to all actuators.
 */
void MainWindow::on_pb_connect_all_clicked() {
    ui_->a_epos_connect->trigger();
    ui_->a_hebi_connect->trigger();
}

/**
 * @brief Send a command signal to disconnect all actuators.
 */
void MainWindow::on_pb_disconnect_all_clicked() {
    ui_->a_epos_disconnect->trigger();
    ui_->a_hebi_disconnect->trigger();
}

/**
 * @brief Send a command signal for the yaw actuator to move.
 */
void MainWindow::on_pb_yaw_start_clicked() {
    auto val = ui_->sb_arm_yaw->value();

    if (ui_->hs_arm_yaw->value() != val) {
        // If value was entered via the SpinBox, update the slider
        ui_->hs_arm_yaw->setValue(val);
    }

    emit CommandEpos({val});
}

/**
 * @brief Send a command signal for the pitch actuator to move.
 */
void MainWindow::on_pb_pitch_start_clicked() {
    auto val = ui_->sb_arm_pitch->value();

    if (ui_->hs_arm_pitch->value() != val) {
        // If value was entered via the SpinBox, update the slider
        ui_->hs_arm_pitch->setValue(val);
    }

    emit CommandHebi({val});
}

/**
 * @brief Send a command signal for all actuators to move.
 */
void MainWindow::on_pb_arm_start_clicked() {
    ui_->pb_yaw_start->animateClick();
    ui_->pb_pitch_start->animateClick();
}

/**
 * @brief Send a command signal for all actuators to stop.
 */
void MainWindow::on_pb_arm_stop_clicked() {
    // TODO: implementation
}

//------------------------------------------------------------------------------
// !Uncategorized
//------------------------------------------------------------------------------
