/******************************************************************************
 * @file   main_window.cpp
 * @brief  Main app window implementation file.
 *
 * @author brice.c.aa
 ******************************************************************************/

// Related Header
#include "main_window.h"

// C++ Standard Library Headers
#include <filesystem>
#include <iostream>
#include <sys/stat.h>

// Other Library Headers
#include <QDateTime>        // Qt::Core
#include <QMessageBox>      // Qt::Widgets
#include <QSerialPortInfo>  // Qt::SerialPort

// Project Headers
// #include "open_epos_window.h"  // TODO(brice.c.aa): add EPOS4 motor control
#include "serial_dialog.h"
#include "ui_main_window.h"  // auto-generated by Qt

// #include "utility.h"

/* --- TABLE OF CONTENTS ---
 * !Helper Functions
 * !Menu Bar
 * !Main Window
 * !Arm
 * !Manipulator
 * !Pumps
 * !Camera
 * !Misc.
 * !Uncategorized
 */

/* Constants */

constexpr int kInfoLifespan = 4000;  // 4s timer for non-hover status tips

constexpr int kHebiFeedbackCount = 3;  // total number of actuator feedback types
constexpr int kFluidStateCount = 4;  // number of pumps * number of pump states
constexpr int kCameraNodeCount = 3;  // total number of camera servos

/**
 * @brief Standard constructor.
 *
 * @param parent Owning Qt widget (default: nullptr)
 */
MainWindow::MainWindow(QWidget* parent)
    : QMainWindow(parent), ui_(new Ui::MainWindow),
      ser_water_(std::make_shared<QSerialPort>(this)),
      ser_servo_(std::make_shared<QSerialPort>(this)) {
    ui_->setupUi(this);

    // Set UI elements
    ui_->a_debug_mode->setChecked(debug_mode_);

    // Check if app is running in Windows Subsystem for Linux (WSL2)
    {
        const char* wsl_path = "/run/WSL";

        struct stat buf {};

        if (stat(wsl_path, &buf) == 0 && S_ISDIR(buf.st_mode)) {
            qWarning()
                << "[WARN] You seem to be running this on WSL2. Please ensure "
                   "you have properly forwarded your USB connections.";
        }
    }

    // --- Component Connection ---

    // TODO: EPOS autoconnect

    // TODO: LibraHebi autoconnect

    // TODO: SerialWater autoconnect

    // Camera
    qDebug() << "[INFO] Checking available video inputs...";

    const auto cameras = QMediaDevices::videoInputs();
    for (const auto& camera_device : cameras) {
        auto id = QString(camera_device.id());

        if (debug_mode_) {
            qDebug() << "[DEBUG] Found camera at " << camera_device.id();
        }

        // Populate ComboBox (new items are appended to existing list)
        ui_->cb_camera_id->addItem(id);
        // Populate internal map (used on ComboBox change)
        available_cameras_[id] = camera_device.description();
    }

    if (!available_cameras_.empty()) {
        ui_->pb_camera_capture->setEnabled(true);
        ui_->pb_camera_record->setEnabled(true);
    } else if (debug_mode_) {
        qDebug() << "[DEBUG] No cameras were found";
    }

    // --- Slot Management (non-thread) ---

    // Pumps (FOR TESTING PURPOSES ONLY)
    connect(ui_->pb_pump_enable, &QPushButton::clicked,  // when clicked
            ui_->w_tank_visual, &TankWidget::Fill);      // start filling

    connect(ui_->pb_pump_disable, &QPushButton::clicked,  // when clicked
            ui_->w_tank_visual, &TankWidget::Stop);       // stop filling

    connect(ui_->pb_pump_drain, &QPushButton::clicked,  // when clicked
            ui_->w_tank_visual, &TankWidget::Drain);    // force drain

    // --- Thread Management ---

    // TOOD: is this necessary in the new app?

    /* In Qt, thread management for subclassed QThreads generally has 4 steps:
     *   1) Initialize a new QThread object
     *   2) Register a QThread signal to return data to a MainWindow handler
     *   3) Register the QThread's exit signal to its own destruction slot
     *   4) Spin off the QThread
     * If the thread loops continuously, there is a fifth step:
     *   5) In the MainWindow destructor, interrupt or forcibly stop the QThread
     */

    // Main controller thread
    /*
    main_thread_ = new MainThread(libra_hebi_, ser_water_, ser_servo_);

    connect(this, &MainWindow::CommandArm,  // send arm commands to main thread
            main_thread_, &MainThread::UpdateArmTarget);
    connect(main_thread_,
            &MainThread::finished,  // when thread exits, deallocate
            main_thread_, &MainThread::deleteLater);

    main_thread_->start();
    */
}

/**
 * @brief Standard destructor.
 */
MainWindow::~MainWindow() {
    // Wrap up the worker thread(s) gracefully
    main_thread_->requestInterruption();  // signal thread to stop looping
    main_thread_->wait();                 // wait for thread cleanup to finish
}

/**
 * @brief Standard constructor.
 */
MainThread::MainThread(std::shared_ptr<LibraHebi> libra_arm,
                       std::shared_ptr<QSerialPort> ser_water,
                       std::shared_ptr<QSerialPort> ser_servo)
    : libra_hebi_(libra_arm), ser_water_(ser_water), ser_servo_(ser_servo) {}

/**
 * @brief Standard destructor.
 */
MainThread::~MainThread() {
    // Ensure data is flushed to log files and close them
    if (continuous_log_.is_open()) {
        continuous_log_.close();
    }
    if (snapshot_log_.is_open()) {
        snapshot_log_.close();
    }
}

//------------------------------------------------------------------------------
// !Helper Functions
//------------------------------------------------------------------------------

namespace {  // local to this file

/**
 * @brief Provides a filename-safe string of the current date and time.
 *
 * @return String formatted as "yyyy-MM-ddTHH-mm-ss"
 */
std::string GetDateTimeStr() {
    auto dts = QDateTime::currentDateTime().toString(Qt::ISODateWithMs);
    dts.replace(":", "-");         // replace colons (invalid in filenames)
    dts = dts.section('.', 0, 0);  // remove milliseconds
    return dts.toStdString();
}

/**
 * @brief Provides an Excel-friendly string of the current time.
 *
 * @return String formatted as "HH-mm-ss.zzz"
 */
std::string GetTimestampStr() {
    return QDateTime::currentDateTime().toString("HH:mm:ss.zzz").toStdString();
}

}  // namespace

//------------------------------------------------------------------------------
// !Worker Threads
//------------------------------------------------------------------------------

/**
 * @brief Initializes a logfile with named columns.
 *
 * @param name The identifier to be assigned to the log filename.
 */
std::ofstream MainThread::InitializeLog(std::string name) {
    // Check if the log directory hasn't been created yet
    if (std::filesystem::create_directory("log")) {
        qDebug() << "[INFO] Created log directory";
    }

    // Ensure log directory exists (false returned, no error)
    assert(!std::filesystem::create_directory("log"));

    // Create log file and populate column headers
    std::ofstream logfile;
    logfile.open("log/" + GetDateTimeStr() + "_" + name + ".csv");
    logfile << "Time,,"
            << "TP_Yaw (deg),TP_Pitch (deg),,"
            << "PP_Yaw (deg),PP_Pitch (deg),,"
            << "PT_Yaw (Nm),PT_Pitch (Nm),,"
            << "PUMP_IN,PUMP_OUT,,"
            << "TP_ManipBase (deg),TP_ManipPan (deg),TP_ManipTilt (deg),,"
            << "Voltage (V),Current (A)" << std::endl;

    return logfile;
}

/**
 * @brief Sends HEBI thread new target values.
 *
 * @param input HEBI actuator target value(s) (order defined in `hebi_thread.h`)
 */
void MainThread::UpdateArmTarget(const std::array<double, 2>& input) {
    arm_target_ = input;

    if (debug_mode_) {
        qDebug() << "[DEBUG] Received the following arm targets:"
                 << input.at(0);
    }

    qDebug() << "[WARN] HEBI actuator control unimplemented!";

    // TODO: implementation
}

/**
 * @brief TODO: Rewrite.
 *        Primary request and response loop for the LIBRA app.
 *        Continuously retrieves actuator and Arduino statuses.
 *        Executed when `start()` is called on the thread.
 */
void MainThread::run() {
    // Initialize fluid system runtime variables
    int count = 0;
    uint8_t cmd_water = 0;

    // Initialize logging
    continuous_log_ = InitializeLog("continuous_log");
    snapshot_log_ = InitializeLog("shot_log");

    // Loop until MainWindow calls QThread::requestInterruption()
    while (!isInterruptionRequested()) {
        /* ----- CHECK FOR COMPONENT OBJECTS (TEMPORARY) ----- */

        if (libra_hebi_ == nullptr) {
            qDebug() << "[WARN] HEBI actuators are not connected! Sleeping...";
            QThread::sleep(5);  // check again in 5 seconds
            continue;
        } else if (ser_water_ == nullptr) {
            qDebug()
                << "[WARN] SerialWater Arduino is not connected! Sleeping...";
            QThread::sleep(5);  // check again in 5 seconds
            continue;
        } else if (ser_servo_ == nullptr) {
            qDebug()
                << "[WARN] SerialServo Arduino is not connected! Sleeping...";
            QThread::sleep(5);  // check again in 5 seconds
            continue;
        }

        /* ----- START ----- */

        // Retrieve HEBI actuator data
        arm_current_.at(0) = libra_hebi_->GetCommandPosition(
            LibraHebi::Joint::kPitch);
        arm_current_.at(1) = libra_hebi_->GetFeedbackPosition(
            LibraHebi::Joint::kPitch);
        arm_current_.at(2) = libra_hebi_->GetFeedbackEffort(
            LibraHebi::Joint::kPitch);

        /* ----- MANIPULATOR ----- */

        // Keep manipulator level by negating arm pitch angle
        const double arm_pitch = arm_current_.at(0);
        if (arm_pitch <= 30) {
            manip_pos_.at(0) = (arm_pitch <= 0) ? -arm_pitch : 0;
        } else {
            manip_pos_.at(0) = 180 - arm_pitch;
        }

        // Retrieve desired camera pan angle
        if (manip_dir_.at(1) != 0) {
            manip_pos_.at(1) += manip_dir_.at(1) * 90.0 / (60.0 * 60.0);
            if ((manip_pos_.at(1) > manip_setpos_.at(1))
                == (manip_dir_.at(1) == 1)) {
                manip_pos_.at(1) = manip_setpos_.at(1);
                manip_dir_.at(1) = 0;
            }
        }

        // Retrieve desired camera tilt angle
        if (manip_dir_.at(2) != 0) {
            manip_pos_.at(2) += manip_dir_.at(2) * 90.0 / (60.0 * 60.0);
            if ((manip_pos_.at(2) > manip_setpos_.at(2))
                == (manip_dir_.at(2) == 1)) {
                manip_pos_.at(2) = manip_setpos_.at(2);
                manip_dir_.at(2) = 0;
            }
        }

        // Send commands to SerialServo Arduino
        std::stringstream servo_ss;
        servo_ss << manip_pos_.at(0) << " " << manip_pos_.at(1) << " "
                 << manip_pos_.at(2) << "\n";
        // (create string object to avoid using temporary object in call to write)
        auto cmd_servo = servo_ss.str();
        ser_servo_->write(cmd_servo.c_str());  // send command

        /* ----- ARM and FLUID SYSTEM ----- */

        // Send commands to SerialWater Arduino
        // TODO(brice.c.aa): since LIBRA-II is simpler, this can be refactored
        switch (water_mode_) {
            case kStandby:  // Normal operational mode
                cmd_water = 0;

                // Excess torque (> 5.0 Nm)
                if (water_en_
                    && abs(libra_hebi_->GetFeedbackEffort(
                           LibraHebi::Joint::kPitch))
                           > 5.0) {
                    // Pause arm movement
                    libra_hebi_->Stop();
                    water_mode_ = WaterMode::kAdjust;
                }
                break;

            case kAdjust:  // Water level adjustment mode
                // Normal response to torque (2.5-5.0 Nm)
                if (water_en_
                    && abs(libra_hebi_->GetFeedbackEffort(
                           LibraHebi::Joint::kPitch))
                           >= 2.5) {
                    if (count == 0) {
                        const double theta = libra_hebi_->GetFeedbackEffort(
                            LibraHebi::Joint::kPitch);

                        // Bit field "0b1234":
                        //   1: PUMP_IN | 2: UNUSED | 3: PUMP_OUT | 4: UNUSED
                        if (theta > 0) {  // front-heavy
                            cmd_water = 0b1000;
                        } else {  // back-heavy
                            cmd_water = 0b0010;
                        }
                    }
                }

                // If torque subsides (< 2.5 Nm)
                else if (count == 0) {
                    // Put fluid system on standby
                    water_mode_ = WaterMode::kStandby;
                    cmd_water = 0;

                    // Resume arm movement
                    // TODO: EPOS (Maxon) implementation
                    // libra_maxon_->Move(arm_target_.at(0));
                    libra_hebi_->Move(arm_target_.at(1));
                }
                break;

            case kDrain:
                // Drain until ENABLE or DISABLE are clicked
                cmd_water = 0b0010;

                // Pause arm movement
                // TODO: EPOS (Maxon) implementation
                // libra_maxon_->Stop();
                libra_hebi_->Stop();
                break;
        }

        auto to_write = static_cast<char>(cmd_water);
        ser_water_->write(&to_write);  // send command

        // TODO: Visualize status of fluid system

        /* ----- LOGGING ----- */

        // Update continuous log
        if (count == 0) {
            // Timestamp
            continuous_log_ << GetTimestampStr() + ",,";

            // Actuator info
            for (auto i = 0; i < kHebiFeedbackCount; i++) {
                continuous_log_ << arm_current_.at(i) << ",,";
            }

            // Fluid system info
            for (auto i = 0; i < kFluidStateCount; i++) {
                continuous_log_ << ((cmd_water & (1 << (3 - i))) ? 1 : 0)
                                << ",";
            }
            continuous_log_ << ",";

            // Camera actuator info
            // TODO: use kCameraNodeCount
            continuous_log_ << manip_pos_.at(0) << "," << manip_pos_.at(1)
                            << "," << manip_pos_.at(2);

            // Flush the current line
            continuous_log_ << std::endl;
        }

        // TODO: refactor this weird attempt at update limiting
        count++;
        if (count == 30) {
            count = 0;
        }
    }
}

/**
 * @brief Sets whether or not verbose debug text is displayed
 * @param true to enable, false to disable
 */
void MainThread::SetDebugMode(bool enabled) {
    debug_mode_ = enabled;
}

//------------------------------------------------------------------------------
// !Menu Bar
//------------------------------------------------------------------------------

/**
 * @brief Toggles debug prinouts for this object and all its children.
 */
void MainWindow::on_a_debug_mode_toggled(bool checked) {
    debug_mode_ = checked;

    if (debug_mode_) {
        qDebug() << "[DEBUG] Debug mode enabled";
    }

    // Propagate to all children
    if (main_thread_ != nullptr) {
        main_thread_->SetDebugMode(debug_mode_);
    }
    if (libra_hebi_ != nullptr) {
        libra_hebi_->SetDebugMode(debug_mode_);
    }
    if (ser_water_ != nullptr) {
        // TODO: make new class inheriting from QSerialPort
        // ser_water_->SetDebugMode(debug_mode_);
    }
    if (ser_servo_ != nullptr) {
        // TODO: make new class inheriting from QSerialPort
        // ser_servo_->SetDebugMode(debug_mode_);
    }
}

/**
 * @brief Event handler for "EPOS" menu bar action "Connect".
 *        Brings up a dialog box similar to `VCS_OpenDeviceDlg()`.
 */
void MainWindow::on_a_epos_connect_triggered() {
    qDebug() << "[WARN] EPOS not yet implemented!";
    return;

    // TODO: implementation

    // Reflect changes in UI
    ui_->a_epos_connect->setEnabled(false);
    ui_->a_epos_disconnect->setEnabled(true);
    // TODO: enable relevant MainWindow buttons
}

/**
 * @brief Event handler for "EPOS" menu bar action "Disonnect".
 *        Terminates the active EPOS controller connection, if any.
 */
void MainWindow::on_a_epos_disconnect_triggered() {
    qDebug() << "[WARN] EPOS not yet implemented!";
    return;

    // TODO: implementation

    // Reflect changes in UI
    ui_->a_epos_connect->setEnabled(true);
    ui_->a_epos_disconnect->setEnabled(false);
    // TODO: disable relevant MainWindow buttons
}

/**
 * @brief Event handler for "HEBI" menu bar action "Connect".
 */
void MainWindow::on_a_hebi_connect_triggered() {
    // Only continue if "Connect" was successful
    libra_hebi_ = std::make_shared<LibraHebi>();
    if (!libra_hebi_->Connect()) {
        libra_hebi_.reset();
        return;
    }

    if (debug_mode_) {
        qDebug() << "[DEBUG] HEBI connect returned successfully";
    }

    // Reflect changes in UI
    ui_->a_hebi_connect->setEnabled(false);
    ui_->a_hebi_disconnect->setEnabled(true);
    ui_->pb_arm_start->setEnabled(true);
    ui_->pb_arm_stop->setEnabled(true);
}

/**
 * @brief Event handler for "HEBI" menu bar action "Disconnect".
 *        Terminates all active HEBI actuator connections, if any.
 */
void MainWindow::on_a_hebi_disconnect_triggered() {
    // Clear the LibraHebi object
    libra_hebi_.reset();

    // Reflect changes in UI
    ui_->a_hebi_connect->setEnabled(true);
    ui_->a_hebi_disconnect->setEnabled(false);
    ui_->pb_arm_start->setEnabled(false);
    ui_->pb_arm_stop->setEnabled(false);
}

/**
 * @brief Event handler for "Pumps" menu bar action "Connect".
 *        Brings up a dialog box of available serial USB devices.
 */
void MainWindow::on_a_pump_connect_triggered() {
    // Check if SerialWater Arduino (COM3) is connected
    bool found = false;
    foreach (const QSerialPortInfo& info, QSerialPortInfo::availablePorts()) {
        if (info.portName() == "COM3") {
            found = true;
            break;
        }
        if (debug_mode_) {
            // Enumerate available serial ports
            qDebug() << "[DEBUG] Found SerialPort with following metadata";
            qDebug() << "  Port: " << info.portName();
            qDebug() << "  Description: " << info.description();
            qDebug() << "  Manufacturer: " << info.manufacturer() << "\n";
            return;
        }
    }

    if (!found) {
        qDebug() << "[ERROR] SerialWater (COM3) not found!";
        return;
    }

    // Set port options
    ser_water_->setPortName("COM3");
    ser_water_->setBaudRate(QSerialPort::Baud115200);
    ser_water_->setDataBits(QSerialPort::Data8);
    ser_water_->setParity(QSerialPort::NoParity);
    ser_water_->setStopBits(QSerialPort::OneStop);
    ser_water_->setFlowControl(QSerialPort::NoFlowControl);

    // Only continue if "open" was successful
    if (!ser_water_->open(QIODevice::ReadOnly)) {
        qDebug() << "[ERROR] Failed to open port: COM3!";
        ser_water_.reset();
        return;
    }

    // Ensure data gets processed when it's made available
    connect(ser_water_.get(), &QSerialPort::readyRead, this,
            &MainWindow::UpdatePumpVals);

    // Reflect changes in UI
    ui_->a_pump_connect->setEnabled(false);
    ui_->a_pump_disconnect->setEnabled(true);
    ui_->pb_pump_enable->setEnabled(true);
    ui_->pb_pump_disable->setEnabled(true);
    ui_->pb_pump_drain->setEnabled(true);
}

/**
 * @brief Event handler for "Pumps" menu bar action "Disconnect".
 *        Terminates the connection to the `SerialWater` Arduino, if it exists.
 */
void MainWindow::on_a_pump_disconnect_triggered() {
    // Clear the Serial object
    ser_water_.reset();

    // Reflect changes in UI
    ui_->a_pump_connect->setEnabled(true);
    ui_->a_pump_disconnect->setEnabled(false);
    ui_->pb_pump_enable->setEnabled(false);
    ui_->pb_pump_disable->setEnabled(false);
    ui_->pb_pump_drain->setEnabled(false);
}

/**
 * @brief Event handler for "Pump/Advanced" menu bar action "Set empty (0%)".
 *        Forces the tank (water bladder) visualization to show as empty.
 *
 * @note Only use if there is a discrepancy with the physical water bladders.
 */
void MainWindow::on_a_pump_set_empty_triggered() {
    ui_->w_tank_visual->OverrideLevel(0.0);
}

/**
 * @brief Event handler for "Pump/Advanced" menu bar action "Set full (100%)".
 *        Forces the tank (water bladder) visualization to show as full.
 *
 * @note Only use if there is a discrepancy with the physical water bladders.
 */
void MainWindow::on_a_pump_set_full_triggered() {
    ui_->w_tank_visual->OverrideLevel(1.0);
}

/**
 * @brief Event handler for "Camera" menu bar action "Connect (servos)".
 *        Brings up a dialog box of available serial USB devices.
 */
void MainWindow::on_a_manip_servos_connect_triggered() {
    // Check if SerialServo Arduino (COM4) is connected
    bool found = false;
    foreach (const QSerialPortInfo& info, QSerialPortInfo::availablePorts()) {
        if (info.portName() == "COM4") {
            found = true;
            break;
        }
        if (debug_mode_) {
            // Enumerate available serial ports
            qDebug() << "[DEBUG] Found SerialPort with following metadata";
            qDebug() << "  Port: " << info.portName();
            qDebug() << "  Description: " << info.description();
            qDebug() << "  Manufacturer: " << info.manufacturer() << "\n";
            return;
        }
    }

    if (!found) {
        qDebug() << "[ERROR] SerialServo (COM4) not found!";
        return;
    }

    // Set port options
    ser_servo_->setPortName("COM4");
    ser_servo_->setBaudRate(QSerialPort::Baud115200);
    ser_servo_->setDataBits(QSerialPort::Data8);
    ser_servo_->setParity(QSerialPort::NoParity);
    ser_servo_->setStopBits(QSerialPort::OneStop);
    ser_servo_->setFlowControl(QSerialPort::NoFlowControl);

    // Only continue if "open" was successful
    if (!ser_servo_->open(QIODevice::ReadOnly)) {
        qDebug() << "[ERROR] Failed to open port: COM4!";
        ser_servo_.reset();
        return;
    }

    // Ensure data gets processed when it's made available
    connect(ser_servo_.get(), &QSerialPort::readyRead, this,
            &MainWindow::UpdateServoVals);

    // Reflect changes in UI
    ui_->a_manip_servos_connect->setEnabled(false);
    ui_->a_manip_servos_disconnect->setEnabled(true);
    ui_->pb_manip_slow->setEnabled(true);
    ui_->pb_manip_fast->setEnabled(true);
}

/**
 * @brief Event handler for "Camera" menu bar action "Disconnect".
 *        Terminates the connection to the `SerialServo` Arduino, if it exists.
 */
void MainWindow::on_a_manip_servos_disconnect_triggered() {
    // Clear the Serial and CameraManager objects
    ser_servo_.reset();
    camera_manager_.reset();

    // Reflect changes in UI
    ui_->a_manip_servos_connect->setEnabled(true);
    ui_->a_manip_servos_disconnect->setEnabled(false);
    ui_->pb_manip_slow->setEnabled(false);
    ui_->pb_manip_fast->setEnabled(false);
}

/**
 * @brief Event handler for "LIDAR" menu bar action "Connect".
 *        Brings up a dialog box of available serial ACM devices.
 *
 * @note Although the Hokuyo LIDAR is connected via USB, it is listed as
 * ACM. See https://sourceforge.net/p/urgnetwork/wiki/serial_linux_en/
 */
void MainWindow::on_a_lidar_connect_triggered() {
    // Display the "Connect to Serial" dialog
    SerialDialog w_serial("ACM", debug_mode_, this);
    w_serial.setModal(true);
    w_serial.exec();

    // Only continue if "Connect" was successful
    if (w_serial.result() != QDialog::Accepted) {
        qWarning() << "[WARN] Failed to connect to serial camera servo "
                      "controller!";
        return;
    }

    if (debug_mode_) {
        qDebug() << "[DEBUG] LIDAR serial dialog returned successfully";
    }

    // Open a connection to the Hokuyo LIDAR
    lidar_ = std::make_shared<Lidar>(w_serial.GetDeviceName());
}

/**
 * @brief Event handler for "LIDAR" menu bar action "Disconnect".
 *        Terminates the connection to the LIDAR, if it exists.
 */
void MainWindow::on_a_lidar_disconnect_triggered() {
    // Clear the Lidar object
    lidar_.reset();

    // Reflect changes in UI
    ui_->a_lidar_disconnect->setEnabled(false);
    ui_->a_lidar_about->setEnabled(false);
}

/**
 * @brief Event handler for "LIDAR" menu bar action "About".
 *        Opens a dialog box with sensor metadata, if connected.
 */
void MainWindow::on_a_lidar_about_triggered() {
    if (lidar_ != nullptr) {
        QMessageBox::information(this, "LIDAR - About",
                                 QString::fromStdString("<pre>"  // monospace
                                                        + lidar_->GetMetadata()
                                                        + "</pre>"));
    } else {
        qWarning() << "[WARN] LIDAR object not yet initialized!";
    }
}

//------------------------------------------------------------------------------
// !Main Window
//------------------------------------------------------------------------------

//------------------------------------------------------------------------------
// !Arm
//------------------------------------------------------------------------------

/**
 * @brief Starts movement of all actuators.
 */
void MainWindow::on_pb_arm_start_clicked() {
    std::array<double, 2> target{0};

    if (libra_hebi_ != nullptr) {
        target.at(0) = ui_->sb_arm_yaw->text().toDouble();
    } else {
        qDebug() << "[WARN] EPOS (Maxon) actuator not connected!";
    }

    if (libra_hebi_ != nullptr) {
        target.at(1) = ui_->sb_arm_pitch->text().toDouble();
    } else {
        qDebug() << "[WARN] HEBI actuator not connected!";
    }

    emit CommandArm(target);
}

/**
 * @brief Stops movement of all actuators.
 */
void MainWindow::on_pb_arm_stop_clicked() {
    if (libra_hebi_ == nullptr) {
        qDebug() << "[WARN] HEBI actuators not connected!";
        return;
    }

    libra_hebi_->Stop();
}

//------------------------------------------------------------------------------
// !Manipulator
//------------------------------------------------------------------------------

/**
 * @brief Moves manipulator servos at a leisurely pace.
 */
void MainWindow::on_pb_manip_slow_clicked() {
    if (ser_servo_ == nullptr) {
        qDebug() << "[WARN] SerialServo not connected!";
        return;
    }

    qDebug() << "[WARN] Camera servo control not yet implemented!";

    // TODO: implementation (adapt code below)
    /*
    manip_setpos_.at(1) = ibox_camera_pan_->GetNum();
    manip_setpos_.at(2) = ibox_camera_tilt_->GetNum();
    manip_dir_.at(1) = (manip_setpos_.at(1) > manip_pos_.at(1)) ? 1 :
                        ((manip_setpos_.at(1) < manip_pos_.at(1)) ? -1 : 0);
    manip_dir_.at(2) = (manip_setpos_.at(2) > manip_pos_.at(2)) ? 1 :
                        ((manip_setpos_.at(2) < manip_pos_.at(2)) ? -1 : 0);
    manip_pos_.at(1) += manip_dir_.at(1) * 90.0 / (60.0 * 60.0);
    manip_pos_.at(2) += manip_dir_.at(2) * 90.0 / (60.0 * 60.0);
    */
}

/**
 * @brief Moves manipulator servos at maximum speed (near-instant).
 */
void MainWindow::on_pb_manip_fast_clicked() {
    if (ser_servo_ == nullptr) {
        qDebug() << "[WARN] SerialServo not connected!";
        return;
    }

    qDebug() << "[WARN] Camera servo control not yet implemented!";

    // TODO: implementation (adapt code below)
    /*
    manip_pos_.at(1) = ibox_camera_pan_->GetNum();
    manip_pos_.at(2) = ibox_camera_tilt_->GetNum();
    */
}

/**
 * @brief Updates camera servo values shown in the UI (from `ser_servo_`
 * Arduino).
 */
void MainWindow::UpdateServoVals() {
    auto data = ser_servo_->readAll();
    if (debug_mode_) {
        qDebug() << "[DEBUG] Received data from SerialServo:" << data;
    }

    qDebug() << "[WARN] Camera servo control not yet implemented!";

    // TODO: implementation
}

//------------------------------------------------------------------------------
// !Pumps
//------------------------------------------------------------------------------

/**
 * @brief Enables operation of fluid system pumps.
 */
void MainWindow::on_pb_pump_enable_clicked() {
    if (!ser_water_->isOpen()) {
        qDebug() << "[WARN] SerialWater not connected!";
        return;
    }

    qDebug() << "[WARN] Pump control not yet implemented!";

    // TODO: implementation (adapt code below)
    /*
    water_en_ = true;
    water_mode_ = WaterMode::kStandby;
    */
}

/**
 * @brief Disables operation of fluid system pumps.
 *
 * @todo Combine funcitonality with `on_pb_pump_enable_clicked()` and
 * refactor the resulting function. Don't forget to rename it to something
 * that makes more sense, e.g., including the word "toggle". For reference
 * on changing button text to reflect state, see
 * `on_pb_camera_record_clicked()`.
 */
void MainWindow::on_pb_pump_disable_clicked() {
    if (!ser_water_->isOpen()) {
        qDebug() << "[WARN] SerialWater not connected!";
        return;
    }

    qDebug() << "[WARN] Pump control not yet implemented!";

    // TODO: implementation (adapt code below)
    /*
    water_en_ = false;
    water_mode_ = WaterMode::kStandby;
    */
}

/**
 * @brief Enables fluid system pumps and forces them on.
 */
void MainWindow::on_pb_pump_drain_clicked() {
    if (!ser_water_->isOpen()) {
        qDebug() << "[WARN] SerialWater not connected!";
        return;
    }

    qDebug() << "[WARN] Pump control not yet implemented!";

    // TODO: implementation (adapt code below)
    /*
    water_en_ = true;
    water_mode_ = WaterMode::kDrain;
    */
}

/**
 * @brief Updates pump values shown in the UI (from `ser_water_` Arduino).
 */
void MainWindow::UpdatePumpVals() {
    auto data = ser_water_->readAll();
    if (debug_mode_) {
        qDebug() << "[DEBUG] Received data from SerialWater:" << data;
    }

    qDebug() << "[WARN] Pump control not yet implemented!";

    // TODO: implementation
}

//------------------------------------------------------------------------------
// !Camera
//------------------------------------------------------------------------------

/**
 * @brief Connects to the selected camera feed.
 */
void MainWindow::on_cb_camera_id_currentTextChanged(const QString& sel) {
    if (camera_manager_ != nullptr) {
        if (debug_mode_) {
            qDebug() << "[DEBUG] Resetting existing camera manager";
        }
        camera_manager_.reset();
    }

    // Show human-readable camera name
    ui_->l_camera_name->setText(available_cameras_[sel]);

    // Open a connection to the camera
    camera_manager_ = std::make_unique<CameraManager>(sel,
                                                      ui_->vw_camera_viewfinder,
                                                      this);
    camera_manager_->Start();

    // Reflect changes in UI
    ui_->pb_camera_capture->setEnabled(true);
    ui_->pb_camera_record->setEnabled(true);
}

/**
 * @brief Captures a still image from the active camera feed.
 */
void MainWindow::on_pb_camera_capture_clicked() {
    camera_manager_->Capture();

    // Display a status tip at the bottom of the UI
    statusBar()->showMessage("Saved capture to img/ directory!", kInfoLifespan);
}

/**
 * @brief Toggles video recording from the active camera feed.
 */
void MainWindow::on_pb_camera_record_clicked() {
    if (camera_manager_->Record()) {
        // Clearly display a "recording" state
        ui_->pb_camera_record->setStyleSheet("color: red;");
        ui_->pb_camera_record->setText("STOP");
    } else {
        // Display a status tip at the bottom of the UI
        statusBar()->showMessage("Saved recording to vid/ directory!",
                                 kInfoLifespan);

        // Revert to original state
        ui_->pb_camera_record->setStyleSheet("color: black;");
        ui_->pb_camera_record->setText("RECORD");
    }
}

//------------------------------------------------------------------------------
// !Misc.
//------------------------------------------------------------------------------

/**
 * @brief Records a "screenshot" of loggable data to a separate log file.
 */
void MainWindow::on_pb_logshot_clicked() {
    qDebug() << "[WARN] Not yet reimplemented!";

    // TODO: implementation (adapt code below)
    /*
    const std::string dts = GetTimestampStr();
    snapshot_log_ << dts << ",,";
    for (auto i = 0; i < kHebiFeedbackCount; i++) {
        snapshot_log_ << arm_current_.at(i) << ",,";
    }
    snapshot_log_ << ibox_voltage_->GetNum() << ","
                  << ibox_current_->GetNum() << "\n";

    colorize::Print("Snapshot - " + dts + " | Voltage: "
                        + std::to_string(ibox_voltage_->GetNum())
                        + " V | Current: "
                        + std::to_string(ibox_current_->GetNum()) + " A\n",
                    colorize::Level::kInfo);
    */
}

//------------------------------------------------------------------------------
// !Uncategorized
//------------------------------------------------------------------------------
