/******************************************************************************
 * @file   main_window.cpp
 * @brief  Main app window implementation file.
 *
 * @author brice.c.aa
 ******************************************************************************/

// Related Header
#include "main_window.h"

// C++ Standard Library Headers
#include <filesystem>
#include <iostream>
#include <sys/stat.h>

// Other Library Headers
#include <QDateTime>    // Qt::Core
#include <QMessageBox>  // Qt::Widgets

// Project Headers
#include "open_serial_dialog.h"
#include "ui_main_window.h"  // auto-generated by Qt

/* --- TABLE OF CONTENTS ---
 * !Local Helpers
 * !Class Management
 * !Class Helpers
 * !Thread Handlers (Slots)
 * !Menu Bar
 * !Main Window
 * !Arm
 * !Manipulator
 * !Water
 * !Camera
 * !Misc.
 * !Uncategorized
 */

// Qt

constexpr int kPrecision = 1;        // 0.1
constexpr int kInfoLifespan = 4000;  // 4s timer for non-hover status tips

// Arduino

#if LIBRA_VERSION == 1
constexpr bool kManipMoveSlow = true;
constexpr bool kManipMoveFast = false;
#endif

//------------------------------------------------------------------------------
// !Local Helpers
//------------------------------------------------------------------------------

namespace {

/**
 * @brief Checks whether app is running in Windows Subsystem for Linux (WSL2).
 */
void CheckWslEnvironment() {
    const char* wsl_path = "/run/WSL";

    struct stat buf {};

    if (stat(wsl_path, &buf) == 0 && S_ISDIR(buf.st_mode)) {
        qWarning()
            << "[WARN] You seem to be running this on WSL2. Please ensure "
               "you have properly forwarded your USB connections.";
    }
}

/**
 * @brief Fully deletes a widget or layout from the user interface.
 *
 * @tparam T Any visual QObject type
 * @param widget The widget or layout to be removed
 */
template<typename T>
void RemoveUiElement(T*& element) {
    if (!element) {
        return;
    }

    // To avoid duplicating code, define this lambda capable of handling both
    // QWidgets and QLayouts (since they boil down to different QObjects)
    auto RemoveFromParentLayout = [](QObject* obj) {
        if (!obj) {
            return;
        }

        // All objects are eventually children of a QWidget, so this is allowed
        if (auto* p = qobject_cast<QWidget*>(obj->parent())) {
            if (auto* pl = p->layout()) {
                // We must explicitly cast since indexOf() does not take QObjects
                if (auto* w = qobject_cast<QWidget*>(obj)) {
                    if (int i = pl->indexOf(w); i >= 0) {
                        delete pl->takeAt(i);
                    }
                } else if (auto* l = qobject_cast<QLayout*>(obj)) {
                    if (int i = pl->indexOf(l); i >= 0) {
                        delete pl->takeAt(i);
                    }
                }
            }
        }
    };

    RemoveFromParentLayout(element);

    // Handle layouts
    if constexpr (std::is_base_of_v<QLayout, T>) {
        // Recursively delete all children
        while (QLayoutItem* item = element->takeAt(0)) {
            if (auto* w = item->widget()) {
                RemoveUiElement(w);
            } else if (auto* l = item->layout()) {
                RemoveUiElement(l);
            }
            delete item;
        }
    }

    // Mark for deletion to reclaim visual space
    element->deleteLater();
    element = nullptr;
}

}  // namespace

//------------------------------------------------------------------------------
// !Class Management
//------------------------------------------------------------------------------

/**
 * @brief Standard constructor.
 *
 * @param parent Owning Qt widget (default: nullptr)
 */
MainWindow::MainWindow(QWidget* parent)
    : QMainWindow(parent), ui_(new Ui::MainWindow) {
    ui_->setupUi(this);
    this->setMinimumSize(this->minimumSizeHint());  // enforce minimum size

    // Runtime checks
    CheckWslEnvironment();

    // GUI configuration
    ConfigureUi();
    InitializeThreads();
    InitializeFeedbackElementMap();

    // Component auto-connect
    auto reply = QMessageBox::question(nullptr, "LIBRA App Startup",
                                       "Automatically connect all components?",
                                       QMessageBox::Yes | QMessageBox::No);
    if (reply == QMessageBox::Yes) {
        ui_->a_connect_all->trigger();
    } else {
        // Even if auto-connect was refused, some UI elements should be populated
        ui_->a_refresh_camera_list->trigger();
    }
}

/**
 * @brief Standard destructor.
 */
MainWindow::~MainWindow() {
    // Define a lambda for gracefully wrapping up worker thread(s)
    auto StopThread = [](QThread* thread) {
        if (thread != nullptr && thread->isRunning()) {
            thread->disconnect();           // kill any further communication
            thread->requestInterruption();  // signal thread to stop looping
            thread->wait();                 // wait for thread cleanup to finish
        }
    };

    // Cleanup
    StopThread(log_thread_);
    StopThread(arduino_thread_);
    StopThread(hebi_thread_);
#if LIBRA_VERSION == 2
    StopThread(epos_thread_);
#endif

    disconnect();  // all MainWindow-related signals and slots, just in case

    delete ui_;
}

//------------------------------------------------------------------------------
// !Class Helpers
//------------------------------------------------------------------------------

/**
 * @brief Based on LIBRA version, disables unneeded widgets and connects those
 *        with complementary functions.
 *
 * @note Only used in constructor - placed in own function to improve readability.
 */
void MainWindow::ConfigureUi() {
    ui_->a_debug_mode->setChecked(debug_mode_);

    // Set LIBRA_VERSION label
    QString ver_text =
        "<span style='color: rgba(0, 0, 0, 0.6);'>LIBRA_VERSION = ";
#ifdef LIBRA_VERSION
    ver_text += QString("<b>%1</b>").arg(LIBRA_VERSION);
#else
    ver_text += "<b>Unsupported</b>";
#endif
    ver_text += "</span>";
    ui_->static_l_libraversion->setText(ver_text);

    // Set BUILD_WITH_ROS2 label
    QString ros2en_text =
        "<span style='color: rgba(0, 0, 0, 0.6);'>BUILD_WITH_ROS2 = ";
#ifdef BUILD_WITH_ROS2
    ros2en_text += "<b style='color: green;'>ON</b>";
#else
    ros2en_text += "<b style='color: red;'>OFF</b>";
#endif
    ros2en_text += "</span>";
    ui_->static_l_ros2enabled->setText(ros2en_text);

    // ========== Menu Bar ==========

    // Unneeded menus/actions
#if LIBRA_VERSION != 1
    ui_->m_serial_servo->setEnabled(false);
#elif LIBRA_VERSION != 2
    ui_->m_epos->setEnabled(false);
#endif

    // Slots
    //   (none)

    // ========== Water ==========

    // Unneeded widgets
#if LIBRA_VERSION != 1
    RemoveUiElement(ui_->vl_counterweight_2);
    RemoveUiElement(ui_->pb_water_fill_2);
    RemoveUiElement(ui_->pb_water_drain_2);
#endif

    // Slots
    //   (none)

    // ========== Arm ==========

    // Unneeded widgets
#if LIBRA_VERSION != 1
    RemoveUiElement(ui_->gl_roll_input);
    RemoveUiElement(ui_->gl_roll_output);

    RemoveUiElement(ui_->gl_j1_input);
    RemoveUiElement(ui_->gl_j1_output);

    RemoveUiElement(ui_->gl_j2_input);
    RemoveUiElement(ui_->gl_j2_output);

    RemoveUiElement(ui_->gl_j3_input);
    RemoveUiElement(ui_->gl_j3_output);
#elif LIBRA_VERSION != 2
    RemoveUiElement(ui_->gl_yaw_input);
    RemoveUiElement(ui_->gl_yaw_output);

    RemoveUiElement(ui_->l_epos_status);
#endif

    // Slots
    connect(ui_->hs_arm_pitch, &QAbstractSlider::sliderMoved,  // when moved
            ui_->sb_arm_pitch, &QDoubleSpinBox::setValue);     // update display
    connect(ui_->sb_arm_pitch, &QDoubleSpinBox::valueChanged,  // when changed
            ui_->hs_arm_pitch, &QAbstractSlider::setValue);    // update slider

#if LIBRA_VERSION != 1
    connect(ui_->hs_arm_yaw, &QAbstractSlider::sliderMoved,  // "
            ui_->sb_arm_yaw, &QDoubleSpinBox::setValue);
    connect(ui_->sb_arm_yaw, &QDoubleSpinBox::valueChanged,  // "
            ui_->hs_arm_yaw, &QAbstractSlider::setValue);
#elif LIBRA_VERSION != 2
    connect(ui_->hs_arm_roll, &QAbstractSlider::sliderMoved,  // "
            ui_->sb_arm_roll, &QDoubleSpinBox::setValue);
    connect(ui_->sb_arm_roll, &QDoubleSpinBox::valueChanged,  // "
            ui_->hs_arm_roll, &QAbstractSlider::setValue);

    connect(ui_->hs_arm_j1, &QAbstractSlider::sliderMoved,  // "
            ui_->sb_arm_j1, &QDoubleSpinBox::setValue);
    connect(ui_->sb_arm_j1, &QDoubleSpinBox::valueChanged,  // "
            ui_->hs_arm_j1, &QAbstractSlider::setValue);

    connect(ui_->hs_arm_j2, &QAbstractSlider::sliderMoved,  // "
            ui_->sb_arm_j2, &QDoubleSpinBox::setValue);
    connect(ui_->sb_arm_j2, &QDoubleSpinBox::valueChanged,  // "
            ui_->hs_arm_j2, &QAbstractSlider::setValue);

    connect(ui_->hs_arm_j3, &QAbstractSlider::sliderMoved,  // "
            ui_->sb_arm_j3, &QDoubleSpinBox::setValue);
    connect(ui_->sb_arm_j3, &QDoubleSpinBox::valueChanged,  // "
            ui_->hs_arm_j3, &QAbstractSlider::setValue);
#endif

    // ========== Camera ==========

    connect(ui_->pb_camera_refresh, &QPushButton::clicked,     // when clicked
            ui_->a_refresh_camera_list, &QAction::triggered);  // refresh list
}

/**
 * @brief Sets up signal and slot connections to child threads and spins them up.
 *
 * @note In Qt, thread management for subclassed QThreads generally has 4 steps:
 *   1) Initialize a new QThread object as a child of MainWindow
 *   2) Register its signals and slots to send/receive data to/from MainWindow
 *   3) Register its exit signal to its own destruction slot
 *   4) Spin it off
 * If the thread loops continuously, there is a fifth step:
 *   5) In the MainWindow destructor, interrupt or forcibly stop the QThread
 *
 * @note Only used in constructor - placed in own function to improve readability.
 */
void MainWindow::InitializeThreads() {
    // ========== Log Thread ==========

    /*
    log_thread_ = new LogThread(this, debug_mode_);

    // MainWindow signals
    connect(this, &MainWindow::EnableDebugMode,  // update debug mode
            log_thread_, &LogThread::SetDebugMode);

    connect(ui_->pb_logshot, &QPushButton::clicked,  // log snapshot
            log_thread_, &LogThread::TakeLogShot);

    // Thread cleanup
    connect(log_thread_, &LogThread::finished,      // when thread exits
            log_thread_, &LogThread::deleteLater);  // deallocate

    log_thread_->start();
    */

    // ========== Arduino Thread ==========

    arduino_thread_ = new ArduinoThread(this, debug_mode_);

    // MainWindow signals
    connect(this, &MainWindow::EnableDebugMode,  // update debug mode
            arduino_thread_, &ArduinoThread::SetDebugMode);

#if LIBRA_VERSION == 1
    connect(ui_->a_manip_disconnect, &QAction::triggered,  // disconnect servos
            arduino_thread_, &ArduinoThread::DisconnectManip);

    connect(this, &MainWindow::CommandManip,  // update manip target(s)
            arduino_thread_, &ArduinoThread::SetManipCommand);
#endif

    connect(ui_->a_water_disconnect, &QAction::triggered,  // disconnect water
            arduino_thread_, &ArduinoThread::DisconnectWater);

    connect(this, &MainWindow::EnableFluidSystem,  // change water state
            arduino_thread_, &ArduinoThread::SetWaterState);
    connect(this, &MainWindow::CommandWater,  // force update water command
            arduino_thread_, &ArduinoThread::SetWaterCommand);

    // MainWindow slots
#if LIBRA_VERSION == 1
    connect(ui_->a_manip_connect, &QAction::triggered,  // connect to servos
            this, &MainWindow::ConnectManipHelper);
    connect(arduino_thread_, &ArduinoThread::ManipConnected,  // update UI
            this, &MainWindow::HandleManipConnChanged);
    connect(arduino_thread_, &ArduinoThread::ReportPosition,  // get position
            this, &MainWindow::HandleManipPosition);
#endif

    connect(ui_->a_water_connect, &QAction::triggered,  // connect to water
            this, &MainWindow::ConnectWaterHelper);
    connect(arduino_thread_, &ArduinoThread::WaterConnected,  // update UI
            this, &MainWindow::HandleWaterConnChanged);
    connect(arduino_thread_, &ArduinoThread::ReportWaterStatus,  // get state
            this, &MainWindow::HandleWaterStatus);

    connect(arduino_thread_, &ArduinoThread::ErrorThrown,  // handle errors
            this, &MainWindow::HandleCriticalError);

    // Thread cleanup
    connect(arduino_thread_, &ArduinoThread::finished,      // when thread exits
            arduino_thread_, &ArduinoThread::deleteLater);  // deallocate

    arduino_thread_->start();

    // ========== HEBI Thread ==========

    hebi_thread_ = new HebiThread(this, {"LIBRA"},
#if LIBRA_VERSION == 1
                                  {"MA", "MB", "J1", "J2", "J3"},
#elif LIBRA_VERSION == 2
                                  {"Pitch"},
#endif
                                  debug_mode_);

    // MainWindow signals
    connect(this, &MainWindow::EnableDebugMode,  // update debug mode
            hebi_thread_, &HebiThread::SetDebugMode);
    connect(this, &MainWindow::EnableAutoTorqueComp,  // update auto control
            hebi_thread_, &HebiThread::SetAutoTorqueComp);

    connect(ui_->a_hebi_connect, &QAction::triggered,  // connect to HEBI
            hebi_thread_, &HebiThread::Connect);
    connect(ui_->a_hebi_disconnect, &QAction::triggered,  // disconnect HEBI
            hebi_thread_, &HebiThread::Disconnect);

    connect(this, &MainWindow::CommandHebi,  // update HEBI target(s)
            hebi_thread_, &HebiThread::SetTarget);
    connect(ui_->pb_arm_stop, &QPushButton::clicked,  // stop ALL actuators
            hebi_thread_, &HebiThread::Stop);

    // MainWindow slots
    connect(hebi_thread_, &HebiThread::Connected,  // update UI
            this, &MainWindow::HandleHebiConnChanged);

    connect(hebi_thread_, &HebiThread::ReportFeedback,  // get feedback
            this, &MainWindow::HandleActuatorFeedback);
    connect(hebi_thread_, &HebiThread::ReportStatus,  // get minor statuses
            this, &MainWindow::HandleActuatorStatus);

    connect(hebi_thread_, &HebiThread::ErrorThrown,  // handle errors
            this, &MainWindow::HandleCriticalError);

    // ArduinoThread slots
    connect(hebi_thread_, &HebiThread::ReportArmTorque,  // update water command
            arduino_thread_, &ArduinoThread::SetWaterCommand);

    // Thread cleanup
    connect(hebi_thread_, &HebiThread::finished,      // when thread exits
            hebi_thread_, &HebiThread::deleteLater);  // deallocate

    hebi_thread_->start();

    // ========== EPOS Thread ==========

#if LIBRA_VERSION == 2
    epos_thread_ = new EposThread(this, "EPOS4", "MAXON SERIAL V2", "USB",
                                  "USB0", 1000000, debug_mode_);

    // MainWindow signals
    connect(this, &MainWindow::EnableDebugMode,  // update debug mode
            epos_thread_, &EposThread::SetDebugMode);

    connect(ui_->a_epos_connect, &QAction::triggered,  // connect to EPOS
            epos_thread_, &EposThread::Connect);
    connect(ui_->a_epos_disconnect, &QAction::triggered,  // disconnect EPOS
            epos_thread_, &EposThread::Disconnect);

    connect(this, &MainWindow::CommandEpos,  // update EPOS target(s)
            epos_thread_, &EposThread::SetTarget);
    connect(ui_->pb_arm_stop, &QPushButton::clicked,  // stop ALL actuators
            epos_thread_, &EposThread::Stop);

    // MainWindow slots
    connect(epos_thread_, &EposThread::Connected,  // update UI
            this, &MainWindow::HandleEposConnChanged);

    connect(epos_thread_, &EposThread::ReportFeedback,  // get feedback
            this, &MainWindow::HandleActuatorFeedback);
    connect(epos_thread_, &EposThread::ReportStatus,  // get minor statuses
            this, &MainWindow::HandleActuatorStatus);

    connect(epos_thread_, &EposThread::ErrorThrown,  // handle errors
            this, &MainWindow::HandleCriticalError);

    // Thread cleanup
    connect(epos_thread_, &EposThread::finished,      // when thread exits
            epos_thread_, &EposThread::deleteLater);  // deallocate

    epos_thread_->start();
#endif
}

/**
 * @brief Populates a map-of-maps with UI label elements, according to their
 *        corresponding joint names (`Joint`) and feedback types
 *        (`Actuator::Feedback`).
 *
 * @note Only used in constructor - placed in own function to improve readability.
 *
 * @see Joint::Name Actuator::Feedback
 */
void MainWindow::InitializeFeedbackElementMap() {
    // Central joint
#if LIBRA_VERSION == 1
    feedback_element_map_[Joint::kRoll][Actuator::Feedback::kTargetPos] =
        ui_->l_target_roll;
    feedback_element_map_[Joint::kRoll][Actuator::Feedback::kActualPos] =
        ui_->l_actual_roll;
    feedback_element_map_[Joint::kRoll][Actuator::Feedback::kActualTorque] =
        ui_->l_torque_roll;
#elif LIBRA_VERSION == 2
    feedback_element_map_[Joint::kYaw][Actuator::Feedback::kTargetPos] =
        ui_->l_target_yaw;
    feedback_element_map_[Joint::kYaw][Actuator::Feedback::kActualPos] =
        ui_->l_actual_yaw;
    feedback_element_map_[Joint::kYaw][Actuator::Feedback::kActualTorque] =
        ui_->l_torque_yaw;
#endif

    feedback_element_map_[Joint::kPitch][Actuator::Feedback::kTargetPos] =
        ui_->l_target_pitch;
    feedback_element_map_[Joint::kPitch][Actuator::Feedback::kActualPos] =
        ui_->l_actual_pitch;
    feedback_element_map_[Joint::kPitch][Actuator::Feedback::kActualTorque] =
        ui_->l_torque_pitch;

    // Arm
#if LIBRA_VERSION == 1
    feedback_element_map_[Joint::kJ1][Actuator::Feedback::kTargetPos] =
        ui_->l_target_j1;
    feedback_element_map_[Joint::kJ1][Actuator::Feedback::kActualPos] =
        ui_->l_actual_j1;
    feedback_element_map_[Joint::kJ1][Actuator::Feedback::kActualTorque] =
        ui_->l_torque_j1;

    feedback_element_map_[Joint::kJ2][Actuator::Feedback::kTargetPos] =
        ui_->l_target_j2;
    feedback_element_map_[Joint::kJ2][Actuator::Feedback::kActualPos] =
        ui_->l_actual_j2;
    feedback_element_map_[Joint::kJ2][Actuator::Feedback::kActualTorque] =
        ui_->l_torque_j2;

    feedback_element_map_[Joint::kJ3][Actuator::Feedback::kTargetPos] =
        ui_->l_target_j3;
    feedback_element_map_[Joint::kJ3][Actuator::Feedback::kActualPos] =
        ui_->l_actual_j3;
    feedback_element_map_[Joint::kJ3][Actuator::Feedback::kActualTorque] =
        ui_->l_torque_j3;
#endif
}

#if LIBRA_VERSION == 1
/**
 * @brief Allows user to select a physical serial device and commands
 *        ArduinoThread to connect to it as the "SerialServo" device.
 */
void MainWindow::ConnectManipHelper() {
    // Prompt user to select a serial device
    OpenSerialDialog open_port_dlg(this, QString("SerialServo"));
    QString port_name;

    if (open_port_dlg.exec() == QDialog::Accepted) {
        port_name = open_port_dlg.GetSelectedPortName();

        if (port_name.isEmpty()) {
            qCritical("No port selected!");
            return;
        }
    } else {
        qDebug("Port selection cancelled by user");
        return;
    }

    emit arduino_thread_->ConnectManip(port_name);
}
#endif

/**
 * @brief Allows user to select a physical serial device and commands
 *        ArduinoThread to connect to it as the "SerialWater" device.
 */
void MainWindow::ConnectWaterHelper() {
    // Prompt user to select a serial device
    OpenSerialDialog open_port_dlg(this, QString("SerialWater"));
    QString port_name;

    if (open_port_dlg.exec() == QDialog::Accepted) {
        port_name = open_port_dlg.GetSelectedPortName();

        if (port_name.isEmpty()) {
            qCritical("No port selected!");
            return;
        }
    } else {
        qDebug("Port selection cancelled by user");
        return;
    }

    emit arduino_thread_->ConnectWater(port_name);
}

//------------------------------------------------------------------------------
// !Thread Handlers (Slots)
//------------------------------------------------------------------------------

#if LIBRA_VERSION == 1
/**
 * @brief Reflects SerialServo connection status in UI.
 */
void MainWindow::HandleManipConnChanged(const bool& connected) {
    if (connected) {
        ui_->a_manip_connect->setEnabled(false);
        ui_->a_manip_disconnect->setEnabled(true);
        ui_->pb_manip_slow->setEnabled(true);
        ui_->pb_manip_fast->setEnabled(true);
    } else {
        ui_->a_manip_connect->setEnabled(true);
        ui_->a_manip_disconnect->setEnabled(false);
        ui_->pb_manip_slow->setEnabled(false);
        ui_->pb_manip_fast->setEnabled(false);
    }
}

/**
 * @brief Sorts important actuator information into individual UI elements.
 *
 * @param base Position of the pitch-correction servo.
 * @param pan Position of the manipulator yaw servo.
 * @param tilt Position of the manipulator pitch servo.
 */
void MainWindow::HandleManipPosition(const double& base, const double& pan,
                                     const double& tilt) {
    ui_->l_actual_manip_base->setText(QString::number(base, 'f', 1));  // 0.1
    ui_->l_actual_manip_pan->setText(QString::number(pan, 'f', 1));
    ui_->l_actual_manip_tilt->setText(QString::number(tilt, 'f', 1));
}
#endif

/**
 * @brief Reflects SerialWater connection status in UI.
 */
void MainWindow::HandleWaterConnChanged(const bool& connected) {
    ui_->a_water_connect->setEnabled(!connected);
    ui_->a_water_disconnect->setEnabled(connected);

    ui_->pb_water_enable->setEnabled(connected);

    ui_->pb_water_fill_1->setEnabled(connected);
    ui_->pb_water_drain_1->setEnabled(connected);
#if LIBRA_VERSION == 1
    ui_->pb_water_fill_2->setEnabled(connected);
    ui_->pb_water_drain_2->setEnabled(connected);
#endif
}

/**
 * @brief Reflects fluid system status in UI.
 *        - Primary visual feedback: formatted status string in "WATER" GroupBox
 *        - Secondary visual feedback: updates TankWidget(s) animation state
 *
 * @param side The side of the fluid system
 * @param state The flow state of the fluid system
 */
void MainWindow::HandleWaterStatus(const Water::Side& side,
                                   const Water::State& state) {
    // Display formatted status string - primary visual feedback
    switch (side) {
        case Water::Side::kA:
            ui_->l_water1_status->setText(Water::StateEnumToString(state));
            ui_->tw_fill_level_1->UpdateState(state);
            break;
#if LIBRA_VERSION == 1
        case Water::Side::kB:
            ui_->l_water2_status->setText(Water::StateEnumToString(state));
            ui_->tw_fill_level_2->UpdateState(state);
            break;
#endif
        default:
            // Shouldn't be able to get here
            qCritical() << "[ERROR] Received status for unknown fluid system "
                           "side: Water::Side("
                        << std::to_string(static_cast<int>(side)) << ")";
    }

    // Pass along to TankWidget(s) - secondary visual feedback
}

/**
 * @brief Reflects HEBI actuator connection status in UI.
 */
void MainWindow::HandleHebiConnChanged(const bool& connected) {
    ui_->a_hebi_connect->setEnabled(!connected);
    ui_->a_hebi_disconnect->setEnabled(connected);

    ui_->pb_arm_start->setEnabled(connected);
    if (connected) {
        // NOTE: It is possible for multiple actuator types -- and, by
        //       extension, multiple HandleXConnChanged() calls -- to exist.
        //       Therefore, the "STOP" PushButton should only ever be enabled
        //       by such calls, since other actuators may still be connected.
        ui_->pb_arm_stop->setEnabled(connected);
    }
}

#if LIBRA_VERSION == 2
/**
 * @brief Reflects EPOS (Maxon) actuator connection status in UI.
 */
void MainWindow::HandleEposConnChanged(const bool& connected) {
    ui_->a_epos_connect->setEnabled(!connected);
    ui_->a_epos_disconnect->setEnabled(connected);

    ui_->pb_arm_start->setEnabled(connected);
    if (connected) {
        // NOTE: It is possible for multiple actuator types -- and, by
        //       extension, multiple HandleXConnChanged() calls -- to exist.
        //       Therefore, the "STOP" PushButton should only ever be enabled
        //       by such calls, since other actuators may still be connected.
        ui_->pb_arm_stop->setEnabled(connected);
    }
}
#endif

/**
 * @brief Sorts important actuator information into individual UI elements.
 *
 * @param feedbacks Unordered map of joint(s) and their corresponding feedback
 * @param feedback_type The type of primary feedback provided
 */
void MainWindow::HandleActuatorFeedback(
    const std::unordered_map<Actuator::Name, double>& feedbacks,
    const Actuator::Feedback feedback_type) {
    // Handle complex joints first
#if LIBRA_VERSION == 1
    // Special Case: MA and MB differential drive -> Roll and Pitch
    const auto ma = feedbacks.find(Actuator::Name::kMA);
    const auto mb = feedbacks.find(Actuator::Name::kMB);

    if (ma != feedbacks.end() && mb != feedbacks.end()) {
        const double ma_val = ma->second;
        const double mb_val = mb->second;

        /*
         * From our forward mapping at the `emit CommandHebi()` call:
         *   MA = -roll - pitch
         *   MB = -roll + pitch
         * Combine the equations and solve:
         *   MA + MB = -2 * roll    ->   roll  = -(MA + MB) / 2
         *   MA - MB = -2 * pitch   ->   pitch = -(MA - MB) / 2
         */
        feedback_element_map_.at(Joint::kRoll)
            .at(feedback_type)
            ->setText(
                QString::number(-(ma_val + mb_val) / 2.0, 'f', kPrecision));

        feedback_element_map_.at(Joint::kPitch)
            .at(feedback_type)
            ->setText(
                QString::number(-(ma_val - mb_val) / 2.0, 'f', kPrecision));
    }
#endif

    // Handle regular 1-DoF joints
    for (const auto& feedback : feedbacks) {
#if LIBRA_VERSION == 1
        // Skip special cases (already processed)
        if (feedback.first == Actuator::Name::kMA
            || feedback.first == Actuator::Name::kMB) {
            continue;
        }
#endif
        try {
            // Index into relevant UI label using the map-of-maps initialized
            // in the constructor (we can static cast Actuator::Name to Joint
            // for 1:1 cases)
            feedback_element_map_.at(static_cast<Joint>(feedback.first))
                .at(feedback_type)
                ->setText(QString::number(feedback.second, 'f', kPrecision));
        } catch (const std::out_of_range&) {
            qCritical() << "[ERROR] No UI element mapped to joint"
                        << feedback.first << "and feedback type"
                        << feedback_type;
        }
    }
}

/**
 * @brief Prints miscellaneous actuator information at the bottom of the UI.
 *
 * @param status Newline-delimited status info
 * @param type The actuator type, for updating the corresponding UI element
 */
void MainWindow::HandleActuatorStatus(const QString& status,
                                      const Actuator::Type type) {
    switch (type) {
        case Actuator::Type::kHebi:
            ui_->l_hebi_status->setText(status);
            break;
#if LIBRA_VERSION == 2
        case Actuator::Type::kEpos:
            ui_->l_epos_status->setText(status);
            break;
#endif
        default:
            // Shouldn't be able to get here
            qCritical() << "[ERROR] Received status from unknown actuator type:"
                        << type;
    }
}

/**
 * @brief Throws a pop-up error box upon receiving an error signal from a thread.
 *
 * @param err Fatal error message from a component
 */
void MainWindow::HandleCriticalError(const QString& err) {
    QMessageBox::critical(this, tr("Error"), err);
}

//------------------------------------------------------------------------------
// !Menu Bar
//------------------------------------------------------------------------------

/**
 * @brief Event handler for "Preferences" menu action "Debug Mode".
 *        Toggles debug prinouts for this object and all its children.
 */
void MainWindow::on_a_debug_mode_toggled(bool checked) {
    debug_mode_ = checked;

    if (debug_mode_) {
        qDebug() << "[DEBUG] Debug mode enabled";
    }

    // Propagate to all children
    emit EnableDebugMode(checked);
}

/**
 * @brief Event handler for "Sensors/RealSense" menu action "Refresh Camera
 *        List". Populates the "Camera" tab's ComboBox with all detected cameras.
 */
void MainWindow::on_a_refresh_camera_list_triggered() {
    qDebug() << "[INFO] Checking available video inputs...";

    ui_->cb_camera_id->clear();  // existing list may be stale

    const auto cameras = QMediaDevices::videoInputs();
    for (const auto& camera_device : cameras) {
        auto id = QString(camera_device.id());

        if (debug_mode_) {
            qDebug() << "[DEBUG] Found camera at " << camera_device.id();
        }

        // Populate ComboBox
        ui_->cb_camera_id->addItem(id);

        // Populate internal map (used on ComboBox change)
        available_cameras_[id] = camera_device.description();
    }

    if (!available_cameras_.empty()) {
        ui_->pb_camera_capture->setEnabled(true);
        ui_->pb_camera_record->setEnabled(true);
    } else if (debug_mode_) {
        qDebug() << "[DEBUG] No cameras were found";
    }
}

/**
 * @brief Event handler for "Sensors/2D LIDAR" menu action "About".
 *        Opens a dialog box with sensor metadata, if connected.
 */
void MainWindow::on_a_lidar_about_triggered() {
    qDebug() << "[WARN] 2D LIDAR \"About\" not yet implemented";

    // TODO: spinning LIDAR implementation
}

/**
 * @brief Event handler for "Water/Advanced" menu action "Set empty (0%)".
 *        Forces the tank (water bladder) visualization to show as empty.
 *
 * @note Only use if there is a discrepancy with the physical water bladders.
 */
void MainWindow::on_a_water_set_empty_triggered() {
    ui_->tw_fill_level_1->OverrideLevel(0.0);
#if LIBRA_VERSION == 1
    ui_->tw_fill_level_2->OverrideLevel(0.0);
#endif
}

/**
 * @brief Event handler for "Water/Advanced" menu action "Set full (100%)".
 *        Forces the tank (water bladder) visualization to show as full.
 *
 * @note Only use if there is a discrepancy with the physical water bladders.
 */
void MainWindow::on_a_water_set_full_triggered() {
    ui_->tw_fill_level_1->OverrideLevel(1.0);
#if LIBRA_VERSION == 1
    ui_->tw_fill_level_2->OverrideLevel(1.0);
#endif
}

/**
 * @brief Event handler for "Quick Actions" menu action "Connect All".
 *        Connects all peripheral devices (actuators, sensors, etc.).
 */
void MainWindow::on_a_connect_all_triggered() {
    // Arduinos
#if LIBRA_VERSION == 1
    ConnectManipHelper();
#endif
    ConnectWaterHelper();

    // Actuators
    ui_->a_hebi_connect->trigger();
#if LIBRA_VERSION == 2
    ui_->a_epos_connect->trigger();
#endif

    // Sensors
    ui_->a_refresh_camera_list->trigger();
    ui_->a_lidar_connect->trigger();
}

/**
 * @brief Event handler for "Quick Actions" menu action "Disconnect All".
 *        Disconnects all peripheral devices (actuators, sensors, etc.).
 */
void MainWindow::on_a_disconnect_all_triggered() {
    // Arduinos
#if LIBRA_VERSION == 1
    emit arduino_thread_->DisconnectManip();
#endif
    emit arduino_thread_->DisconnectWater();

    // Actuators
    ui_->a_hebi_disconnect->trigger();
#if LIBRA_VERSION == 2
    ui_->a_epos_disconnect->trigger();
#endif

    // Sensors
    ui_->a_lidar_disconnect->trigger();
}

//------------------------------------------------------------------------------
// !Main Window
//------------------------------------------------------------------------------

//------------------------------------------------------------------------------
// !Arm
//------------------------------------------------------------------------------

/**
 * @brief Send movement command signal to all actuators.
 */
void MainWindow::on_pb_arm_start_clicked() {
#if LIBRA_VERSION == 1
    // Roll and Pitch are controlled by actuators MA and MB via differential drive
    // TODO: confirm this
    auto val_ma = (-ui_->sb_arm_roll->value() - ui_->sb_arm_pitch->value());
    auto val_mb = (-ui_->sb_arm_roll->value() + ui_->sb_arm_pitch->value());

    // To improve ease of use, arm actuator angles in the UI are shown
    // relative to a perspective directly behind the robot, where 0 is
    // directly forward. Adjust for actual J1, J2 and J3 angles here
    // TODO: confirm this
    auto val_j1 = ui_->sb_arm_j1->value();
    auto val_j2 = -ui_->sb_arm_j2->value();
    auto val_j3 = ui_->sb_arm_j3->value();

    emit CommandHebi({val_ma, val_mb, val_j1, val_j2, val_j3});
#elif LIBRA_VERSION == 2
    emit CommandEpos({ui_->sb_arm_yaw->value()});
    emit CommandHebi({ui_->sb_arm_pitch->value()});
#endif
}

//------------------------------------------------------------------------------
// !Manipulator
//------------------------------------------------------------------------------

#if LIBRA_VERSION == 1
/**
 * @brief Moves manipulator servos at a leisurely pace.
 */
void MainWindow::on_pb_manip_slow_clicked() {
    emit CommandManip(ui_->sb_arm_j3->value(), ui_->sb_manip_pan->value(),
                      ui_->sb_manip_tilt->value(), kManipMoveSlow);
}

/**
 * @brief Moves manipulator servos at maximum speed (near-instant).
 */
void MainWindow::on_pb_manip_fast_clicked() {
    emit CommandManip(ui_->sb_arm_j3->value(), ui_->sb_manip_pan->value(),
                      ui_->sb_manip_tilt->value(), kManipMoveFast);
}
#endif

//------------------------------------------------------------------------------
// !Water
//------------------------------------------------------------------------------

/**
 * @brief Enable/disable fluid system operation (and, by association, automatic
 *        torque control of the central arm joint).
 *
 * @param checked Whether the fluid system is being enabled or disabled
 */
void MainWindow::on_pb_water_enable_toggled(bool checked) {
    emit EnableFluidSystem(checked);
    emit EnableAutoTorqueComp(checked);

    if (checked) {
        // Clearly display an "enabled" state
        ui_->pb_camera_record->setStyleSheet("color: red;");
        ui_->pb_camera_record->setText("DISABLE");
    } else {
        // Revert to "disabled" state
        ui_->pb_camera_record->setStyleSheet("color: black;");
        ui_->pb_camera_record->setText("ENABLE");
    }
}

/**
 * @brief Force-drain the counterweight(s).
 */
void MainWindow::on_pb_water_drain_clicked() {
    emit EnableFluidSystem(true);
    emit CommandWater(ArduinoThread::kDrain);
}

//------------------------------------------------------------------------------
// !Camera
//------------------------------------------------------------------------------

/**
 * @brief Connects to the selected camera feed.
 */
void MainWindow::on_cb_camera_id_currentTextChanged(const QString& sel) {
    if (camera_manager_ != nullptr) {
        if (debug_mode_) {
            qDebug() << "[DEBUG] Resetting existing camera manager";
        }
        camera_manager_.reset();
    }

    // Show human-readable camera name
    ui_->l_camera_name->setText(available_cameras_[sel]);

    // Open a connection to the camera
    camera_manager_ = std::make_unique<CameraManager>(sel,
                                                      ui_->vw_camera_viewfinder,
                                                      this);
    camera_manager_->Start();

    // Reflect changes in UI
    ui_->pb_camera_capture->setEnabled(true);
    ui_->pb_camera_record->setEnabled(true);
}

/**
 * @brief Captures a still image from the active camera feed.
 */
void MainWindow::on_pb_camera_capture_clicked() {
    camera_manager_->Capture();

    // Display a status tip at the bottom of the UI
    statusBar()->showMessage("Saved capture to img/ directory!", kInfoLifespan);
}

/**
 * @brief Toggles video recording from the active camera feed.
 */
void MainWindow::on_pb_camera_record_clicked() {
    if (camera_manager_->Record()) {
        // Clearly display a "recording" state
        ui_->pb_camera_record->setStyleSheet("color: red;");
        ui_->pb_camera_record->setText("STOP");
    } else {
        // Display a status tip at the bottom of the UI
        statusBar()->showMessage("Saved recording to vid/ directory!",
                                 kInfoLifespan);

        // Revert to original state
        ui_->pb_camera_record->setStyleSheet("color: black;");
        ui_->pb_camera_record->setText("RECORD");
    }
}

//------------------------------------------------------------------------------
// !Misc.
//------------------------------------------------------------------------------

//------------------------------------------------------------------------------
// !Uncategorized
//------------------------------------------------------------------------------
