/******************************************************************************
 * @file   main_window.cpp
 * @brief  Main app window implementation file.
 *
 * @author brice.c.aa
 ******************************************************************************/

// Related Header
#include "main_window.h"

// C++ Standard Library Headers
#include <filesystem>
#include <iostream>
#include <sys/stat.h>

// Other Library Headers
#include <QDateTime>        // Qt::Core
#include <QMessageBox>      // Qt::Widgets
#include <QSerialPortInfo>  // Qt::SerialPort

// Project Headers
#include "ui_main_window.h"  // auto-generated by Qt

/* --- TABLE OF CONTENTS ---
 * !Helper Functions
 * !Thread Handlers (Slots)
 * !Menu Bar
 * !Main Window
 * !Arm
 * !Manipulator
 * !Pump
 * !Camera
 * !Misc.
 * !Uncategorized
 */

/* Constants */

constexpr int kInfoLifespan = 4000;  // 4s timer for non-hover status tips

/**
 * @brief Standard constructor.
 *
 * @param parent Owning Qt widget (default: nullptr)
 */
MainWindow::MainWindow(QWidget* parent)
    : QMainWindow(parent),
      ui_(new Ui::MainWindow),
      ser_water_(new QSerialPort(this)),
      ser_servo_(new QSerialPort(this)) {
    ui_->setupUi(this);

    // Set UI elements
    ui_->a_debug_mode->setChecked(debug_mode_);

    // Check if app is running in Windows Subsystem for Linux (WSL2)
    {
        const char* wsl_path = "/run/WSL";

        struct stat buf {};

        if (stat(wsl_path, &buf) == 0 && S_ISDIR(buf.st_mode)) {
            qWarning()
                << "[WARN] You seem to be running this on WSL2. Please ensure "
                   "you have properly forwarded your USB connections.";
        }
    }

    // --- Slot Management (non-thread) ---

    // Arm
    connect(ui_->hs_arm_yaw, &QAbstractSlider::sliderMoved,  // when moved
            ui_->sb_arm_yaw, &QDoubleSpinBox::setValue);     // update display
    connect(ui_->sb_arm_yaw, &QDoubleSpinBox::valueChanged,  // when changed
            ui_->hs_arm_yaw, &QAbstractSlider::setValue);    // update slider

    connect(ui_->hs_arm_pitch, &QAbstractSlider::sliderMoved,  // when moved
            ui_->sb_arm_pitch, &QDoubleSpinBox::setValue);     // update display
    connect(ui_->sb_arm_pitch, &QDoubleSpinBox::valueChanged,  // when changed
            ui_->hs_arm_pitch, &QAbstractSlider::setValue);    // update slider

    // Pump (FOR TESTING PURPOSES ONLY)
    connect(ui_->pb_pump_enable, &QPushButton::clicked,  // when clicked
            ui_->w_tank_visual, &TankWidget::Fill);      // start filling

    connect(ui_->pb_pump_disable, &QPushButton::clicked,  // when clicked
            ui_->w_tank_visual, &TankWidget::Stop);       // stop filling

    connect(ui_->pb_pump_drain, &QPushButton::clicked,  // when clicked
            ui_->w_tank_visual, &TankWidget::Drain);    // force drain

    // --- Thread Management ---

    /* In Qt, thread management for subclassed QThreads generally has 4 steps:
     *   1) Initialize a new QThread object
     *   2) Register a QThread signal to return data to a MainWindow handler
     *   3) Register the QThread's exit signal to its own destruction slot
     *   4) Spin off the QThread
     * If the thread loops continuously, there is a fifth step:
     *   5) In the MainWindow destructor, interrupt or forcibly stop the QThread
     */

    // Log thread
    log_thread_ = new LogThread(this, debug_mode_);

    // - MainWindow signals
    connect(this, &MainWindow::UpdateDebugMode,  // update debug mode
            log_thread_, &LogThread::SetDebugMode);

    connect(ui_->pb_logshot, &QPushButton::clicked,  // log snapshot
            log_thread_, &LogThread::TakeLogShot);

    // - MainWindow slots
    // TODO: implementation

    log_thread_->start();

    // EPOS thread
    epos_thread_ = new EposThread(this, "EPOS4", "MAXON SERIAL V2", "USB",
                                  "USB0", 1000000, debug_mode_);

    // - MainWindow signals
    connect(this, &MainWindow::UpdateDebugMode,  // update debug mode
            epos_thread_, &EposThread::SetDebugMode);

    connect(ui_->a_epos_connect, &QAction::triggered,  // connect to EPOS
            epos_thread_, &EposThread::Connect);
    connect(ui_->a_epos_disconnect, &QAction::triggered,  // disconnect EPOS
            epos_thread_, &EposThread::Disconnect);

    connect(this, &MainWindow::CommandEpos,  // update EPOS target(s)
            epos_thread_, &EposThread::SetTarget);
    connect(ui_->pb_arm_stop, &QPushButton::clicked,  // stop ALL actuators
            epos_thread_, &EposThread::Stop);

    // - MainWindow slots
    connect(epos_thread_, &EposThread::ReportFeedback,  // receive feedback
            this, &MainWindow::HandleActuatorFeedback);
    connect(epos_thread_, &EposThread::ReportStatus,  // receive minor statuses
            this, &MainWindow::HandleActuatorStatus);

    connect(epos_thread_, &EposThread::ErrorThrown,  // handle error messages
            this, &MainWindow::HandleErrorMsg);

    // - Thread cleanup
    connect(epos_thread_, &EposThread::finished,      // when thread exits
            epos_thread_, &EposThread::deleteLater);  // ... deallocate

    epos_thread_->start();

    // HEBI thread
    hebi_thread_ = new HebiThread(this, {"LIBRA"}, {"Pitch"}, debug_mode_);

    // - MainWindow signals
    connect(this, &MainWindow::UpdateDebugMode,  // update debug mode
            hebi_thread_, &HebiThread::SetDebugMode);

    connect(ui_->a_hebi_connect, &QAction::triggered,  // connect to HEBI
            hebi_thread_, &HebiThread::Connect);
    connect(ui_->a_hebi_disconnect, &QAction::triggered,  // disconnect HEBI
            hebi_thread_, &HebiThread::Disconnect);

    connect(this, &MainWindow::CommandHebi,  // update HEBI target(s)
            hebi_thread_, &HebiThread::SetTarget);
    connect(ui_->pb_arm_stop, &QPushButton::clicked,  // stop ALL actuators
            hebi_thread_, &HebiThread::Stop);

    // - MainWindow slots
    connect(hebi_thread_, &HebiThread::ReportFeedback,  // receive feedback
            this, &MainWindow::HandleActuatorFeedback);
    connect(hebi_thread_, &HebiThread::ReportStatus,  // receive minor statuses
            this, &MainWindow::HandleActuatorStatus);

    connect(hebi_thread_, &HebiThread::ErrorThrown,  // handle error messages
            this, &MainWindow::HandleErrorMsg);

    // - Thread cleanup
    connect(hebi_thread_, &HebiThread::finished,      // when thread exits
            hebi_thread_, &HebiThread::deleteLater);  // ... deallocate

    hebi_thread_->start();

    // --- Component Connection ---

    InitializeFeedbackElementMap();

    auto reply = QMessageBox::question(nullptr, "LIBRA App Startup",
                                       "Automatically connect all components?",
                                       QMessageBox::Yes | QMessageBox::No);
    if (reply == QMessageBox::Yes) {
        ui_->a_connect_all->trigger();
    }
}

/**
 * @brief Standard destructor.
 */
MainWindow::~MainWindow() {
    // Wrap up the worker thread(s) gracefully
    if (log_thread_ != nullptr && log_thread_->isRunning()) {
        log_thread_->requestInterruption();  // signal thread to stop looping
        log_thread_->wait();  // wait for thread cleanup to finish
    }
    if (epos_thread_ != nullptr && epos_thread_->isRunning()) {
        epos_thread_->requestInterruption();
        epos_thread_->wait();
    }
    if (hebi_thread_ != nullptr && hebi_thread_->isRunning()) {
        hebi_thread_->requestInterruption();
        hebi_thread_->wait();
    }

    delete ui_;
}

//------------------------------------------------------------------------------
// !Helper Functions
//------------------------------------------------------------------------------

namespace {  // local to this file

}  // namespace

/**
 * @brief Populates a map-of-maps with UI label elements, according to their
 *        corresponding actuator joint names (`Actuator::Joint`) and feedback types
 *        (`Actuator::Feedback`).
 *
 * @see Actuator::Joint Actuator::Feedback
 */
void MainWindow::InitializeFeedbackElementMap() {
    // Yaw joint
    feedback_element_map_[Actuator::Joint::kYaw]
                         [Actuator::Feedback::kTargetPos] = ui_->l_target_yaw;
    feedback_element_map_[Actuator::Joint::kYaw]
                         [Actuator::Feedback::kActualPos] = ui_->l_actual_yaw;
    feedback_element_map_[Actuator::Joint::kYaw]
                         [Actuator::Feedback::kActualTorque] = ui_->l_torque_yaw;

    // Pitch joint
    feedback_element_map_[Actuator::Joint::kPitch]
                         [Actuator::Feedback::kTargetPos] = ui_->l_target_pitch;
    feedback_element_map_[Actuator::Joint::kPitch]
                         [Actuator::Feedback::kActualPos] = ui_->l_actual_pitch;
    feedback_element_map_[Actuator::Joint::kPitch]
                         [Actuator::Feedback::kActualTorque] =
                             ui_->l_torque_pitch;
}

//------------------------------------------------------------------------------
// !Thread Handlers
//------------------------------------------------------------------------------

/**
 * @brief Sorts important actuator information into individual UI elements.
 *
 * @param feedbacks Unordered map of joint(s) and their corresponding feedback
 * @param feedback_type The type of primary feedback provided
 */
void MainWindow::HandleActuatorFeedback(
    const std::unordered_map<Actuator::Joint, double>& feedbacks,
    const Actuator::Feedback feedback_type) {
    for (const auto& feedback : feedbacks) {
        try {
            // Index into the relevant UI label using the map-of-maps
            // initialized in the constructor
            feedback_element_map_.at(feedback.first)
                .at(feedback_type)
                ->setText(QString::number(feedback.second, 'f', 1));  // 0.1
        } catch (const std::out_of_range&) {
            qCritical() << "[ERROR] No UI element mapped to joint"
                        << feedback.first << "and feedback type"
                        << feedback_type;
        }
    }
}

/**
 * @brief Prints miscellaneous actuator information at the bottom of the UI.
 *
 * @param status Newline-delimited status info
 * @param type The actuator type, for updating the corresponding UI element
 */
void MainWindow::HandleActuatorStatus(const QString& status,
                                      const Actuator::Type type) {
    switch (type) {
        case Actuator::Type::kEpos:
            ui_->l_yaw_status->setText(status);
            break;
        case Actuator::Type::kHebi:
            ui_->l_pitch_status->setText(status);
            break;
        default:
            // Shouldn't be able to get here
            qCritical() << "[ERROR] Received status from unknown actuator type:"
                        << type;
    }
}

/**
 * @brief Throws a pop-up error box upon receiving an error signal from a thread.
 *
 * @param err Fatal error message from an actuator
 */
void MainWindow::HandleErrorMsg(const QString& err) {
    QMessageBox::critical(this, tr("Error"), err);
}

//------------------------------------------------------------------------------
// !Menu Bar
//------------------------------------------------------------------------------

/**
 * @brief Event handler for "Preferences" menu action "Debug Mode".
 *        Toggles debug prinouts for this object and all its children.
 */
void MainWindow::on_a_debug_mode_toggled(bool checked) {
    debug_mode_ = checked;

    if (debug_mode_) {
        qDebug() << "[DEBUG] Debug mode enabled";
    }

    // Propagate to all children
    emit UpdateDebugMode(checked);
}

/**
 * @brief Event handler for "Actuators/EPOS" menu action "Connect".
 *        Simply applies UI changes; functionality is covered by signal call.
 */
void MainWindow::on_a_epos_connect_triggered() {
    ui_->a_epos_connect->setEnabled(false);
    ui_->a_epos_disconnect->setEnabled(true);

    ui_->pb_arm_start->setEnabled(true);
    ui_->pb_arm_stop->setEnabled(true);
}

/**
 * @brief Event handler for "Actuators/EPOS" menu action "Disonnect".
 *        Simply applies UI changes; functionality is covered by signal call.
 */
void MainWindow::on_a_epos_disconnect_triggered() {
    ui_->a_epos_connect->setEnabled(true);
    ui_->a_epos_disconnect->setEnabled(false);

    ui_->pb_arm_start->setEnabled(false);
}

/**
 * @brief Event handler for "Actuators/HEBI" menu action "Connect".
 *        Simply applies UI changes; functionality is covered by signal call.
 */
void MainWindow::on_a_hebi_connect_triggered() {
    ui_->a_hebi_connect->setEnabled(false);
    ui_->a_hebi_disconnect->setEnabled(true);

    ui_->pb_arm_start->setEnabled(true);
    ui_->pb_arm_stop->setEnabled(true);
}

/**
 * @brief Event handler for "Actuators/HEBI" menu action "Disonnect".
 *        Simply applies UI changes; functionality is covered by signal call.
 */
void MainWindow::on_a_hebi_disconnect_triggered() {
    ui_->a_hebi_connect->setEnabled(true);
    ui_->a_hebi_disconnect->setEnabled(false);

    ui_->pb_arm_start->setEnabled(false);
}

/**
 * @brief Event handler for "Actuators/Manip. Servos" menu action "Connect".
 *        Brings up a dialog box of available serial USB devices. (TODO: check)
 */
void MainWindow::on_a_serial_servo_connect_triggered() {
    // Check if SerialServo Arduino (COM4) is connected
    bool found = false;
    foreach (const QSerialPortInfo& info, QSerialPortInfo::availablePorts()) {
        if (info.portName() == "COM4") {
            found = true;
            break;
        }
        if (debug_mode_) {
            // Enumerate available serial ports
            qDebug() << "[DEBUG] Found SerialPort with following metadata";
            qDebug() << "  Port: " << info.portName();
            qDebug() << "  Description: " << info.description();
            qDebug() << "  Manufacturer: " << info.manufacturer() << "\n";
            return;
        }
    }

    if (!found) {
        qDebug() << "[ERROR] SerialServo (COM4) not found!";
        return;
    }

    // Set port options
    ser_servo_->setPortName("COM4");
    ser_servo_->setBaudRate(QSerialPort::Baud115200);
    ser_servo_->setDataBits(QSerialPort::Data8);
    ser_servo_->setParity(QSerialPort::NoParity);
    ser_servo_->setStopBits(QSerialPort::OneStop);
    ser_servo_->setFlowControl(QSerialPort::NoFlowControl);

    // Only continue if "open" was successful
    if (!ser_servo_->open(QIODevice::ReadWrite)) {
        qDebug() << "[ERROR] Failed to open port: COM4!";
        QMessageBox::critical(this, tr("Error"), ser_servo_->errorString());
        return;
    }

    // Ensure data gets processed when it's made available
    connect(ser_servo_, &QSerialPort::readyRead, this,
            &MainWindow::UpdateServoVals);

    // Reflect changes in UI
    ui_->a_serial_servo_connect->setEnabled(false);
    ui_->a_serial_servo_disconnect->setEnabled(true);
    ui_->pb_manip_slow->setEnabled(true);
    ui_->pb_manip_fast->setEnabled(true);
}

/**
 * @brief Event handler for "Actuators/Manip. Servos" menu action "Disconnect".
 *        Terminates the connection to the `SerialServo` Arduino, if it exists.
 */
void MainWindow::on_a_serial_servo_disconnect_triggered() {
    // Clear the Serial and CameraManager objects
    if (ser_servo_->isOpen()) {
        ser_servo_->close();
    }
    camera_manager_.reset();

    // Reflect changes in UI
    ui_->a_serial_servo_connect->setEnabled(true);
    ui_->a_serial_servo_disconnect->setEnabled(false);
    ui_->pb_manip_slow->setEnabled(false);
    ui_->pb_manip_fast->setEnabled(false);
}

/**
 * @brief Event handler for "Sensors/RealSense" menu action "Refresh Camera
 *        List". Populates the "Camera" tab's ComboBox with all detected cameras.
 */
void MainWindow::on_a_refresh_camera_list_triggered() {
    qDebug() << "[INFO] Checking available video inputs...";

    const auto cameras = QMediaDevices::videoInputs();
    for (const auto& camera_device : cameras) {
        auto id = QString(camera_device.id());

        if (debug_mode_) {
            qDebug() << "[DEBUG] Found camera at " << camera_device.id();
        }

        // Populate ComboBox (new items are appended to existing list)
        ui_->cb_camera_id->addItem(id);
        // Populate internal map (used on ComboBox change)
        available_cameras_[id] = camera_device.description();
    }

    if (!available_cameras_.empty()) {
        ui_->pb_camera_capture->setEnabled(true);
        ui_->pb_camera_record->setEnabled(true);
    } else if (debug_mode_) {
        qDebug() << "[DEBUG] No cameras were found";
    }
}

/**
 * @brief Event handler for "Sensors/2D LIDAR" menu action "Connect".
 *        ???
 */
void MainWindow::on_a_lidar_connect_triggered() {
    qDebug() << "[WARN] 2D LIDAR \"Connect\" not yet implemented";

    // TODO: 2D LIDAR implementation

    // Reflect changes in UI
    ui_->a_lidar_connect->setEnabled(false);
    ui_->a_lidar_disconnect->setEnabled(true);
}

/**
 * @brief Event handler for "Sensors/2D LIDAR" menu action "Disconnect".
 *        ???
 */
void MainWindow::on_a_lidar_disconnect_triggered() {
    qDebug() << "[WARN] 2D LIDAR \"Disconnect\" not yet implemented";

    // TODO: 2D LIDAR implementation

    // Reflect changes in UI
    ui_->a_lidar_connect->setEnabled(true);
    ui_->a_lidar_disconnect->setEnabled(false);
}

/**
 * @brief Event handler for "Sensors/2D LIDAR" menu action "About".
 *        Opens a dialog box with sensor metadata, if connected.
 */
void MainWindow::on_a_lidar_about_triggered() {
    qDebug() << "[WARN] 2D LIDAR \"About\" not yet implemented";

    // TODO: spinning LIDAR implementation
}

/**
 * @brief Event handler for "Pump" menu action "Connect".
 *        Brings up a dialog box of available serial USB devices. (TODO: check)
 */
void MainWindow::on_a_pump_connect_triggered() {
    // Check if SerialWater Arduino (COM3) is connected
    bool found = false;
    foreach (const QSerialPortInfo& info, QSerialPortInfo::availablePorts()) {
        if (info.portName() == "COM3") {
            found = true;
            break;
        }
        if (debug_mode_) {
            // Enumerate available serial ports
            qDebug() << "[DEBUG] Found SerialPort with following metadata";
            qDebug() << "  Port: " << info.portName();
            qDebug() << "  Description: " << info.description();
            qDebug() << "  Manufacturer: " << info.manufacturer() << "\n";
            return;
        }
    }

    if (!found) {
        qDebug() << "[ERROR] SerialWater (COM3) not found!";
        return;
    }

    // Set port options
    ser_water_->setPortName("COM3");
    ser_water_->setBaudRate(QSerialPort::Baud115200);
    ser_water_->setDataBits(QSerialPort::Data8);
    ser_water_->setParity(QSerialPort::NoParity);
    ser_water_->setStopBits(QSerialPort::OneStop);
    ser_water_->setFlowControl(QSerialPort::NoFlowControl);

    // Only continue if "open" was successful
    if (!ser_water_->open(QIODevice::ReadWrite)) {
        qDebug() << "[ERROR] Failed to open port: COM3!";
        QMessageBox::critical(this, tr("Error"), ser_water_->errorString());
        return;
    }

    // Ensure data gets processed when it's made available
    connect(ser_water_, &QSerialPort::readyRead, this,
            &MainWindow::UpdatePumpVals);

    // Reflect changes in UI
    ui_->a_pump_connect->setEnabled(false);
    ui_->a_pump_disconnect->setEnabled(true);
    ui_->pb_pump_enable->setEnabled(true);
    ui_->pb_pump_disable->setEnabled(true);
    ui_->pb_pump_drain->setEnabled(true);
}

/**
 * @brief Event handler for "Pump" menu action "Disconnect".
 *        Terminates the connection to the `SerialWater` Arduino, if it exists.
 */
void MainWindow::on_a_pump_disconnect_triggered() {
    // Clear the Serial object
    if (ser_water_->isOpen()) {
        ser_water_->close();
    }

    // Reflect changes in UI
    ui_->a_pump_connect->setEnabled(true);
    ui_->a_pump_disconnect->setEnabled(false);
    ui_->pb_pump_enable->setEnabled(false);
    ui_->pb_pump_disable->setEnabled(false);
    ui_->pb_pump_drain->setEnabled(false);
}

/**
 * @brief Event handler for "Pump/Advanced" menu action "Set empty (0%)".
 *        Forces the tank (water bladder) visualization to show as empty.
 *
 * @note Only use if there is a discrepancy with the physical water bladders.
 */
void MainWindow::on_a_pump_set_empty_triggered() {
    ui_->w_tank_visual->OverrideLevel(0.0);
}

/**
 * @brief Event handler for "Pump/Advanced" menu action "Set full (100%)".
 *        Forces the tank (water bladder) visualization to show as full.
 *
 * @note Only use if there is a discrepancy with the physical water bladders.
 */
void MainWindow::on_a_pump_set_full_triggered() {
    ui_->w_tank_visual->OverrideLevel(1.0);
}

/**
 * @brief Event handler for "Quick Ations" menu action "Connect All".
 *        Connects all peripheral devices (actuators, sensors, etc.).
 */
void MainWindow::on_a_connect_all_triggered() {
    // Actuators
    ui_->a_epos_connect->trigger();
    ui_->a_hebi_connect->trigger();
    ui_->a_serial_servo_connect->trigger();
    ui_->a_pump_connect->trigger();

    // Sensors
    ui_->a_refresh_camera_list->trigger();
    ui_->a_lidar_connect->trigger();
}

/**
 * @brief Event handler for "Quick Ations" menu action "Disconnect All".
 *        Disconnects all peripheral devices (actuators, sensors, etc.).
 */
void MainWindow::on_a_disconnect_all_triggered() {
    // Actuators
    ui_->a_epos_disconnect->trigger();
    ui_->a_hebi_disconnect->trigger();
    ui_->a_serial_servo_disconnect->trigger();
    ui_->a_pump_disconnect->trigger();

    // Sensors
    ui_->a_lidar_disconnect->trigger();
}

//------------------------------------------------------------------------------
// !Main Window
//------------------------------------------------------------------------------

//------------------------------------------------------------------------------
// !Arm
//------------------------------------------------------------------------------

/**
 * @brief Send movement command signal to all actuators.
 */
void MainWindow::on_pb_arm_start_clicked() {
    // Yaw
    emit CommandEpos({ui_->sb_arm_yaw->value()});

    // Pitch
    emit CommandHebi({ui_->sb_arm_pitch->value()});
}

//------------------------------------------------------------------------------
// !Manipulator
//------------------------------------------------------------------------------

/**
 * @brief Moves manipulator servos at a leisurely pace.
 */
void MainWindow::on_pb_manip_slow_clicked() {
    if (!ser_servo_->isOpen()) {
        qDebug() << "[WARN] SerialServo not connected!";
        return;
    }

    qDebug() << "[WARN] Camera servo control not yet implemented!";

    // TODO: implementation (adapt code below)
    /*
    manip_setpos_.at(1) = ibox_camera_pan_->GetNum();
    manip_setpos_.at(2) = ibox_camera_tilt_->GetNum();
    manip_dir_.at(1) = (manip_setpos_.at(1) > manip_pos_.at(1)) ? 1 :
                        ((manip_setpos_.at(1) < manip_pos_.at(1)) ? -1 : 0);
    manip_dir_.at(2) = (manip_setpos_.at(2) > manip_pos_.at(2)) ? 1 :
                        ((manip_setpos_.at(2) < manip_pos_.at(2)) ? -1 : 0);
    manip_pos_.at(1) += manip_dir_.at(1) * 90.0 / (60.0 * 60.0);
    manip_pos_.at(2) += manip_dir_.at(2) * 90.0 / (60.0 * 60.0);
    */
}

/**
 * @brief Moves manipulator servos at maximum speed (near-instant).
 */
void MainWindow::on_pb_manip_fast_clicked() {
    if (!ser_servo_->isOpen()) {
        qDebug() << "[WARN] SerialServo not connected!";
        return;
    }

    qDebug() << "[WARN] Camera servo control not yet implemented!";

    // TODO: implementation (adapt code below)
    /*
    manip_pos_.at(1) = ibox_camera_pan_->GetNum();
    manip_pos_.at(2) = ibox_camera_tilt_->GetNum();
    */
}

/**
 * @brief Updates camera servo values shown in the UI.
 */
void MainWindow::UpdateServoVals() {
    if (!ser_servo_->isOpen()) {
        qDebug() << "[WARN] SerialServo not connected!";
        return;
    }

    auto data = ser_servo_->readAll();
    if (debug_mode_) {
        qDebug() << "[DEBUG] Received data from SerialServo:" << data;
    }

    qDebug() << "[WARN] Camera servo control not yet implemented!";

    // TODO: implementation
}

//------------------------------------------------------------------------------
// !Pump
//------------------------------------------------------------------------------

/**
 * @brief Enables operation of fluid system pump(s).
 */
void MainWindow::on_pb_pump_enable_clicked() {
    if (!ser_water_->isOpen()) {
        qDebug() << "[WARN] SerialWater not connected!";
        return;
    }

    qDebug() << "[WARN] Pump control not yet implemented!";

    // TODO: implementation (adapt code below)
    /*
    water_en_ = true;
    water_mode_ = WaterMode::kStandby;
    */
}

/**
 * @brief Disables operation of fluid system pump(s).
 *
 * @todo Combine funcitonality with `on_pb_pump_enable_clicked()` and
 *       refactor the resulting function. Don't forget to rename it to something
 *       that makes more sense, e.g., including the word "toggle". For reference
 *       on changing button text to reflect state, see
 *       `on_pb_camera_record_clicked()`.
 */
void MainWindow::on_pb_pump_disable_clicked() {
    if (!ser_water_->isOpen()) {
        qDebug() << "[WARN] SerialWater not connected!";
        return;
    }

    qDebug() << "[WARN] Pump control not yet implemented!";

    // TODO: implementation (adapt code below)
    /*
    water_en_ = false;
    water_mode_ = WaterMode::kStandby;
    */
}

/**
 * @brief Enables fluid system pump(s) and forces them on.
 */
void MainWindow::on_pb_pump_drain_clicked() {
    if (!ser_water_->isOpen()) {
        qDebug() << "[WARN] SerialWater not connected!";
        return;
    }

    qDebug() << "[WARN] Pump control not yet implemented!";

    // TODO: implementation (adapt code below)
    /*
    water_en_ = true;
    water_mode_ = WaterMode::kDrain;
    */
}

/**
 * @brief Updates pump values shown in the UI (from `ser_water_` Arduino).
 */
void MainWindow::UpdatePumpVals() {
    if (!ser_water_->isOpen()) {
        qDebug() << "[WARN] SerialWater not connected!";
        return;
    }

    auto data = ser_water_->readAll();
    if (debug_mode_) {
        qDebug() << "[DEBUG] Received data from SerialWater:" << data;
    }

    qDebug() << "[WARN] Pump control not yet implemented!";

    // TODO: implementation
}

//------------------------------------------------------------------------------
// !Camera
//------------------------------------------------------------------------------

/**
 * @brief Connects to the selected camera feed.
 */
void MainWindow::on_cb_camera_id_currentTextChanged(const QString& sel) {
    if (camera_manager_ != nullptr) {
        if (debug_mode_) {
            qDebug() << "[DEBUG] Resetting existing camera manager";
        }
        camera_manager_.reset();
    }

    // Show human-readable camera name
    ui_->l_camera_name->setText(available_cameras_[sel]);

    // Open a connection to the camera
    camera_manager_ = std::make_unique<CameraManager>(sel,
                                                      ui_->vw_camera_viewfinder,
                                                      this);
    camera_manager_->Start();

    // Reflect changes in UI
    ui_->pb_camera_capture->setEnabled(true);
    ui_->pb_camera_record->setEnabled(true);
}

/**
 * @brief Captures a still image from the active camera feed.
 */
void MainWindow::on_pb_camera_capture_clicked() {
    camera_manager_->Capture();

    // Display a status tip at the bottom of the UI
    statusBar()->showMessage("Saved capture to img/ directory!", kInfoLifespan);
}

/**
 * @brief Toggles video recording from the active camera feed.
 */
void MainWindow::on_pb_camera_record_clicked() {
    if (camera_manager_->Record()) {
        // Clearly display a "recording" state
        ui_->pb_camera_record->setStyleSheet("color: red;");
        ui_->pb_camera_record->setText("STOP");
    } else {
        // Display a status tip at the bottom of the UI
        statusBar()->showMessage("Saved recording to vid/ directory!",
                                 kInfoLifespan);

        // Revert to original state
        ui_->pb_camera_record->setStyleSheet("color: black;");
        ui_->pb_camera_record->setText("RECORD");
    }
}

//------------------------------------------------------------------------------
// !Misc.
//------------------------------------------------------------------------------

//------------------------------------------------------------------------------
// !Uncategorized
//------------------------------------------------------------------------------
