/******************************************************************************
 * @file   open_serial_dialog.cpp
 * @brief  Serial (USB) selection dialog box implementation file.
 *
 * @author brice.c.aa
 ******************************************************************************/

// Related Header
#include "open_serial_dialog.h"

// C++ Standard Library Headers
//   (none)

// Other Library Headers
//   (none)

// Project Headers
#include "ui_open_serial_dialog.h"  // auto-generated by Qt

/* --- TABLE OF CONTENTS ---
 * !Local Helpers
 * !Class Management
 * !Helper Functions
 * !Main Window
 * !Getters & Setters
 * !Uncategorized
 */

//------------------------------------------------------------------------------
// !Local Helpers
//------------------------------------------------------------------------------

namespace {}

//------------------------------------------------------------------------------
// !Class Management
//------------------------------------------------------------------------------

/**
 * @brief Standard constructor.
 *
 * @param parent Owning Qt widget (default: nullptr)
 * @param device_to_prompt Label for informing the user which device will be
 *                         opened with the result of this dialog box
 */
OpenSerialDialog::OpenSerialDialog(QWidget* parent, QString device_to_prompt)
    : QDialog(parent), ui_(new Ui::OpenSerialDialog) {
    ui_->setupUi(this);

    // Set dialog title to include the port label
    this->setWindowTitle(QString("Select %1 Port").arg(device_to_prompt));

    // Populate ports on creation
    PopulatePorts();
}

/**
 * @brief Standard QDialog destructor.
 */
OpenSerialDialog::~OpenSerialDialog() {
    delete ui_;
}

//------------------------------------------------------------------------------
// !Helper Functions
//------------------------------------------------------------------------------

/**
 * @brief Populates the "Select Port" ComboBox with all valid ports (i.e.,
 *        serial devices that have non-empty descriptions).
 */
void OpenSerialDialog::PopulatePorts() {
    valid_ports_.clear();
    ui_->cb_ports->clear();

    // Collect ports with non-empty descriptions (i.e., exclude virtual ports)
    foreach (const auto& info, QSerialPortInfo::availablePorts()) {
        if (!info.description().isEmpty()) {
            valid_ports_.append(info);
            ui_->cb_ports->addItem(info.portName());
        }
    }

    // Set port description label
    if (!valid_ports_.isEmpty()) {
        ui_->l_port_description->setText(valid_ports_[0].description());
    } else {
        ui_->l_port_description->setText("No valid ports found!");
    }
}

//------------------------------------------------------------------------------
// !Main Window
//------------------------------------------------------------------------------

/**
 * @brief Event handler for "Select Port" ComboBox selection.
 *        Populates the "Description" label with the full device name.
 *
 * @param sel The index of the device name selected by the user
 */
void OpenSerialDialog::on_cb_ports_currentIndexChanged(int sel) {
    if (sel >= 0 && sel < valid_ports_.size()) {
        ui_->l_port_description->setText(valid_ports_[sel].description());
    }
}

//------------------------------------------------------------------------------
// !Getters & Setters
//------------------------------------------------------------------------------

/**
 * @brief Returns the Linux device name used to communicate with a serial device.
 *
 * @return QString Device name for serial connection
 */
QString OpenSerialDialog::GetSelectedPortName() {
    auto i = ui_->cb_ports->currentIndex();
    if (i >= 0 && i < valid_ports_.size()) {
        return valid_ports_[i].portName();
    }

    return QString();
}

//------------------------------------------------------------------------------
// !Uncategorized
//------------------------------------------------------------------------------
