%YAML:1.0

#------------------------------------------------------------------------------>
# RealSense D456 Camera Parameters. (Infrared, 848x480)
#------------------------------------------------------------------------------>
Camera.type: "PinHole"

# Left Camera calibration and distortion parameters (OpenCV)
Camera.fx: 430.714
Camera.fy: 430.714
Camera.cx: 425.014
Camera.cy: 240.590
# distortion parameters
Camera.k1: 0.0
Camera.k2: 0.0
Camera.p1: 0.0
Camera.p2: 0.0

# Right Camera calibration and distortion parameters (OpenCV)
Camera2.fx: 430.714
Camera2.fy: 430.714
Camera2.cx: 425.014
Camera2.cy: 240.590
# distortion parameters
Camera2.k1: 0.0
Camera2.k2: 0.0
Camera2.p1: 0.0
Camera2.p2: 0.0

# Transformation from left camera (Infrared 1) to right camera (Infrared 2)
Tlr: !!opencv-matrix
  rows: 3
  cols: 4
  dt: f
  data: [1.0, 0.0, 0.0, -0.0950501,
         0.0, 1.0, 0.0, 0.0,
         0.0, 0.0, 1.0, 0.0,
         0.0, 0.0, 0.0, 1.0]

# Camera resolution
Camera.width: 848
Camera.height: 480

# Camera frames per second 
Camera.fps: 30.0

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

# Image scale, it changes the image size to be processed (<1.0: reduce, >1.0: increase)
Camera.imageScale: 0.5 # 0.5 #0.7071 # 1/sqrt(2)

# Close/Far threshold
ThDepth: 50.0
# Stereo baseline (in meters) times fx
# - D410: b=0.055
# - D415: b=0.055
# - D430: b=0.050
# - D450: b=0.095
# - D401: b=0.018
Camera.bf: 40.91783

#--------------------------------------------------------------------------------------------
# ORB Parameters (unchanged from RealSense_D435i.yaml)
#--------------------------------------------------------------------------------------------
# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 1250

# ORB Extractor: Scale factor between levels in the scale pyramid 	
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid	
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast			
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7

#--------------------------------------------------------------------------------------------
# Viewer Parameters (unchanged from RealSense_D435i.yaml)
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3
Viewer.ViewpointX: 0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -3.5
Viewer.ViewpointF: 500
