################################################################################
# @file   CMakeLists.txt
# @brief  ROS2 workspace CMakeLists file.
#
# @author brice.c.aa
################################################################################

# Register interfaces (e.g., messages) before the nodes that use them
# TODO: add_subdirectory(interfaces)
add_subdirectory(nodes)
