/******************************************************************************
 * @file   open_epos_dialog.cpp
 * @brief  Open EPOS device window implementation file.
 *
 * @author Christian Brice
 ******************************************************************************/

// Related Header
#include "open_epos_dialog.h"

// C++ Standard Library Headers
//   (none)

// Other Library Headers
#include "Definitions.h"  // EPOS (Maxon)

// Project Headers
#include "ui_open_epos_dialog.h"  // auto-generated by Qt
#include "util.h"

/* --- TABLE OF CONTENTS ---
 * !Local Helpers
 * !Class Management
 * !Main Window
 * !Getters & Setters
 * !Uncategorized
 */

// EPOS Functions

constexpr int kMaxonTrue = 1;   // In general Maxon code = TRUE
constexpr int kMaxonFalse = 0;  // In general Maxon code = FALSE
constexpr uint kMaxCharBufSize = 100;
constexpr uint kTimeout = 100;  // ms

//------------------------------------------------------------------------------
// !Local Helpers
//------------------------------------------------------------------------------

//------------------------------------------------------------------------------
// !Class Management
//------------------------------------------------------------------------------

/**
 * @brief Standard constructor.
 *        Also populates the "Device" combo box and enables it.
 *
 * @param parent Owning Qt widget
 */
OpenEposDialog::OpenEposDialog(QWidget* parent)
    : QDialog(parent), ui_(new Ui::OpenEposDialog) {
    ui_->setupUi(this);

    QStringList devices;
    char name[kMaxCharBufSize];
    int end_of_sel = 0;
    uint err_code = 0;

    // Get name of first device communicating on network
    if (VCS_GetDeviceNameSelection(kMaxonTrue, name, kMaxCharBufSize,
                                   &end_of_sel, &err_code)
        != 0) {
        devices << name;

        // Get names of other devices on the network, if any
        while (end_of_sel == 0) {
            memset(name, '\0', kMaxCharBufSize);
            VCS_GetDeviceNameSelection(kMaxonFalse, name, kMaxCharBufSize,
                                       &end_of_sel, &err_code);
            devices << name;
        }
    }

    // Validation
    if (err_code != 0) {
        qCritical() << util::GetFormattedEposErrTxt(
            "VCS_GetDeviceNameSelection", err_code);
        return;
    }

    if (devices.empty()) {
        qWarning() << "No devices found on the network!";
    }

    // Populate Device combo box and enable it
    devices.removeDuplicates();  // just in case
    ui_->cb_device_name->addItems(devices);
    ui_->cb_device_name->setEnabled(true);

    // If only one device available, automatically populate next combo box
    if (devices.count() == 1) {
        on_cb_device_name_textActivated(devices.first());
    }
}

/**
 * @brief Standard destructor.
 */
OpenEposDialog::~OpenEposDialog() {
    delete ui_;
}

//------------------------------------------------------------------------------
// !Main Window
//------------------------------------------------------------------------------

/**
 * @brief Event handler for "Device" combo box selection.
 *        Populates the "Protocol" combo box and enables it.
 *
 * @param sel The device name selected by the user
 */
void OpenEposDialog::on_cb_device_name_textActivated(const QString& sel) {
    // Save selected device name
    params_.device_name = sel.toStdString();

    // Ensure all "downstream" selections and combo boxes are cleared
    params_.protocol_name.clear();
    ui_->cb_protocol_name->clear();
    ui_->cb_protocol_name->setEnabled(false);
    params_.interface_name.clear();
    ui_->cb_interface_name->clear();
    ui_->cb_interface_name->setEnabled(false);
    params_.port_name.clear();
    ui_->cb_port_name->clear();
    ui_->cb_port_name->setEnabled(false);
    params_.baud_rate = 0;
    ui_->cb_baud_rate->clear();
    ui_->cb_baud_rate->setEnabled(false);

    // Get name of first protocol used on network
    QStringList protocols;
    char name[kMaxCharBufSize];
    int end_of_sel = 0;
    uint err_code = 0;

    if (VCS_GetProtocolStackNameSelection(params_.device_name.data(),
                                          kMaxonTrue, name, kMaxCharBufSize,
                                          &end_of_sel, &err_code)
        > 0) {
        protocols << name;

        // Get names of other protocols on the network, if any
        while (end_of_sel == 0) {
            memset(name, '\0', kMaxCharBufSize);
            VCS_GetProtocolStackNameSelection(params_.device_name.data(),
                                              kMaxonFalse, name,
                                              kMaxCharBufSize, &end_of_sel,
                                              &err_code);
            protocols << name;
        }
    }

    // Validation
    if (err_code != 0) {
        qCritical() << util::GetFormattedEposErrTxt(
            "VCS_GetProtocolStackNameSelection", err_code);
        return;
    }

    if (protocols.empty()) {
        qWarning() << "No protocols in use by "
                   << QString::fromStdString(params_.device_name);
        return;
    }

    // Populate Protocol combo box and enable it
    protocols.removeDuplicates();  // just in case
    ui_->cb_protocol_name->addItems(protocols);
    ui_->cb_protocol_name->setEnabled(true);

    // If only one protocol available, automatically populate next combo box
    if (protocols.count() == 1) {
        on_cb_protocol_name_textActivated(protocols.first());
    }
}

/**
 * @brief Event handler for "Protocol" combo box selection.
 *        Populates the "Interface" combo box and enables it.
 *
 * @param sel The protocol name selected by the user
 */
void OpenEposDialog::on_cb_protocol_name_textActivated(const QString& sel) {
    // Save selected protocol name
    params_.protocol_name = sel.toStdString();

    // Ensure all "downstream" selections and combo boxes are cleared
    params_.interface_name.clear();
    ui_->cb_interface_name->clear();
    ui_->cb_interface_name->setEnabled(false);
    params_.port_name.clear();
    ui_->cb_port_name->clear();
    ui_->cb_port_name->setEnabled(false);
    params_.baud_rate = 0;
    ui_->cb_baud_rate->clear();
    ui_->cb_baud_rate->setEnabled(false);

    // Get name of first interface listed on network
    QStringList interfaces;
    char name[kMaxCharBufSize];
    int end_of_sel = 0;
    uint err_code = 0;

    if (VCS_GetInterfaceNameSelection(params_.device_name.data(),
                                      params_.protocol_name.data(), kMaxonTrue,
                                      name, kMaxCharBufSize, &end_of_sel,
                                      &err_code)
        > 0) {
        interfaces << name;

        // Get names of other interfaces on the network, if any
        while (end_of_sel == 0) {
            memset(name, '\0', kMaxCharBufSize);
            VCS_GetInterfaceNameSelection(params_.device_name.data(),
                                          params_.protocol_name.data(),
                                          kMaxonFalse, name, kMaxCharBufSize,
                                          &end_of_sel, &err_code);
            interfaces << name;
        }
    }

    // Validation
    if (err_code != 0) {
        qCritical() << util::GetFormattedEposErrTxt(
            "VCS_GetInterfaceNameSelection", err_code);
        return;
    }

    if (interfaces.empty()) {
        qWarning() << "No interfaces found running "
                   << QString::fromStdString(params_.protocol_name);
        return;
    }

    // Populate Interface combo box and enable it
    interfaces.removeDuplicates();  // just in case
    ui_->cb_interface_name->addItems(interfaces);
    ui_->cb_interface_name->setEnabled(true);

    // If only one interface available, automatically populate next combo box
    if (interfaces.count() == 1) {
        on_cb_interface_name_textActivated(interfaces.first());
    }
}

/**
 * @brief Event handler for "Interface" combo box selection.
 *        Populates the "Port" combo box and enables it.
 *
 * @param sel The interface name selected by the user
 */
void OpenEposDialog::on_cb_interface_name_textActivated(const QString& sel) {
    // Save selected interface name
    params_.interface_name = sel.toStdString();

    // Ensure all "downstream" selections and combo boxes are cleared
    params_.port_name.clear();
    ui_->cb_port_name->clear();
    ui_->cb_port_name->setEnabled(false);
    params_.baud_rate = 0;
    ui_->cb_baud_rate->clear();
    ui_->cb_baud_rate->setEnabled(false);

    // Get name of first port open on network
    QStringList ports;
    char name[kMaxCharBufSize];
    int end_of_sel = 0;
    uint err_code = 0;

    if (VCS_GetPortNameSelection(params_.device_name.data(),
                                 params_.protocol_name.data(),
                                 params_.interface_name.data(), kMaxonTrue,
                                 name, kMaxCharBufSize, &end_of_sel, &err_code)
        > 0) {
        ports << name;

        // Get names of other ports on the network, if any
        while (end_of_sel == 0) {
            memset(name, '\0', kMaxCharBufSize);
            VCS_GetPortNameSelection(params_.device_name.data(),
                                     params_.protocol_name.data(),
                                     params_.interface_name.data(), kMaxonFalse,
                                     name, kMaxCharBufSize, &end_of_sel,
                                     &err_code);
            ports << name;
        }
    }

    // Validation
    if (err_code != 0) {
        qCritical() << util::GetFormattedEposErrTxt("VCS_GetPortNameSelection",
                                                    err_code);
        return;
    }

    if (ports.empty()) {
        qWarning() << "No ports found on "
                   << QString::fromStdString(params_.interface_name);
    }

    // Populate Port combo box and enable it
    ports.removeDuplicates();  // just in case
    ui_->cb_port_name->addItems(ports);
    ui_->cb_port_name->setEnabled(true);

    // If only one port available, automatically populate next combo box
    if (ports.count() == 1) {
        on_cb_port_name_textActivated(ports.first());
    }
}

/**
 * @brief Event handler for "Port" combo box selection.
 *        Populates the "Baud Rate" combo box and enables it.
 *
 * @param sel The port name selected by the user
 */
void OpenEposDialog::on_cb_port_name_textActivated(const QString& sel) {
    // Save selected port name
    params_.port_name = sel.toStdString();

    // Ensure all "downstream" selections and combo boxes are cleared
    params_.baud_rate = 0;
    ui_->cb_baud_rate->clear();
    ui_->cb_baud_rate->setEnabled(false);

    // Get first available baud rate for port
    QStringList bauds;
    uint rate = 0;
    int end_of_sel = 0;
    uint err_code = 0;

    if (VCS_GetBaudrateSelection(params_.device_name.data(),
                                 params_.protocol_name.data(),
                                 params_.interface_name.data(),
                                 params_.port_name.data(), kMaxonTrue, &rate,
                                 &end_of_sel, &err_code)
        > 0) {
        bauds << QString::number(rate);

        // Get other baud rates for port, if any
        while (end_of_sel == 0) {
            rate = 0;
            VCS_GetBaudrateSelection(params_.device_name.data(),
                                     params_.protocol_name.data(),
                                     params_.interface_name.data(),
                                     params_.port_name.data(), kMaxonFalse,
                                     &rate, &end_of_sel, &err_code);
            bauds << QString::number(rate);
        }
    }

    // Validation
    if (err_code != 0) {
        qCritical() << util::GetFormattedEposErrTxt("VCS_GetBaudrateSelection",
                                                    err_code);
        return;
    }

    if (bauds.empty()) {
        qWarning() << "No baud rates available for "
                   << QString::fromStdString(params_.port_name);
    }

    // Populate Baud Rate combo box and enable it
    bauds.removeDuplicates();  // just in case
    ui_->cb_baud_rate->addItems(bauds);
    ui_->cb_baud_rate->setEnabled(true);

    // If only one baud rate available, automatically populate next combo box
    if (bauds.count() == 1) {
        on_cb_baud_rate_textActivated(bauds.first());
    }
}

/**
 * @brief Event handler for "Baud Rate" combo box selection.
 *        Enables the "Connect" button.
 *
 * @param sel The baud rate selected by the user
 */
void OpenEposDialog::on_cb_baud_rate_textActivated(const QString& sel) {
    // Save selected baud rate
    params_.baud_rate = sel.toUInt();
    params_.is_set = true;  // finished selecting all params

    // Since all device parameters have been specified, enable Connect button
    ui_->pb_confirm->setEnabled(true);
}

/**
 * @brief Event handler for "Connect" button. Simply closes the window, as EPOS
 *        connection should, in principle, be handled by the object which will
 *        command the device.
 */
void OpenEposDialog::on_pb_confirm_clicked() {
    // Close the dialog and return `QDialog::Accepted`
    OpenEposDialog::accept();
}

/**
 * @brief Event handler for "Cancel" button. Gives the user another way to close
 *        the window (in addition to the X in the menu bar).
 */
void OpenEposDialog::on_pb_cancel_clicked() {
    // Close the dialog and return `QDialog::Rejected`
    OpenEposDialog::reject();
}

//------------------------------------------------------------------------------
// !Getters & Setters
//------------------------------------------------------------------------------

/**
 * @brief Returns the necessary device parameters for opening a connection to
 *        the EPOS controller.
 *
 * @return EposDeviceParams Convenience struct grouping all device parameters
 */
EposDeviceParams OpenEposDialog::GetDeviceParams() {
    return std::move(params_);
}

//------------------------------------------------------------------------------
// !Uncategorized
//------------------------------------------------------------------------------
