/******************************************************************************
 * @file   open_serial_dialog.cpp
 * @brief  Serial (USB) selection dialog box implementation file.
 *
 * @author Christian Brice
 ******************************************************************************/

// Related Header
#include "open_serial_dialog.h"

// C++ Standard Library Headers
//   (none)

// Other Library Headers
//   (none)

// Project Headers
#include "ui_open_serial_dialog.h"  // auto-generated by Qt

/* --- TABLE OF CONTENTS ---
 * !Local Helpers
 * !Class Management
 * !Helper Functions
 * !Main Window
 * !Getters & Setters
 * !Uncategorized
 */

//------------------------------------------------------------------------------
// !Local Helpers
//------------------------------------------------------------------------------

namespace {}

//------------------------------------------------------------------------------
// !Class Management
//------------------------------------------------------------------------------

/**
 * @brief Standard constructor.
 *
 * @param parent Owning Qt widget
 * @param device_to_prompt Label for informing the user which device will be
 *                         opened with the result of this dialog box
 * @param wanted_device_desc Device description (human-readable name) to
 *                           automatically search for
 */
OpenSerialDialog::OpenSerialDialog(QWidget* parent, QString device_to_prompt,
                                   QString wanted_device_desc)
    : QDialog(parent),
      ui_(new Ui::OpenSerialDialog),
      wanted_device_desc_(wanted_device_desc) {
    ui_->setupUi(this);

    // Set dialog title to include the port label
    this->setWindowTitle(QString("Select %1 Port").arg(device_to_prompt));

    // Populate ports on creation
    PopulatePorts();

    // Search for wanted device, close dialog if found
    AutoSelectWantedDevice();  // does nothing if wanted_device_desc_ is empty
}

/**
 * @brief Standard QDialog destructor.
 */
OpenSerialDialog::~OpenSerialDialog() {
    delete ui_;
}

//------------------------------------------------------------------------------
// !Helper Functions
//------------------------------------------------------------------------------

/**
 * @brief Populates the "Select Port" ComboBox with all valid ports (i.e.,
 *        serial devices that have non-empty descriptions).
 */
void OpenSerialDialog::PopulatePorts() {
    valid_ports_.clear();
    ui_->cb_ports->clear();

    // Collect ports with non-empty descriptions (i.e., exclude virtual ports)
    foreach (const auto& info, QSerialPortInfo::availablePorts()) {
        if (!info.description().isEmpty()) {
            valid_ports_.append(info);
            ui_->cb_ports->addItem(info.portName());
        }
    }

    // Set port description label
    if (!valid_ports_.isEmpty()) {
        ui_->l_port_description->setText(valid_ports_[0].description());
    } else {
        ui_->l_port_description->setText("No valid ports found!");
    }
}

/**
 * @brief Searches for a device with matching description and auto-selects it.
 *        If exactly one matching device is found: selects it and closes the dialog.
 */
void OpenSerialDialog::AutoSelectWantedDevice() {
    if (wanted_device_desc_.isEmpty()) {
        return;
    }

    int match_idx = -1;
    int num_match = 0;

    // Search for devices with matching description
    for (auto i = 0; i < valid_ports_.size(); ++i) {
        if (valid_ports_[i].description().contains(wanted_device_desc_,
                                                   Qt::CaseInsensitive)) {
            match_idx = i;
            num_match++;
        }
    }

    // If at least one match was found, select it
    if (num_match >= 1) {
        qDebug() << "Found" << num_match
                 << "device(s) matching description:" << wanted_device_desc_;

        ui_->cb_ports->setCurrentIndex(match_idx);
        ui_->l_port_description->setText(valid_ports_[match_idx].description());

        // If exactly one match was found, go ahead and close the dialog
        if (num_match == 1) {
            accept();
        }
    } else {
        qDebug() << "No matching device found for description:"
                 << wanted_device_desc_;
    }
}

//------------------------------------------------------------------------------
// !Main Window
//------------------------------------------------------------------------------

/**
 * @brief Event handler for "Select Port" ComboBox selection.
 *        Populates the "Description" label with the full device name.
 *
 * @param sel The index of the device name selected by the user
 */
void OpenSerialDialog::on_cb_ports_currentIndexChanged(int sel) {
    if (sel >= 0 && sel < valid_ports_.size()) {
        ui_->l_port_description->setText(valid_ports_[sel].description());
    }
}

//------------------------------------------------------------------------------
// !Getters & Setters
//------------------------------------------------------------------------------

/**
 * @brief Returns the Linux device name used to communicate with a serial device.
 *
 * @return QString Device name for serial connection
 */
QString OpenSerialDialog::GetSelectedPortName() {
    auto i = ui_->cb_ports->currentIndex();
    if (i >= 0 && i < valid_ports_.size()) {
        return valid_ports_[i].portName();
    }

    return QString();
}

//------------------------------------------------------------------------------
// !Uncategorized
//------------------------------------------------------------------------------
