/******************************************************************************
 * @file   torque_comp_dialog.cpp
 * @brief  Torque compensation settings dialog box implementation file.
 *
 * @author Christian Brice
 ******************************************************************************/

// Related Header
#include "torque_comp_dialog.h"

// C++ Standard Library Headers
//   (none)

// Other Library Headers
//   (none)

// Project Headers
#include "ui_torque_comp_dialog.h"  // auto-generated by Qt

/* --- TABLE OF CONTENTS ---
 * !Class Management
 * !Class Helpers
 * !Uncategorized
 */

//------------------------------------------------------------------------------
// !Class Management
//------------------------------------------------------------------------------

/**
 * @brief Standard constructor.
 *
 * @param parent Owning Qt widget
 * @param upper_bound Initial lower bound value, in Nm
 * @param lower_bound Initial upper bound value, in Nm
 */
TorqueCompDialog::TorqueCompDialog(QWidget* parent, const double& lower_bound,
                                   const double& upper_bound)
    : QDialog(parent), ui_(new Ui::TorqueCompDialog) {
    ui_->setupUi(this);
    this->setModal(true);

    // Populate dialog elements
    ui_->sb_lower_bound->setValue(lower_bound);
    ui_->sb_upper_bound->setValue(upper_bound);
}

/**
 * @brief Standard destructor.
 */
TorqueCompDialog::~TorqueCompDialog() {
    delete ui_;
}

//------------------------------------------------------------------------------
// !Class Helpers
//------------------------------------------------------------------------------

/**
 * @brief Returns the lower bound value.
 *
 * @return double Lower bound in Nm
 */
double TorqueCompDialog::GetLowerBound() const {
    return ui_->sb_lower_bound->value();
}

/**
 * @brief Returns the upper bound value.
 *
 * @return double Upper bound in Nm
 */
double TorqueCompDialog::GetUpperBound() const {
    return ui_->sb_upper_bound->value();
}

//------------------------------------------------------------------------------
// !Uncategorized
//------------------------------------------------------------------------------
